### PR TITLE
change StateSelector logic

### LINKED ISSUE #7955: Finalized state from `debug/state` API is incorrect on epochs with empty slots in the end
### Description
We return `finalizedAnchor` in `debug/state` API, though if this state is associated with block which is not the last in finalized epoch, finalized state should be transitioned through empty slots to the end of the epoch. It sounds logical for this kind of `id` and `state` API endpoint and is default behavior of the other clients.

### PR DESCRIPTION
**Pull request by rolfyone**
fixes #7955

alternative solution to #8782 

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by rolfyone** [comment]
also moved some private functions to the bottom (breaks my own rule of not refactoring). The new functionality was a finalized selector similar to teh justified flow in CombinedChainDataClient, and a `getBestFinalizedState` which essentially determines the finalized slot to refer to in the same way `on_block` does.

File: data/provider/src/main/java/tech/pegasys/teku/api/stateselector/StateSelectorFactory.java [hunk 1]
```diff
@@ -80,19 +80,13 @@ public StateSelector genesisSelector() {
...
-        SafeFuture.completedFuture(
-            client
-                .getLatestFinalized()
-                .map(
-                    finalized ->
-                        addMetaData(
-                            finalized.getState(),
-                            // The finalized checkpoint may change because of optimistically
-                            // imported blocks at the head and if the head isn't optimistic, the
-                            // finalized block can't be optimistic.
```
Comment (rolfyone) [inline data/provider/src/main/java/tech/pegasys/teku/api/stateselector/StateSelectorFactory.java:92]: there was nothing testing this.

i went with the on_block implementation of the finalized state where we base it off of the checkpoint.

**Review by lucassaldanha — APPROVED** [review]
LGTM
