### PR TITLE
Ensure invalid attestations are not included in blocks

### LINKED ISSUE #1996: Attestations from different forks included in blocks
### Description
Teku is periodically including attestations where the current justified checkpoint doesn't match the attestation source.  This results in the state transition during block creation failing and the validator misses it's block production duty.

```
2020-05-28 13:02:52.050+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event *** Slot: 11114, Block: 0x18d8..3b12, Epoch: 347, Finalized checkpoint: 345, Finalized root: 0xda98..3b64, Peers: 29^[[0m
2020-05-28 13:03:00.086+00:00 | ValidatorApiChannel-0 | WARN  | BlockProcessorUtil | process_attestations: Attestation source error 1
2020-05-28 13:03:00.086+00:00 | ValidatorApiChannel-0 | WARN  | StateTransition | State Transition error
tech.pegasys.teku.core.exceptions.BlockProcessingException: java.lang.IllegalArgumentException: process_attestations: Attestation source error 1
        at tech.pegasys.teku.core.BlockProcessorUtil.process_attestations_no_validation(BlockProcessorUtil.java:456) ~[teku-ethereum-core-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.core.BlockProcessorUtil.process_operations_no_validation(BlockProcessorUtil.java:226) ~[teku-ethereum-core-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.core.StateTransition.lambda$process_block$0(StateTransition.java:130) ~[teku-ethereum-core-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.datastructures.state.BeaconStateImpl.updated(BeaconStateImpl.java:273) ~[teku-ethereum-datastructures-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.core.StateTransition.process_block(StateTransition.java:125) ~[teku-ethereum-core-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:97) ~[teku-ethereum-core-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.core.BlockProposalUtil.createNewUnsignedBlock(BlockProposalUtil.java:78) ~[teku-ethereum-core-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.validator.coordinator.BlockFactory.createUnsignedBlock(BlockFactory.java:97) ~[teku-validator-coordinator-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createUnsignedBlock$3(ValidatorApiHandler.java:144) ~[teku-validator-coordinator-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createFromBlockAndState$4(ValidatorApiHandler.java:159) ~[teku-validator-coordinator-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.util.async.SafeFuture.lambda$thenApplyChecked$16(SafeFuture.java:283) ~[teku-util-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2306) ~[?:?]
        at tech.pegasys.teku.util.async.SafeFuture.thenCompose(SafeFuture.java:320) ~[teku-util-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.util.async.SafeFuture.thenApplyChecked(SafeFuture.java:280) ~[teku-util-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createFromBlockAndState(ValidatorApiHandler.java:154) ~[teku-validator-coordinator-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createUnsignedBlock(ValidatorApiHandler.java:141) ~[teku-validator-coordinator-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at tech.pegasys.teku.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:67) ~[teku-events-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:60) ~[teku-events-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:70) ~[teku-events-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111) [teku-events-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103) [teku-events-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.IllegalArgumentException: process_attestations: Attestation source error 1
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[guava-28.1-jre.jar:?]
        at tech.pegasys.teku.core.BlockProcessorUtil.process_attestations_no_validation(BlockProcessorUtil.java:443) ~[teku-ethereum-core-0.11.3-SNAPSHOT.jar:0.11.3-dev-5f23919c]
        ... 28 more
```

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
Block creation sometimes failed because invalid attestations were included in the block.

This extracts AttestationData validations into a separate class so they can be reused by block processing and selecting which attestations to include.

## Fixed Issue(s)
fixes #1996

### CODE REVIEW

File: ethereum/core/src/main/java/tech/pegasys/teku/core/BlockAttestationDataValidator.java [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+                        .compareTo(state.getSlot())
+                    <= 0,
+                InvalidReason.SUBMITTED_TOO_QUICKLY),
+        () ->
+            check(
+                state
+                        .getSlot()
+                        .compareTo(data.getSlot().plus(UnsignedLong.valueOf(SLOTS_PER_EPOCH)))
+                    <= 0,
+                InvalidReason.SUBMITTED_TOO_FAR_IN_HISTORY),
```
Comment (cemozerr) [inline ethereum/core/src/main/java/tech/pegasys/teku/core/BlockAttestationDataValidator.java]: nit: I know we've been saying `SUBMITTED_TOO_FAR_IN_HISTORY` for a while, but maybe `SUBMITTED_TOO_LATE` could be simpler.

File: ethereum/core/src/main/java/tech/pegasys/teku/core/BlockAttestationDataValidator.java [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+        justifiedCheckpointCheck);
+  }
+
+  @SafeVarargs
+  private Optional<InvalidReason> firstOf(final Supplier<Optional<InvalidReason>>... checks) {
+    return Stream.of(checks)
```
Comment (cemozerr) [inline ethereum/core/src/main/java/tech/pegasys/teku/core/BlockAttestationDataValidator.java:78]: maybe you could add `Stream.parallel()` here

**Review by cemozerr — APPROVED** [review]
Looks good to me, but given the `ValidateableAttestations` concept, and the centralizing of attestation validations and processing we talked about (around `AttestationManager`) I'm not sure if it makes sense to have a `BlockAttestationDataValidator`. 

Not entirely sure, but I'm assuming the checks that we run at `AttestationManager` are a superset of the checks we run here at `BlockAttestationDataValidator`. My guess is that we were including invalid attestations because `AttestationData` in our pool would either get too old, or we'd add them to blocks too quickly. I think a better approach would be to modify `AggregatingAttestationsPool` in such a way that it would drop attestations that are too old (immediately) and when asked for a list of attestations for a block, filters attestations that are too recent.

This way we could make sure we don't repeat validating the same attestation multiple times, and keep the `AggregatingAttestationPool` from growing indefinitely. The only problem in that scenario would be missing to check if attestations aggregated in  `AggregatingAttestationPool` were built correctly, but we should have tests for that anyway.

Still approving because it is a clean simple fix, and we can improve on it as time goes on.

File: ethereum/core/src/main/java/tech/pegasys/teku/core/BlockAttestationDataValidator.java (hunk 2 above)
Comment (ajsutton) [reply ethereum/core/src/main/java/tech/pegasys/teku/core/BlockAttestationDataValidator.java:78]: The checks are quite simple so going parallel would almost certainly reduce performance because of the overhead cost. It would also be a subtle trap in the future if any of the checks depended on each other (e.g. one checks that an index is in range, one then uses that index to check a value).

File: ethereum/core/src/main/java/tech/pegasys/teku/core/BlockAttestationDataValidator.java (hunk 1 above)
Comment (ajsutton) [reply ethereum/core/src/main/java/tech/pegasys/teku/core/BlockAttestationDataValidator.java]: Done.

**Comment by ajsutton** [comment]
I think you've misunderstood what the original problem was.  We were correctly filtering attestations based on slot - the error we were getting was that the attestation source did not match the current justified checkpoint.  To ensure all attestations included in blocks are valid, we need to run all the same validations as would happen when it's in a block - that way we know it's completely valid before we put it in.

I don't think this clashes with the `ValidatableAttestation` work because these validations are contingent on the state for the block the attestation is being included in.  So they aren't checks that we can perform once and remember that it's valid - we need to perform them again with the new block state for every block we consider including them in (and every block we process that includes them).

**Comment by ajsutton** [comment]
Also, the `AggregatingAttestationPool` doesn't grow indefinitely even if attestations are never included in blocks - each slot it drops attestations older than a certain threshold.  We may need to create a block or aggregate for something that isn't the very latest head slot though so it doesn't drop things the instant they can't be included in a block.
