### PR TITLE
Fix VC to BN compatibility for `/eth/v1/validator/beacon_committee_subscriptions`

### LINKED ISSUE #6121: Teku's VC doesn't follow the standard Beacon API spec for `/eth/v1/validator/beacon_committee_subscriptions`
### Description
The Teku VC will send the following body to the BN as part of the `/eth/v1/validator/beacon_committee_subscriptions` when it needs to get validator duties:

```
[{"validator_index":275394,"committee_index":53,"committees_at_slot":"64","slot":"3733432","is_aggregator":false}]
```

According to [the official spec for this route](https://ethereum.github.io/beacon-APIs/#/Validator/prepareBeaconCommitteeSubnet), all of these numerical values need to be strings. However, the `validator_index` and `committee_index` here are integers. This is a small but important deviation from the spec that causes a failure when trying the VC to connect to other clients.

For example, this causes a deserialization error when trying to connect a Teku VC to a Nimbus BN:
```
{"code":"400","message":"Invalid subscription request object(s)","stacktraces":["Unable to deserialize data"]}
```

Wrapping the `validator_index` and `committee_index` values in quotes, like this:
```
[{"validator_index":"275394","committee_index":"53","committees_at_slot":"64","slot":"3733432","is_aggregator":false}]
```

Results in the correct behavior.

### Steps to Reproduce (Bug)

**Expected behavior:** Teku's VC successfully connects to a different client's BN and submits successful attestations

**Actual behavior:** Teku's VC errors out when connecting to a different client's BN

**Frequency:** 100%

### Versions
* Software version: v22.8.1
* Java version: ---
* OS Name & Version: Debian 11 x64
* Docker Version: 20.10.17
* Cloud VM, type, size: N/A

### PR DESCRIPTION
**Pull request by StefanBratanov**
## PR Description
Change `BeaconCommitteeSubscriptionRequest` to use String instead of int in order to make Jackson quote the `validator_index` and `committee_index`

## Fixed Issue(s)
fixes #6121 

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: data/serializer/src/main/java/tech/pegasys/teku/api/request/v1/validator/BeaconCommitteeSubscriptionRequest.java [hunk 1]
```diff
@@ -21,11 +21,11 @@
 @SuppressWarnings("JavaCase")
 public class BeaconCommitteeSubscriptionRequest {
 
-  @Schema(type = "string", format = "uint64")
-  public final int validator_index;
+  @Schema(type = "string")
```
Comment (rolfyone) [inline data/serializer/src/main/java/tech/pegasys/teku/api/request/v1/validator/BeaconCommitteeSubscriptionRequest.java]: delete schema line, redundant

File: data/serializer/src/main/java/tech/pegasys/teku/api/request/v1/validator/BeaconCommitteeSubscriptionRequest.java [hunk 2]
```diff
@@ -21,11 +21,11 @@
...
+  public final String validator_index;
 
-  @Schema(type = "string", format = "uint64")
-  public final int committee_index;
+  @Schema(type = "string")
```
Comment (rolfyone) [inline data/serializer/src/main/java/tech/pegasys/teku/api/request/v1/validator/BeaconCommitteeSubscriptionRequest.java]: delete schema line

File: data/serializer/src/main/java/tech/pegasys/teku/api/request/v1/validator/BeaconCommitteeSubscriptionRequest.java [hunk 3]
```diff
@@ -37,8 +37,8 @@ public class BeaconCommitteeSubscriptionRequest {
 
   @JsonCreator
   public BeaconCommitteeSubscriptionRequest(
-      @JsonProperty("validator_index") final int validator_index,
-      @JsonProperty("committee_index") final int committee_index,
+      @JsonProperty("validator_index") final String validator_index,
+      @JsonProperty("committee_index") final String committee_index,
```
Comment (rolfyone) [inline data/serializer/src/main/java/tech/pegasys/teku/api/request/v1/validator/BeaconCommitteeSubscriptionRequest.java:40]: wonder if we want to CheckNotNull on these two now that its nullable... maybe a test to show we handle things ok if these fields aren't set - should be a 400 not a 500 error...

**Review by rolfyone — APPROVED** [review]
overall looks good, a couple of nits and maybe another test case..

File: data/serializer/src/main/java/tech/pegasys/teku/api/request/v1/validator/BeaconCommitteeSubscriptionRequest.java (hunk 3 above)
Comment (rolfyone) [reply data/serializer/src/main/java/tech/pegasys/teku/api/request/v1/validator/BeaconCommitteeSubscriptionRequest.java:40]: may translate to an illegalArgumentException depending on where you are maybe...

Comment (StefanBratanov) [reply data/serializer/src/main/java/tech/pegasys/teku/api/request/v1/validator/BeaconCommitteeSubscriptionRequest.java:40]: thank you, added `checkNotNull` preconditon to both fields

**Review by tbenr — APPROVED** [review]
LGTM too. I'd just do a paranoia backward compatibility test against our BN.
Paranoia backward compatibility: `RemoteValidatorAcceptanceTest` should eventually find any issues.
