### PR TITLE
Standardise the Engine JSON-RPC error codes

### LINKED ISSUE #8671: Standardise the Engine Json RPC error codes
The json RPC error codes are standard: [JSON-RPC 2.0 Specification](https://www.jsonrpc.org/specification#error_object)
It would be better to handle the errors in the `Web3JClient::doRequest` based on their codes and avoid logging the whole stack trace.
Example: error code `-32601` -> 	Method not found

### PR DESCRIPTION
**Pull request by Malaydewangan09**
## PR Description
This pull request standardises the handling of JSON-RPC error codes in the Web3JClient::doRequest method according to the JSON-RPC 2.0 specification. It introduces specific error code handling for well-known JSON-RPC errors and customizes error messages to reduce unnecessary stack trace logging.

## Fixed Issue(s)
fixes #8671 

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+ */
+
+package tech.pegasys.teku.ethereum.executionclient.web3j;
+
+import java.util.Collections;
+import java.util.HashMap;
+import java.util.Map;
+
+public final class JsonRpcErrorCodes {
+  public static final int PARSE_ERROR = -32700;
```
Comment (tbenr) [inline ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java]: I'd convert this to an Enum with `errorCode` and `description` fields, so you can avoid this static fields\initialization

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java [hunk 2]
```diff
@@ -86,21 +85,40 @@ public <T> SafeFuture<Response<T>> doRequest(
...
+    final boolean couldBeAuthError = isAuthenticationException(exception);
+    handleError(isCriticalRequest, exception, couldBeAuthError);
+    return Response.withErrorMessage(getMessageOrSimpleName(exception));
+  }
+
+  private <T> Response<T> handleJsonRpcError(
+      final org.web3j.protocol.core.Response.Error error, final boolean isCriticalRequest) {
+    int errorCode = error.getCode();
+    String errorType = JsonRpcErrorCodes.getErrorMessage(errorCode);
+    String formattedError = String.format("%s (%d): %s", errorType, errorCode, error.getMessage());
```
Comment (tbenr) [inline ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java]: these vars can be `final`

**Review by tbenr — COMMENTED** [review]
Thanks! Looks nice so far.
I have some comments and I think we should add some tests in `Web3JClientTest`

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java (hunk 2 above)
Comment (Malaydewangan09) [reply ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java]: Sure @tbenr
I'll update this

**Comment by Malaydewangan09** [comment]
Hey @tbenr 
I've refactored the JsonRpcErrorCodes class to use an enum for improved structure and efficiency. 
However, I'm looking for help in writing or updating the corresponding test cases for this change.

**Comment by tbenr** [comment]
Hey @Malaydewangan09 I don't see the update on the Enum front. Can you double check?
Thanks!

**Comment by Malaydewangan09** [comment]
Hey @tbenr, my bad. 
I've updated the class to an Enum. 
Can you please check the changes?

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+
+  public static String getErrorMessage(final int errorCode) {
+    return fromCode(errorCode).getDescription();
+  }
+
+  public static JsonRpcErrorCodes fromCode(final int errorCode) {
+    for (JsonRpcErrorCodes error : values()) {
+      if (error.getErrorCode() == errorCode) {
+        return error;
+      }
```
Comment (tbenr) [inline ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java]: I suspect to make this better we could have a static `Int2ObjectOpenHashMap` map that could be fed in the `JsonRpcErrorCodes` constructor, so we could lookup a map instead of looping over the codes

Comment (Malaydewangan09) [reply ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java]: Okay @tbenr 
Let me know if this is what we are aiming for 
image

Comment (tbenr) [reply ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java]: @Malaydewangan09  yes! My suggestion wasn't totally correct but you got it right

Comment (Malaydewangan09) [reply ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java]: Okay @tbenr 
Thanks!

**Comment by tbenr** [comment]
WRT testing you could:

take inspiration from `shouldNotUpdateAvailabilityWhenNonCriticalMethodFailsWithErrorResponse` on how to simulate an error and from `shouldTimeoutIfResponseNotReceived` on how to get the response and check that the mapping has been applied. I'd add one test covering the fact that the errors are decoded via JsonRpcErrorCodes as expected.

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java [hunk 4]
```diff
@@ -23,6 +25,14 @@ public enum JsonRpcErrorCodes {
 
   private final int errorCode;
   private final String description;
+  private static final Int2ObjectOpenHashMap<JsonRpcErrorCodes> CODE_TO_ERROR_MAP;
+
+  static {
+    CODE_TO_ERROR_MAP = new Int2ObjectOpenHashMap<>();
+    for (JsonRpcErrorCodes error : values()) {
```
Comment (tbenr) [inline ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java]: `final JsonRpcErrorCodes error : values()`

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java [hunk 5]
```diff
@@ -42,10 +52,9 @@ public static String getErrorMessage(final int errorCode) {
   }
 
   public static JsonRpcErrorCodes fromCode(final int errorCode) {
-    for (JsonRpcErrorCodes error : values()) {
-      if (error.getErrorCode() == errorCode) {
-        return error;
-      }
+    JsonRpcErrorCodes error = CODE_TO_ERROR_MAP.get(errorCode);
```
Comment (tbenr) [inline ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java]: `final`

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+ * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
+ * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
+ * specific language governing permissions and limitations under the License.
+ */
+
+package tech.pegasys.teku.ethereum.executionclient.web3j;
+
+import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
+
+public enum JsonRpcErrorCodes {
```
Comment (tbenr) [inline ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java]: maybe we can remove `public` have this package private.

Comment (Malaydewangan18) [reply ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java:18]: Got it, @tbenr 
I have done these locally 
I'll try to write the test cases and push the final changes

Comment (Malaydewangan09) [reply ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java]: Got it, @tbenr
I have done these locally
I'll try to write the test cases and push the final changes

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+
+  public int getErrorCode() {
+    return errorCode;
+  }
+
+  public String getDescription() {
+    return description;
+  }
+
+  public static String getErrorMessage(final int errorCode) {
```
Comment (tbenr) [inline ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/JsonRpcErrorCodes.java]: I'd name this `getDescription` too

**Comment by tbenr** [comment]
I think there is still something to improve:

image

maybe the final error should be something like `JSON-RPC error: Invalid params (-32602)` ?

**Comment by Malaydewangan09** [comment]
Ah yes, that would be a more concise error message.
I'll update the message.

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java (hunk 2 above)
Comment (tbenr) [reply ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java]: @Malaydewangan09 don't forget the `final`s here :)

**Comment by tbenr** [comment]
sorry I got confused by repetition of `Invalid params`. The first is the decoded error description, the second is the message coming from the server. I'd change the message to be something different in the test.

**Comment by Malaydewangan09** [comment]
@tbenr 
I'd like to clarify the purpose of your comment about the repetition of 'Invalid params'. Were you suggesting we make the test case more realistic by using a distinct server error message, or was there another reason for pointing out this repetition?

**Comment by tbenr** [comment]
> @tbenr I'd like to clarify the purpose of your comment about the repetition of 'Invalid params'. Were you suggesting we make the test case more realistic by using a distinct server error message, or was there another reason for pointing out this repetition?

@Malaydewangan09 Yes, I was suggesting to make the test more realistic and thus less confusing. The message from the server could be something more verbose like "engine_newPaylad method has been called with invalid parameters"

**Review by tbenr — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by Malaydewangan09** [comment]
@tbenr Thanks for your consistent feedback!
