### PR TITLE
Move processWithdrawalRequests to BlockProcessorElectra

### LINKED ISSUE #8680: Investigate failures with EL withdrawal requests sanity blocks ref tests
The following tests are failing on reference tests `v1.5.0-alpha.7`"
- ~~sanity/blocks - basic_el_withdrawal_request~~
- ~~sanity/blocks - cl_exit_and_el_withdrawal_requests_in_same_block~~
- sanity/blocks - basic_btec_and_el_withdrawal_request_in_same_block

They are being ignored on `SanityBlocksTestExecutor`

### PR DESCRIPTION
**Pull request by gfukushima**
## PR Description
This PR fixes the issue detected in the reference test `basic_btec_and_el_withdrawal_request_in_same_block` which is caused by trying to process the withdrawal request before the blsToExecutionChange operation.

## Fixed Issue(s)

Fixes #8680 

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: eth-reference-tests/src/referenceTest/java/tech/pegasys/teku/reference/phase0/sanity/SanityBlocksTestExecutor.java [hunk 1]
```diff
@@ -42,11 +42,7 @@ public class SanityBlocksTestExecutor implements TestExecutor {
       "Block state root does NOT match the calculated state root";
 
   // TODO re-enable tests as part of https://github.com/Consensys/teku/issues/8680
-  private static final List<String> IGNORED_TEST_NAMES =
-      List.of(
-          "basic_el_withdrawal_request",
-          "basic_btec_and_el_withdrawal_request_in_same_block",
-          "cl_exit_and_el_withdrawal_request_in_same_block");
+  private static final List<String> IGNORED_TEST_NAMES = List.of();
```
Comment (tbenr) [inline eth-reference-tests/src/referenceTest/java/tech/pegasys/teku/reference/phase0/sanity/SanityBlocksTestExecutor.java:44]: you can remove the `//TODO` correct?

**Review by tbenr — APPROVED** [review]
LGTM

File: eth-reference-tests/src/referenceTest/java/tech/pegasys/teku/reference/phase0/sanity/SanityBlocksTestExecutor.java (hunk 1 above)
Comment (gfukushima) [reply eth-reference-tests/src/referenceTest/java/tech/pegasys/teku/reference/phase0/sanity/SanityBlocksTestExecutor.java:44]: done, thanks for catching this
