### PR TITLE
Teku fails to start when Validator API cannot read password file

### LINKED ISSUE #7708: if validator-api-bearer cannot be created or read, needs to be handled better
An example on discord was re. the validator-api-bearer existing, but being a folder rather than a file.

This could be clearer if it does occur, as the service won't be able to be accessed without that bearer token.

At a minimum I would suggest if it's not a file, or can't be read, then an error should be written to log, because that's effectively failing to start something (can't be accessed, even if it's running).

### PR DESCRIPTION
**Pull request by lucassaldanha**
## PR Description
Before this change, if Teku couldn't read the password file for any reason, it would start up but it wouldn't serve any Validator API requests. This can be misleading so we decided to fail-fast and don't startup if something is wrong (likely to be a configuration issue).

## Fixed Issue(s)
fixes #7708 

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: infrastructure/restapi/src/test/java/tech/pegasys/teku/infrastructure/restapi/AuthorizationManagerTest.java [hunk 1]
```diff
@@ -82,31 +83,6 @@ void shouldDenyAccessIfHeaderNotSet(@TempDir final Path tempDir) throws Exceptio
...
-    when(context.method()).thenReturn(HandlerType.GET);
-    when(context.matchedPath()).thenReturn("/aPath");
-    when(context.header("Authorization")).thenReturn(null);
-    AuthorizationManager manager = new AuthorizationManager(tempDir.resolve("passwd"));
-    manager.manage(handler, context, roles);
-    verify(handler, times(0)).handle(context);
-    verify(context).status(401);
-    verify(context).json(any());
-  }
-
```
Comment (lucassaldanha) [inline infrastructure/restapi/src/test/java/tech/pegasys/teku/infrastructure/restapi/AuthorizationManagerTest.java:109]: Removed these 2 tests now that we don't have a state with no bearer loaded.

File: CHANGELOG.md [hunk 2]
```diff
@@ -11,6 +11,7 @@ the [releases page](https://github.com/Consensys/teku/releases).
 
 ### Breaking Changes
 - By default, Teku won't allow syncing from genesis, users should use `--checkpoint-sync-url` when starting a new node. It is possible to revert back to the previous behaviour using the flag `--ignore-weak-subjectivity-period-enabled`.
+- Teku will fail to start if the Validator API cannot read the password file used for authorization.
```
Comment (rolfyone) [inline CHANGELOG.md]: Maybe add something like 'Previously, if the validator-api was enabled and the password file was not available, the validator would continue to startup without the validator-api` or something...

File: infrastructure/restapi/src/main/java/tech/pegasys/teku/infrastructure/restapi/AuthorizationManager.java [hunk 3]
```diff
@@ -34,22 +33,53 @@
...
+                    String.format("password file %s is empty", passwordFile.getAbsolutePath()));
+                LOG.error(errorMessage);
+                return new IllegalStateException(errorMessage.toString());
+              });
     } catch (IOException e) {
-      LOG.error(initFailedMessage, e);
-      bearer = Optional.empty();
+      errorMessage.append(String.format(e.getMessage(), passwordFile.getAbsolutePath()));
+      LOG.error(errorMessage);
+      throw new IllegalStateException(errorMessage.toString());
```
Comment (rolfyone) [inline infrastructure/restapi/src/main/java/tech/pegasys/teku/infrastructure/restapi/AuthorizationManager.java]: i think this is another case where we probably dont want to throw Illegal state, much for the same reason that we'd be spamming the logs with tons of data...

**Review by rolfyone — APPROVED** [review]
LGTM, probably worth addressing the codeql (even if to reject)
