### PR TITLE
AbstractByteBufDecoder: don't close twice

### LINKED ISSUE #3069: Build tests are currently failing
I'm unable to build Teku when running `./gradlew build`.

Java version : `java 12.0.2 2019-07-16`
OS: macOS Catalina

The following tests are failing:

```
Eth2OutgoingRequestHandlerTest$Eth2OutgoingRequestHandlerTest_ssz > shouldCompleteExceptionallyWhenClosedWithTruncatedMessage() FAILED
    io.netty.util.IllegalReferenceCountException at ReferenceCountUpdater.java:74

Eth2OutgoingRequestHandlerTest$Eth2OutgoingRequestHandlerTest_sszSnappy > shouldCompleteExceptionallyWhenClosedWithTruncatedMessage() FAILED
    io.netty.util.IllegalReferenceCountException at ReferenceCountUpdater.java:74
```
My Java version is `java 12.0.2 2019-07-16`

### PR DESCRIPTION
**Pull request by Nashatyrev**
## PR Description

Avoid closing `AbstractByteBufDecoder` twice

## Fixed Issue(s)

Fix #3069 

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/core/encodings/AbstractByteBufDecoder.java [hunk 1]
```diff
@@ -30,12 +30,16 @@
...
+  private boolean closed = false;
 
   @Override
   public Optional<TMessage> decodeOneMessage(ByteBuf in) throws TException {
     if (!in.isReadable()) {
       return Optional.empty();
     }
+    if (closed) {
+      throw new IllegalStateException("Trying to reuse disposed decoder instance");
+    }
```
Comment (mbaxter) [inline networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/core/encodings/AbstractByteBufDecoder.java]: (nit / optional) We could move this to a helper method `assertOpen()`

**Review by mbaxter — APPROVED** [review]

**Comment by Nashatyrev** [comment]
Yep good idea :+1: Just named it `assertNotClosed` since `Opened` sounds a bit weird with respect to `Decoder` :)

File: networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/core/encodings/AbstractByteBufDecoder.java (hunk 1 above)
Comment (Nashatyrev) [reply networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/core/encodings/AbstractByteBufDecoder.java]: Yep good idea  👍  Just named it `assertNotClosed` since `Opened` sounds a bit weird with respect to `Decoder` IMO :)
