### PR TITLE
Readiness api returning 'unavailable' when EL isn't available

### LINKED ISSUE #6236: The /readiness endpoint returns 200 when EL is in bad state
### Description
Our EL client fell behind and Teku stopped performing its duties but /readiness endpoint still returned 200 OK. Some errors seen in teku:

```
 | 2022-09-21 09:29:03 | Caused by: java.lang.IllegalArgumentException: Cannot get active validator indices from an epoch beyond the seed lookahead period. Requested epoch 148241 from state in epoch 14823
...
 | 2022-09-21 09:29:04 | java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Invalid remote response: Failed to connect to execution-client-teku-beacon-2/10.0.125.57:8550
...
| 2022-09-21 09:29:04 | 2022-09-21 08:29:04.053 ERROR - Failed to update fork choice
...
```
And teku was not following the chain in that period.

### Steps to Reproduce (Bug)

**Expected behavior:** /readiness endpoint should return a 50x error code

**Actual behavior:** /readiness endpoint returns 200 OK

### Versions (Add all that apply)
* Software version: 22.9.1

### PR DESCRIPTION
**Pull request by lucassaldanha**
## PR Description

`/readiness` endpoint now will check if EL client is available. If EL is not available, it returns a 503 status code.

`ExecutionClientDataProvider` subscribes to `ExecutionClientEventsChannel` to listen to EL online/offline events.

## Fixed Issue(s)
fixes #6236 

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by tbenr — APPROVED** [review]
LGTM

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java [hunk 1]
```diff
@@ -117,11 +117,10 @@ protected void handleSuccess() {
     final long lastErrorTime = lastError.getAndUpdate(x -> NO_ERROR_TIME);
     if (lastErrorTime == STARTUP_LAST_ERROR_TIME) {
       eventLog.executionClientIsOnline();
-      executionClientEventsPublisher.onAvailabilityUpdated(true);
     } else if (lastErrorTime != NO_ERROR_TIME) {
       eventLog.executionClientRecovered();
-      executionClientEventsPublisher.onAvailabilityUpdated(true);
     }
+    executionClientEventsPublisher.onAvailabilityUpdated(true);
```
Comment (tbenr) [inline ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java]: moving the call here you'll call it on every successful call (which cause some UT to fail). I'd revert it to what was before, unless you have an argument for doing so :)

Comment (lucassaldanha) [reply ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java]: I think I thought about simplifying the code and forgot I planned to avoid unnecessarily publishing the event when we are already available. :)
