### PR TITLE
Attestation criteria change

### LINKED ISSUE #575: verify_bitfields_and_aggregate_signatures error in network mode
### Description

BlockProcessingException thrown in processAttestations() (see screenshot):
image

### Steps to Reproduce (Bug)
1. ./gradlew mash
2. cd scripts && sh demo.sh
3. Wait for the error at the first epoch boundary

### PR DESCRIPTION
**Pull request by jrhea**
## PR Description
- This PR adopts a fix from v5.1 to allow for a relaxed constraint for adding older attestations

image

## Fixed Issue(s)

- resolves #575 
- another syncronization fix
- fixed a integration test bug

### CODE REVIEW

File: validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java [hunk 1]
```diff
@@ -104,6 +104,15 @@ public void onNewHeadStateEvent(HeadStateEvent headStateEvent) {
       this.eventBus.post(attestation);
     }
 
+    List<Attestation> blockAttestations = headBlock.getBody().getAttestations();
+    synchronized (this.attestationsQueue) {
```
Comment (cemozerr) [inline validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java:108]: What does this synchronized (this.attestationsQueue) do here?

**Review by cemozerr — APPROVED** [review]
LGTM.

File: validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java (hunk 1 above)
Comment (jrhea) [reply validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java:108]: i don;t want attestation being added to the queue while i am looking through the list for potential dupes. which, btw, never finds any.   I feel like we need to remove already processed attestations from that queue as need blocks come in with attestations
