### PR TITLE
startup should fail if storage fails to start in some cases.

### LINKED ISSUE #2368: Teku silently stalls when existing storage is incompatible with configured network
### Description
When starting Teku from an existing database using `minimal` configuration but configuring Teku for `altona`, it gets as far as `Initializing storage` and hangs.

The problem is that `StorageBackedRecentChainData.requestInitialStoreWithRetry` is automatically retrying when the request to load the initial store fails for any reason and suppressing the error.  It should only retry on timeout exceptions.  The suppressed exception is:

```
org.apache.tuweni.ssz.InvalidSSZTypeException: SSZ encoded data is not a fixed-length byte array
	at org.apache.tuweni.ssz.BytesSSZReader.ensureBytes(BytesSSZReader.java:217) ~[tuweni-ssz-1.0.0.jar:1.0.0]
	at org.apache.tuweni.ssz.BytesSSZReader.readFixedBytes(BytesSSZReader.java:61) ~[tuweni-ssz-1.0.0.jar:1.0.0]
	at org.apache.tuweni.ssz.SSZReader.readFixedBytes(SSZReader.java:66) ~[tuweni-ssz-1.0.0.jar:1.0.0]
	at tech.pegasys.teku.datastructures.util.SimpleOffsetSerializer.deserializePrimitive(SimpleOffsetSerializer.java:497) ~[teku-ethereum-datastructures-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.datastructures.util.SimpleOffsetSerializer.deserializeFixedElementVector(SimpleOffsetSerializer.java:468) ~[teku-ethereum-datastructures-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.datastructures.util.SimpleOffsetSerializer.deserializeFixedParts(SimpleOffsetSerializer.java:321) ~[teku-ethereum-datastructures-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.datastructures.util.SimpleOffsetSerializer.deserializeContainer(SimpleOffsetSerializer.java:264) ~[teku-ethereum-datastructures-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.datastructures.util.SimpleOffsetSerializer.deserializeContainerErrorWrapper(SimpleOffsetSerializer.java:244) ~[teku-ethereum-datastructures-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.datastructures.util.SimpleOffsetSerializer.lambda$deserialize$1(SimpleOffsetSerializer.java:216) ~[teku-ethereum-datastructures-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at org.apache.tuweni.ssz.SSZ.decode(SSZ.java:1255) ~[tuweni-ssz-1.0.0.jar:1.0.0]
	at tech.pegasys.teku.datastructures.util.SimpleOffsetSerializer.deserialize(SimpleOffsetSerializer.java:212) ~[teku-ethereum-datastructures-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.storage.server.rocksdb.serialization.SszSerializer.deserialize(SszSerializer.java:30) ~[teku-storage-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.storage.server.rocksdb.serialization.SszSerializer.deserialize(SszSerializer.java:20) ~[teku-storage-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance.lambda$get$0(RocksDbInstance.java:66) ~[teku-storage-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at java.util.Optional.map(Optional.java:265) ~[?:?]
	at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance.get(RocksDbInstance.java:66) ~[teku-storage-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.storage.server.rocksdb.dataaccess.V4HotRocksDbDao.getLatestFinalizedState(V4HotRocksDbDao.java:78) ~[teku-storage-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.createMemoryStore(RocksDbDatabase.java:185) ~[teku-storage-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.storage.server.ChainStorage.getStore(ChainStorage.java:68) ~[teku-storage-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.storage.server.ChainStorage.onStoreRequest(ChainStorage.java:84) ~[teku-storage-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at tech.pegasys.teku.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-events-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-events-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:75) ~[teku-events-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) ~[teku-events-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) ~[teku-events-0.12.2-SNAPSHOT.jar:0.12.2-dev-9acab2fd]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

### PR DESCRIPTION
**Pull request by rolfyone**
- startup now fails if storage causes anything other than a TimeoutException

 - added regression test to show storage failing for an IOException

 - added debug trace to include stack trace if context is required.

 fixes #2368

Signed-off-by: Paul Harris <paul.harris@consensys.net>

## Documentation

- [X] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: logging/src/main/java/tech/pegasys/teku/logging/StatusLogger.java [hunk 1]
```diff
@@ -98,6 +98,18 @@ public void beginInitializingChainData() {
     log.info("Initializing storage");
   }
 
+  public void initializingChainDataTimeout() {
+    log.info("storage initialisation timed out, will retry.");
+  }
```
Comment (ajsutton) [inline logging/src/main/java/tech/pegasys/teku/logging/StatusLogger.java]: We don't want to log this to the console.  Just a normal trace log in `StorageBackedRecentChainData` would be enough. We'll almost certainly hit this at least once during startup because of the order that services start.

File: logging/src/main/java/tech/pegasys/teku/logging/StatusLogger.java [hunk 2]
```diff
@@ -98,6 +98,18 @@ public void beginInitializingChainData() {
...
+
+  public void fatalErrorInitialisingStorage(Throwable err) {
+    log.debug("Failed to intiailize storage", err);
+    log.fatal(
+        "Failed to initialize storage. "
+            + "Is your network set in line with your existing database? "
```
Comment (ajsutton) [inline logging/src/main/java/tech/pegasys/teku/logging/StatusLogger.java]:
```suggestion
            + "Check the existing database matches the current network configuration. "
```

**Review by ajsutton — APPROVED** [review]
LGTM.
