### PR TITLE
Don't throw unchecked exceptions when creating requests for builders

### LINKED ISSUE #6109: Error `Failed to send validator registrations to Beacon Node` when using MEV-Boost on Goerli
### Description
- When using the following combo: Geth, Teku, MEV-boost, Web3Signer
- When starting the VC (a few minutes after the BN, to be sure the BN is well started)

I get the following error on VC:
```
2022-08-22 09:17:11.606 INFO  - Loaded validator key 90 of 109.
2022-08-22 09:17:11.608 INFO  - Loaded validator key 100 of 109.
2022-08-22 09:17:11.650 INFO  - Loaded 109 validators
2022-08-22 09:17:11.728 INFO  - Metrics service started and listening on 0.0.0.0:8008
2022-08-22 09:17:11.748 INFO  - Proposer config successfully loaded. It contains the default configuration and 0 specific configuration(s).
2022-08-22 09:17:11.768 INFO  - Starting EventSource client using URI: http://goerli-teku-beacon-0.goerli-teku-beacon.ethereum-common:5051/eth/v1/events?topics=head
2022-08-22 09:17:11.804 INFO  - Connected to EventSource stream.
2022-08-22 09:17:11.841 INFO  - Validator   *** Successfully connected to beacon node event stream
2022-08-22 09:17:11.951 INFO  - 103 validators are in active_ongoing state.
2022-08-22 09:17:11.951 WARN  - Unable to retrieve status for 6 validators.
2022-08-22 09:17:12.316 INFO  - Validator   *** Slashing protection loaded for validators: a1ec5a0, 89bb733, a7c4af0, 9472591, b973c80, b05a334, a3b17d0, 97d2753, a8a4c77, 8ae85f5, b652b72, a287f32, aa9d53a, 8fa37b3, 8b6946a, b5a6d14, aeb2ddc, b8dcbe8, b7ed740, b6495fd… (103 total)
2022-08-22 09:17:12.326 WARN  - Validator   *** Slashing protection not loaded for validators: 84b5bf7, a1aafb7, 990edf3, 8e41ca5, 8a7fd13, 8a4b172
2022-08-22 09:17:13.914 INFO  - Validator   *** Published attestation        Count: 1, Slot: 3720986, Root: 3b6fda033b351b82e52f2df13d007a6808b8806626c3b9500265589166f8cce3
2022-08-22 09:17:14.472 INFO  - 0 out of 103 validator(s) registrations were successfully sent to the Beacon Node.
2022-08-22 09:17:14.472 ERROR - Validator   *** Failed to send validator registrations to Beacon Node
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Invalid params response from Beacon Node API (url = http://goerli-teku-beacon-0.goerli-teku-beacon.ethereum-common:5051/eth/v1/validator/register_validator)
at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[teku-infrastructure-async-22.8.1.jar:22.8.1]
at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:580) ~[teku-infrastructure-async-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$30(SafeFuture.java:399) ~[teku-infrastructure-async-22.8.1.jar:22.8.1]
at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[teku-infrastructure-async-22.8.1.jar:22.8.1]
at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:580) ~[teku-infrastructure-async-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:293) ~[teku-infrastructure-async-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-22.8.1.jar:22.8.1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Invalid params response from Beacon Node API (url = http://goerli-teku-beacon-0.goerli-teku-beacon.ethereum-common:5051/eth/v1/validator/register_validator)
at tech.pegasys.teku.validator.remote.typedef.ResponseHandler.defaultBadRequestHandler(ResponseHandler.java:133) ~[teku-validator-remote-22.8.1.jar:22.8.1]
at tech.pegasys.teku.validator.remote.typedef.ResponseHandler.handleResponse(ResponseHandler.java:92) ~[teku-validator-remote-22.8.1.jar:22.8.1]
at tech.pegasys.teku.validator.remote.typedef.handlers.AbstractTypeDefRequest.executeCall(AbstractTypeDefRequest.java:149) ~[teku-validator-remote-22.8.1.jar:22.8.1]
at tech.pegasys.teku.validator.remote.typedef.handlers.AbstractTypeDefRequest.postJson(AbstractTypeDefRequest.java:127) ~[teku-validator-remote-22.8.1.jar:22.8.1]
at tech.pegasys.teku.validator.remote.typedef.handlers.RegisterValidatorsRequest.sendValidatorRegistrationsAsJson(RegisterValidatorsRequest.java:77) ~[teku-validator-remote-22.8.1.jar:22.8.1]
at tech.pegasys.teku.validator.remote.typedef.handlers.RegisterValidatorsRequest.registerValidators(RegisterValidatorsRequest.java:52) ~[teku-validator-remote-22.8.1.jar:22.8.1]
at tech.pegasys.teku.validator.remote.typedef.OkHttpValidatorTypeDefClient.registerValidators(OkHttpValidatorTypeDefClient.java:101) ~[teku-validator-remote-22.8.1.jar:22.8.1]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.lambda$registerValidators$30(RemoteValidatorApiHandler.java:443) ~[teku-validator-remote-22.8.1.jar:22.8.1]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.lambda$sendRequest$31(RemoteValidatorApiHandler.java:449) ~[teku-validator-remote-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[teku-infrastructure-async-22.8.1.jar:22.8.1]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.sendRequest(RemoteValidatorApiHandler.java:460) ~[teku-validator-remote-22.8.1.jar:22.8.1]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.lambda$sendRequest$32(RemoteValidatorApiHandler.java:455) ~[teku-validator-remote-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[teku-infrastructure-async-22.8.1.jar:22.8.1]
... 4 more
2022-08-22 09:17:28.257 INFO  - Validator   *** Published attestation        Count: 7, Slot: 3720987, Root: 3b6fda033b351b82e52f2df13d007a6808b8806626c3b9500265589166f8cce3
2022-08-22 09:17:36.800 INFO  - Validator   *** Published attestation        Count: 3, Slot: 3720988, Root: a0a97ea603ac52d1bb443bab89ff95339b7066fd212d53f9e0d344bdcab771e3
2022-08-22 09:17:44.028 INFO  - Validator   *** Published aggregate          Count: 1, Slot: 3720988, Root: a0a97ea603ac52d1bb443bab89ff95339b7066fd212d53f9e0d344bdcab771e3
2022-08-22 09:17:48.763 INFO  - Validator   *** Published attestation        Count: 3, Slot: 3720989, Root: b876f1a9f0aa40673729c055de3ea5480b667ec864e97e5ef12f07a5f03cff48
2022-08-22 09:17:56.015 INFO  - Validator   *** Published aggregate          Count: 1, Slot: 3720989, Root: b876f1a9f0aa40673729c055de3ea5480b667ec864e97e5ef12f07a5f03cff48
2022-08-22 09:18:04.116 INFO  - Validator   *** Published attestation        Count: 3, Slot: 3720990, Root: b876f1a9f0aa40673729c055de3ea5480b667ec864e97e5ef12f07a5f03cff48
2022-08-22 09:18:13.671 INFO  - Validator   *** Published attestation        Count: 2, Slot: 3720991, Root: e94579632bc4cbae01b1a4fa871bb8bd2d7d5772d5918bbb9bd935e93719368c
2022-08-22 09:18:25.016 INFO  - 103 out of 103 validator(s) registrations were successfully sent to the Beacon Node.
```

Important lines are:
```
2022-08-22 09:17:14.472 ERROR - Validator   *** Failed to send validator registrations to Beacon Node
```

And eventually (but **NOT** always, or maybe after a very long time):
```
2022-08-22 09:18:25.016 INFO  - 103 out of 103 validator(s) registrations were successfully sent to the Beacon Node.
```

At the same time, the BN has this error:

```
2022-08-22 09:17:04.051 INFO  - Slot Event  *** Slot: 3720985, Block: aa6b3ed7954489ada71223c2ef6dc741202c0157d25e8815ca326f8c5819cf98, Justified: 116279, Finalized: 116278, Peers: 50
2022-08-22 09:17:13.481 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for OkHttp Dispatcher
java.io.UncheckedIOException: java.net.SocketException: Broken pipe
at tech.pegasys.teku.infrastructure.json.JsonUtil.serializeToBytes(JsonUtil.java:71) ~[teku-infrastructure-json-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.json.JsonUtil.serializeToBytes(JsonUtil.java:60) ~[teku-infrastructure-json-22.8.1.jar:22.8.1]
at tech.pegasys.teku.ethereum.executionclient.rest.OkHttpRestClient$1.writeTo(OkHttpRestClient.java:122) ~[teku-ethereum-executionclient-22.8.1.jar:22.8.1]
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) ~[okhttp-4.9.2.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.net.SocketException: Broken pipe
at sun.nio.ch.NioSocketImpl.implWrite(Unknown Source) ~[?:?]
at sun.nio.ch.NioSocketImpl.write(Unknown Source) ~[?:?]
at sun.nio.ch.NioSocketImpl$2.write(Unknown Source) ~[?:?]
at java.net.Socket$SocketOutputStream.write(Unknown Source) ~[?:?]
at okio.OutputStreamSink.write(JvmOkio.kt:53) ~[okio-jvm-2.8.0.jar:?]
at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103) ~[okio-jvm-2.8.0.jar:?]
at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255) ~[okio-jvm-2.8.0.jar:?]
at okio.RealBufferedSink.write(RealBufferedSink.kt:146) ~[okio-jvm-2.8.0.jar:?]
at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSink.write(Http1ExchangeCodec.kt:303) ~[okhttp-4.9.2.jar:?]
at okio.ForwardingSink.write(ForwardingSink.kt:29) ~[okio-jvm-2.8.0.jar:?]
at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218) ~[okhttp-4.9.2.jar:?]
at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255) ~[okio-jvm-2.8.0.jar:?]
at okio.RealBufferedSink$outputStream$1.write(RealBufferedSink.kt:117) ~[okio-jvm-2.8.0.jar:?]
at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2171) ~[jackson-core-2.13.3.jar:2.13.3]
at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:515) ~[jackson-core-2.13.3.jar:2.13.3]
at tech.pegasys.teku.infrastructure.json.types.StringBasedPrimitiveTypeDefinition.serialize(StringBasedPrimitiveTypeDefinition.java:86) ~[teku-infrastructure-json-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.ssz.schema.json.SszTypeDefinitionWrapper.serialize(SszTypeDefinitionWrapper.java:58) ~[teku-infrastructure-ssz-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.ssz.schema.json.SszTypeDefinitionWrapper.serialize(SszTypeDefinitionWrapper.java:27) ~[teku-infrastructure-ssz-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.json.types.RequiredSerializableFieldDefinition.writeField(RequiredSerializableFieldDefinition.java:40) ~[teku-infrastructure-json-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.json.types.SerializableObjectTypeDefinition.serialize(SerializableObjectTypeDefinition.java:57) ~[teku-infrastructure-json-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.json.types.RequiredSerializableFieldDefinition.writeField(RequiredSerializableFieldDefinition.java:40) ~[teku-infrastructure-json-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.json.types.SerializableObjectTypeDefinition.serialize(SerializableObjectTypeDefinition.java:57) ~[teku-infrastructure-json-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.json.types.SerializableArrayTypeDefinition.serialize(SerializableArrayTypeDefinition.java:42) ~[teku-infrastructure-json-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.json.types.SerializableArrayTypeDefinition.serialize(SerializableArrayTypeDefinition.java:22) ~[teku-infrastructure-json-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.json.JsonUtil.lambda$serializeToBytes$1(JsonUtil.java:60) ~[teku-infrastructure-json-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.json.JsonUtil.serializeToBytes(JsonUtil.java:67) ~[teku-infrastructure-json-22.8.1.jar:22.8.1]
... 17 more
Suppressed: java.net.SocketException: Broken pipe
at sun.nio.ch.NioSocketImpl.implWrite(Unknown Source) ~[?:?]
at sun.nio.ch.NioSocketImpl.write(Unknown Source) ~[?:?]
at sun.nio.ch.NioSocketImpl$2.write(Unknown Source) ~[?:?]
at java.net.Socket$SocketOutputStream.write(Unknown Source) ~[?:?]
at okio.OutputStreamSink.write(JvmOkio.kt:53) ~[okio-jvm-2.8.0.jar:?]
at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103) ~[okio-jvm-2.8.0.jar:?]
at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255) ~[okio-jvm-2.8.0.jar:?]
at okio.RealBufferedSink.writeHexadecimalUnsignedLong(RealBufferedSink.kt:250) ~[okio-jvm-2.8.0.jar:?]
at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSink.write(Http1ExchangeCodec.kt:301) ~[okhttp-4.9.2.jar:?]
at okio.ForwardingSink.write(ForwardingSink.kt:29) ~[okio-jvm-2.8.0.jar:?]
at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218) ~[okhttp-4.9.2.jar:?]
at okio.RealBufferedSink.close(RealBufferedSink.kt:279) ~[okio-jvm-2.8.0.jar:?]
at okio.RealBufferedSink$outputStream$1.close(RealBufferedSink.kt:127) ~[okio-jvm-2.8.0.jar:?]
at com.fasterxml.jackson.core.json.UTF8JsonGenerator.close(UTF8JsonGenerator.java:1225) ~[jackson-core-2.13.3.jar:2.13.3]
at tech.pegasys.teku.infrastructure.json.JsonUtil.serializeToBytes(JsonUtil.java:66) ~[teku-infrastructure-json-22.8.1.jar:22.8.1]
at tech.pegasys.teku.infrastructure.json.JsonUtil.serializeToBytes(JsonUtil.java:60) ~[teku-infrastructure-json-22.8.1.jar:22.8.1]
at tech.pegasys.teku.ethereum.executionclient.rest.OkHttpRestClient$1.writeTo(OkHttpRestClient.java:122) ~[teku-ethereum-executionclient-22.8.1.jar:22.8.1]
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) ~[okhttp-4.9.2.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
2022-08-22 09:17:16.005 INFO  - Slot Event  *** Slot: 3720986, Block: 3b6fda033b351b82e52f2df13d007a6808b8806626c3b9500265589166f8cce3, Justified: 116279, Finalized: 116278, Peers: 61
2022-08-22 09:17:28.057 INFO  - Slot Event  *** Slot: 3720987, Block:                                                        ... empty, Justified: 116279, Finalized: 116278, Peers: 68
```

### Specific configuration:
On BN:
```
      network: goerli
      ee-endpoint: http://goerli-geth-2.goerli-geth:8551
      builder-endpoint: http://goerli-mev-boost:18550
      validators-builder-registration-default-enabled: true
      validators-proposer-default-fee-recipient: 1268AD189526AC0b386faF06eFfC46779c340eE6
```

On VC:
```
      beacon-node-api-endpoint: http://goerli-teku-beacon-0.goerli-teku-beacon.ethereum-common:5051
      network: auto
      validators-graffiti: Kiln
      validators-external-signer-url: http://goerli-web3signer.ethereum-web3signer:9000
      validators-proposer-blinded-blocks-enabled: true
      validators-external-signer-public-keys:
      - 833fef779953772b365fd5afc29a67e00470892528ff84a3ec4a6ee59a452d8ba9ff921aacc3a5ca9bc133f653e3d408 
      - 84b5bf716cc68b5270ed17a0cd6efb2c92f8fe7c4ca940837cf9d703e5616e00632067c2cdfac69443cb004ee94565e2 
      - 89855009613df8ea96e52112e003379f9f0875ef813dea4f726965003eb74f1b2e9e7937726e3bfe416489b76815e184
     < ... and so on ...>
```

And VC recipients config:
```
      default_config:
        fee_recipient: 1268AD189526AC0b386faF06eFfC46779c340eE6
        builder:
          enabled: true    
```

### Additional information:
With the same configuration, everything works well on Sepolia.

### Versions (Docker on Kubernetes)
- geth: v1.10.21
- Teku (BN & VC): 22.8.1-jdk17
- Web3Signer: 22.8.1-jdk17
- MEV-boost: v0.7.10

### PR DESCRIPTION
**Pull request by StefanBratanov**
## PR Description
All exceptions are currently handled in the OkHttp callback `onFailure` method. 

This PR makes sure no unchecked exception (different from expected IOException) is thrown in `RequestBody.writeTo` method. If such is thrown, then an exception will be thrown in a background thread, which will trigger `TekuDefaultExceptionHandler` to print a scary log message.

## Fixed Issue(s)
fixes #6109 

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/rest/OkHttpRestClient.java [hunk 1]
```diff
@@ -118,9 +118,11 @@ private <S> RequestBody createRequestBody(
     return new RequestBody() {
 
       @Override
-      public void writeTo(@NotNull BufferedSink bufferedSink) throws JsonProcessingException {
-        JsonUtil.serializeToBytes(
-            requestBodyObject, requestTypeDefinition, bufferedSink.outputStream());
+      public void writeTo(@NotNull final BufferedSink bufferedSink) throws IOException {
```
Comment (rolfyone) [inline ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/rest/OkHttpRestClient.java]: we don't usually use `@NotNull` annotations so that can probably disappear... not sure we need `bufferedSink;` at the start of the try with resources?

Comment (rolfyone) [reply ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/rest/OkHttpRestClient.java]: we could potentially have a test as well...

Comment (StefanBratanov) [reply ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/rest/OkHttpRestClient.java]: I think because the library is written in Kotlin, IntelliJ complains if i remove the annotation.
image

As for the try with resources, I removed it actually since the `JsonUtil` method closes all resources correctly.

Comment (rolfyone) [reply ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/rest/OkHttpRestClient.java]: Intellij does complain, but ignore it... I think it can be disabled in preferences, but I haven't gone looking. We definitely don't want `@NotNull` everywhere..

Comment (StefanBratanov) [reply ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/rest/OkHttpRestClient.java]: kk cool fixed

**Review by tbenr — APPROVED** [review]
LGTM.
Even if its only in test code, pinging @ajsutton for an approval on adding `awaitility` dependency.

**Comment by StefanBratanov** [comment]
> LGTM. Even if its only in test code, pinging @ajsutton for an approval on adding `awaitility` dependency.

Cool, I used it to get the `catchUncaughtExceptions` functionality, which fails the test if exceptions are caught in background threads. Otherwise, needed to create a separate thread and attach a test handler to it.

File: ethereum/executionclient/src/integration-test/java/tech/pegasys/teku/ethereum/executionclient/rest/OkHttpRestClientTest.java [hunk 2]
```diff
@@ -189,6 +195,21 @@ void postsAsync() throws InterruptedException {
...
+  @Test
+  void postsAsyncDoesNotThrowExceptionsInOtherThreadsWhenRequestCreationFails() {
+
+    final TestObject2 requestBodyObject = new TestObject2(TEST_BLOCK_HASH);
+    final SafeFuture<Response<TestObject>> responseFuture =
+        underTest.postAsync(
+            TEST_PATH, requestBodyObject, failingRequestTypeDefinition, responseTypeDefinition);
+
+    // this will fail if exceptions are thrown in other threads
+    await().catchUncaughtExceptions().atMost(Duration.ofSeconds(1)).until(responseFuture::isDone);
```
Comment (ajsutton) [inline ethereum/executionclient/src/integration-test/java/tech/pegasys/teku/ethereum/executionclient/rest/OkHttpRestClientTest.java]: Awaitility can be really finicky to get right so we generally use it via the `Waiter` class so that if we need to fix some source of intermittency we can fix it in one class and it's solved everywhere.  So I'd suggest moving this call into a new method in Waiter (and then I think you won't need the direct dependency on awaitility).

I'd also say that the maximum wait of 1 second is too tight - the system can be very busy when running tests so we usually want a long timeout (like 30 seconds) - it should still finish as soon as responseFuture is done which keeps it running quickly when things are working.

Comment (StefanBratanov) [reply ethereum/executionclient/src/integration-test/java/tech/pegasys/teku/ethereum/executionclient/rest/OkHttpRestClientTest.java]: Thanks, did a change to `Waiter`, good to know of that class for the future :)

File: infrastructure/async/src/testFixtures/java/tech/pegasys/teku/infrastructure/async/Waiter.java [hunk 3]
```diff
@@ -34,8 +35,19 @@ public class Waiter {
...
+
+  public static void waitFor(
+      final Condition assertion,
+      final int timeoutValue,
+      final TimeUnit timeUnit,
+      final boolean ignoreExceptions) {
+    ConditionFactory conditionFactory = Awaitility.waitAtMost(timeoutValue, timeUnit);
+    if (ignoreExceptions) {
+      conditionFactory = conditionFactory.ignoreExceptions();
+    }
```
Comment (ajsutton) [inline infrastructure/async/src/testFixtures/java/tech/pegasys/teku/infrastructure/async/Waiter.java:49]: Is this actually the same as the `catchUncaughtException` option you were using previously? Or more specifically, did you confirm the test still fails if your fix isn't applied?  If so, looks good, carry on and merge.  Otherwise totally fine to just add a completely separate method here in Waiter.

Comment (StefanBratanov) [reply infrastructure/async/src/testFixtures/java/tech/pegasys/teku/infrastructure/async/Waiter.java:49]: Yup confirmed the test fails without the fix. `catchUncaughtExceptions` is true by default for awaitility unless `ignoreExceptions` is used
