### PR TITLE
Remove usage of grpc for validator signing

### LINKED ISSUE #1134: ValidatorCoordinatorTest intermittently fails
### Description
Recently added `tech.pegasys.artemis.validator.coordinator.ValidatorCoordinatorTest` fails intermittently 

### Steps to Reproduce (Bug)
- On my Windows machine it fails 100% of time when running a single test from IDEA
- It intermittently fails on travis: e.g. passed on https://github.com/PegaSysEng/artemis/pull/1133/commits/6906f283f911665e23b5b0dcc499023b2bd9084b but failed on https://github.com/PegaSysEng/artemis/pull/1133/commits/b74aa73d9c4c113bec80dafac8a135916168bbce (PR #1133 )

### Versions (Add all that apply)
* Software version: latest master: https://github.com/PegaSysEng/artemis/commit/c61f4083cc8b2a6e835d4e8e33162a329fd7ffee

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
Avoids creating insecure open ports that expose the signing key
Avoids port conflicts when running multiple instances on the same host
Fixes intermittency in ValidatorCoordinatorTest which was caused by those port conflicts.

There is still an interface in place so remote validator signing services could be used later, but there's no point in using GRPC and network sockets while we're hard coded to use the signing service in the same process anyway.

## Fixed Issue(s)
Fixes #1134

### CODE REVIEW

File: validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorLoader.java [hunk 1]
```diff
@@ -47,14 +44,11 @@
...
-          Constants.VALIDATOR_CLIENT_PORT_BASE + i + keyProvider.getValidatorPortStartIndex();
-      new ValidatorClient(keypair, port);
-      ManagedChannel channel =
-          ManagedChannelBuilder.forAddress("localhost", port).usePlaintext().build();
+      final LocalMessageSignerService signerService = new LocalMessageSignerService(keypair);
       STDOUT.log(Level.DEBUG, "Validator " + i + ": " + keypair.getPublicKey().toString());
 
-      validators.put(keypair.getPublicKey(), new ValidatorInfo(numNaughtyValidators > 0, channel));
+      validators.put(
+          keypair.getPublicKey(), new ValidatorInfo(numNaughtyValidators > 0, signerService));
```
Comment (cemozerr) [inline validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorLoader.java:51]: Unrelated but, it might be a good idea to move the naughtyValidator functionality to the test environment.

**Review by cemozerr — APPROVED** [review]
Much needed refactoring. Neat.

File: validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorLoader.java (hunk 1 above)
Comment (ajsutton) [reply validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorLoader.java:51]: Yeah I think that should just be removed - having the production code be capable of bad behaviour is a bad idea.
