### PR TITLE
[issue #2747] fix slashing data export

### LINKED ISSUE #2747: NullPointerException when exporting slashing protection file
### Description

Receiving a NullPointerException error when running the following:

`bgravenorst@~/testteku/medalla$ ~/teku/build/install/teku/bin/teku slashing-protection export --to=validatorSlashing.yml
Reading slashing protection data from: /Users/bgravenorst/Library/teku/data/validators/slashingprotection
Exporting 963aa44979ce7f2131025e3a5115df624a65e11cc176ee7606add9cd389737df2e06347d274a5d51a212e913e0e7ae15
Writing slashing protection data to: validatorSlashing.yml
java.lang.NullPointerException
	at tech.pegasys.teku.infrastructure.io.SyncDataAccessor.syncedWrite(SyncDataAccessor.java:55)
	at tech.pegasys.teku.data.SlashingProtectionExporter.saveToFile(SlashingProtectionExporter.java:91)
	at tech.pegasys.teku.cli.slashingprotection.ExportCommand.run(ExportCommand.java:65)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at tech.pegasys.teku.cli.BeaconNodeCommand.parse(BeaconNodeCommand.java:223)
	at tech.pegasys.teku.Teku.main(Teku.java:32)`

The command works fine when I specify the `--to` option as `./validatorSlashing.yml`.

### Additional Information
teku/v0.12.6-dev-89c46a57/osx-x86_64/oracle-java-12

### PR DESCRIPTION
**Pull request by rolfyone**
After recent changes to use SyncDataAccessor, the slashing protection exporter requires a path to be passed, or an NPE occurs.

Also found that the path in use by the export command wasn't correct.

Fixes #2747

Signed-off-by: Paul Harris <paul.harris@consensys.net>

## Documentation

- [X] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: infrastructure/io/src/main/java/tech/pegasys/teku/infrastructure/io/SyncDataAccessor.java [hunk 1]
```diff
@@ -52,9 +52,11 @@
...
    */
   public void syncedWrite(final Path path, final Bytes data) throws IOException {
-    final File parentDirectory = path.getParent().toFile();
-    if (!parentDirectory.mkdirs() && !parentDirectory.isDirectory()) {
-      throw new IOException("Unable to create directory " + parentDirectory);
+    if (path.getParent() != null) {
+      final File parentDirectory = path.getParent().toFile();
+      if (!parentDirectory.mkdirs() && !parentDirectory.isDirectory()) {
+        throw new IOException("Unable to create directory " + parentDirectory);
+      }
```
Comment (ajsutton) [inline infrastructure/io/src/main/java/tech/pegasys/teku/infrastructure/io/SyncDataAccessor.java]: I'd suggest using `path.toAbsolutePath()` to get an absolute path before attempting to get the parent.  It still may have no parent if it's the root path but if it's a relative path the absolute version may have a parent when the relative doesn't.

**Review by ajsutton — APPROVED** [review]
LGTM.
