### PR TITLE
Fix error starting Teku with empty public keys

### LINKED ISSUE #5130: Error starting teku with empty public keys `
### Description
[Detailed description of the problem and the impact it has]
Starting Teku in remote signer mode with the following flags:
```
    exec /opt/teku/bin/teku \
        --network=prater \
        --data-base-path=/opt/teku/data \
        --eth1-endpoint=$HTTP_WEB3PROVIDER \
        --validators-external-signer-url=$HTTP_WEB3SIGNER \
        --validators-external-signer-public-keys=$PUBLIC_KEYS_COMMA_SEPARATED \
        --p2p-port=9000 \
        --rest-api-cors-origins="*" \
        --rest-api-interface=0.0.0.0 \
        --rest-api-port=$BEACON_API_PORT \
        --rest-api-host-allowlist="*" \
        --rest-api-enabled=true \
        --rest-api-docs-enabled=true \
        --log-destination=CONSOLE \
        --validators-graffiti=\"$GRAFFITI\" \
        $EXTRA_OPTS
``` 

The public keys loaded onto the flag `--validators-external-signer-public-keys` are obtained dynamically and parsed from the remote signer standard API https://eips.ethereum.org/EIPS/eip-3030#get-keys.

The public keys returned from the remote signer may be empty, this situation is not contemplated by teku, resulting in an error to start teku with empty public keys at `--validators-external-signer-public-keys`

I think this is not the ideal behavior, especially taking into account that the validator and beacon processes run in a monoservice process, so it does not allow to keep syncing the beacon chain if there are no validators loaded

### Steps to Reproduce (Bug)
[Please be as specific as possible]
start teku with an empty string in the flag `--validators-external-signer-public-keys`

**Expected behavior:** [What you expect to happen]
I expected teku to realize that an empty string means no validators and keep running instead of throwing errors. 

**Actual behavior:** [What actually happens]
Start teku with the flag `--validators-external-signer-public-keys` with an empty string result into an error
```
FATAL - Invalid configuration. Signer public key is invalid
```

**Frequency:** [How regularly does it occur?]
The error is thrown on startup so the process keeps in a restarting status.

### Versions (Add all that apply)
* Software version: [`teku --version` or look for log lines starting with `Teku version:`]  22.3.0
* Java version: [`java -version`]  official docker image
* OS Name & Version: [`cat /etc/*release`]   official docker image
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

### PR DESCRIPTION
**Pull request by courtneyeh**
fixes #5130 

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: teku/src/main/java/tech/pegasys/teku/cli/options/ValidatorKeysOptions.java [hunk 1]
```diff
@@ -120,6 +121,12 @@ public void configure(TekuConfiguration.Builder builder) {
                     convertToPath(validatorExternalSignerTruststorePasswordFile)));
   }
 
+  private List<String> parseValidatorExternalKeys() {
+    return validatorExternalSignerPublicKeys.stream()
+        .filter(val -> !Strings.isNullOrEmpty(val))
```
Comment (ajsutton) [inline teku/src/main/java/tech/pegasys/teku/cli/options/ValidatorKeysOptions.java]: I'd suggest using the commons lang3 `StringUtils.isNotBlank` here which will also filter out strings that are entirely whitespace. You also won't need to negate it so can use a method reference.

**Review by ajsutton — APPROVED** [review]
LGTM. Would just switch it over to also ignore strings that are entirely white space.
