### PR TITLE
Report all block & attestation production attempts to performance tracker

### LINKED ISSUE #2918: Add info on what was supposed to happen to performance reports
My node failed to produce a block, but that was not shown in a performance summary.

The block production failed:
```
02:24:56.143 ERROR - Validator   *** Failed to produce block  Slot: 464824
tech.pegasys.teku.validator.coordinator.MissingDepositsException: Unable to create block because ETH1 deposits are not available. Missing deposits 80047 to 80241
```

I saw no performance summary related to this (since we supress reports when nothing happens), but it would have been good to see something like:
```
HH:MM:SS.nnn INFO  - Block performance: expected: 1, produced 0, included 0 (0%)
```

The same should apply to attestation performance  summaries.

### PR DESCRIPTION
**Pull request by cemozerr**
## PR Description
Report all block & attestation production attempts to performance tracker.

## Fixed Issue(s)

Fixes #2918

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: validator/client/src/main/java/tech/pegasys/teku/validator/client/duties/AttestationProductionDuty.java [hunk 1]
```diff
@@ -134,6 +134,7 @@ public String getProducedType() {
             signedAttestation ->
                 validatorApiChannel.sendSignedAttestation(
                     signedAttestation, Optional.of(validator.getValidatorIndex())))
+        // TODO: here we report succes for the attestation yet we don't know if it was successful.
```
Comment (ajsutton) [inline validator/client/src/main/java/tech/pegasys/teku/validator/client/duties/AttestationProductionDuty.java]: This is in the Validator Client, and it has just produced and sent to the beacon node the attestation. It can't know if the beacon node sent it on.  The APIs around this are changing at the moment anyway which may change this, but for now this TODO seems out of scope of this change and probably should be removed.

**Review by ajsutton — APPROVED** [review]
LGTM.

File: validator/client/src/main/java/tech/pegasys/teku/validator/client/duties/AttestationProductionDuty.java (hunk 1 above)
Comment (cemozerr) [reply validator/client/src/main/java/tech/pegasys/teku/validator/client/duties/AttestationProductionDuty.java]: Done.
