### PR TITLE
Fix issue where remote config is missing data

### LINKED ISSUE #7492: interop issue with constants that have moved to the network configuration
ref. #7489

When we are loading from a spec url, if the moved constants aren't available, we should still continue, and just reference the old constant values.

This is likely to need to be done until Deneb, because we can't guarantee currently the version of a client that someone is connecting to has these same settings.

### PR DESCRIPTION
**Pull request by courtneyeh**
fixes #7492 

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/spec/src/testFixtures/java/tech/pegasys/teku/spec/TestSpecFactory.java [hunk 1]
```diff
@@ -343,19 +343,30 @@ private static SpecConfigDeneb getDenebSpecConfig(final Eth2Network network) {
...
+        network, altairForkEpoch, bellatrixForkEpoch, capellaForkEpoch, denebForkEpoch, true);
+  }
+
+  public static SpecConfigDeneb getDenebSpecConfig(
+      final Eth2Network network,
+      final UInt64 altairForkEpoch,
+      final UInt64 bellatrixForkEpoch,
+      final UInt64 capellaForkEpoch,
+      final UInt64 denebForkEpoch,
+      final boolean kzgNoop) {
```
Comment (rolfyone) [inline ethereum/spec/src/testFixtures/java/tech/pegasys/teku/spec/TestSpecFactory.java]: seems very curious we've had to make this change? doesnt seem related to anything we're doing...

File: teku/src/test/java/tech/pegasys/teku/cli/subcommand/RemoteSpecLoaderTest.java [hunk 2]
```diff
@@ -55,6 +64,29 @@ void shouldFailWhenRequiredItemsAreMissing() {
...
+        Resources.toString(
+            Resources.getResource(RemoteSpecLoaderTest.class, "spec_config.json"),
+            StandardCharsets.UTF_8);
+    final ObjectMapper objectMapper = new ObjectMapper();
+    TypeReference<Map<String, String>> typeReference = new TypeReference<>() {};
+    Map<String, String> data = objectMapper.readValue(jsonConfig, typeReference);
+
+    final SpecConfig specConfig = SpecConfigLoader.loadRemoteConfig(data);
+
+    final SpecConfig expectedConfig =
```
Comment (rolfyone) [inline teku/src/test/java/tech/pegasys/teku/cli/subcommand/RemoteSpecLoaderTest.java]: basically instead of doing this, you'd just create a mainnet spec, and get the genesis spec config from that...

File: teku/src/test/java/tech/pegasys/teku/cli/subcommand/RemoteSpecLoaderTest.java [hunk 3]
```diff
@@ -55,6 +64,29 @@ void shouldFailWhenRequiredItemsAreMissing() {
...
+        TestSpecFactory.getDenebSpecConfig(
+            Eth2Network.MAINNET,
+            UInt64.valueOf(74240),
+            UInt64.valueOf(144896),
+            UInt64.valueOf(194048),
+            UInt64.valueOf("18446744073709551615"),
+            false);
+    assertThat(specConfig).isEqualTo(expectedConfig);
```
Comment (rolfyone) [inline teku/src/test/java/tech/pegasys/teku/cli/subcommand/RemoteSpecLoaderTest.java]: rather than comparing the entire spec, all we need to know is that the load didnt cause an exception (it couldnt have to get this far) and that the fields that were missing are now set with the correct values. so we can check max_chunk_size etc explicitly from our mainnet spec we internally generate against the one we load remotely.

File: teku/src/test/resources/tech/pegasys/teku/cli/subcommand/spec_config.json [hunk 4]
```diff
@@ -0,0 +1,97 @@
+{
+  "CONFIG_NAME": "mainnet",
+  "PRESET_BASE": "mainnet",
```
Comment (rolfyone) [inline teku/src/test/resources/tech/pegasys/teku/cli/subcommand/spec_config.json]: we might name this better... something like `config_missing_network_fields.json` so that we know what it is

**Review by rolfyone — APPROVED** [review]
LGTM
