### PR TITLE
Fix `SszOptionalSchema` bounds

### LINKED ISSUE #8412: Fix `SszLengthBounds` for `SszOptinal`
I think the following is wrong. We should consider the minimum bound to be as the Optional is empty.
```Java
  private SszLengthBounds calcSszLengthBounds() {
    return childSchema.getSszLengthBounds().addBytes(PREFIX_SIZE_BYTES).ceilToBytes();
  }
```

### PR DESCRIPTION
**Pull request by tbenr**
fixes #8412 

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: infrastructure/ssz/src/test/java/tech/pegasys/teku/infrastructure/ssz/schema/SszSchemaTestBase.java [hunk 1]
```diff
@@ -46,24 +47,22 @@ void getDefaultTree_shouldBeEqualToDefaultStructure(final SszSchema<SszData> sch
...
+    if (schema instanceof AbstractSszCollectionSchema<?, ?> collectionSchema) {
+      assumeThat(collectionSchema.getHints().getHint(SszSuperNodeHint.class))
           .describedAs("uses SszSuperNode")
           .isEmpty();
     }
 
     SszData data = randomSsz.randomData(schema);
+
+    if (data instanceof SszOptional<?> optionalData) {
+      assumeThat(optionalData.getValue()).describedAs("optional has a value").isPresent();
```
Comment (zilm13) [inline infrastructure/ssz/src/test/java/tech/pegasys/teku/infrastructure/ssz/schema/SszSchemaTestBase.java]: I would left a comment that empty will not pass it for clarification (why it happens)

**Review by zilm13 — APPROVED** [review]
Great!
Thank you for addressing this
