### PR TITLE
[Issue 2037] Limit hot blocks in memory (with race condition fix)

### LINKED ISSUE #2037: Reduce memory requirements related to non-finalized blocks
### Description
Teku currently keeps all non-finalized blocks in memory.  When finalization is delayed, this significantly increases the memory requirements, often leading to out-of-memory errors.

Teku should limit the number of blocks it keeps in memory and handle reloading non-finalized blocks from disk when required.

This work relates to Issue #1976

### PR DESCRIPTION
**Pull request by mbaxter**
## PR Description
Limit hot blocks kept in memory.  

This PR reapplies reverted changes from  #2211 with an additional fix for a race condition. The following example scenario illustrates the race condition: 
* Transaction A adds a block.
* Transaction A is committed and we [pre-calculate changes](https://github.com/PegaSysEng/teku/blob/5380e888871def02e4541c0f2ca8cba1f37d2c8d/storage/src/main/java/tech/pegasys/teku/storage/store/Store.java#L516) to be applied.
  * These changes included a new `blockTree` containing the newly added block.
* Then, transaction B starts (updating something irrelevant to the chain data like `time`).
* Transaction B commits, and pre-calculates its changes. 
  * These pre-calculations are based on the existing data in `Store` which does not contain the pending changes from Transaction A.  So, the updated `blockTree` calculated here does not contain the new block from Transaction A.
* Transaction A [finishes committing](https://github.com/PegaSysEng/teku/blob/5380e888871def02e4541c0f2ca8cba1f37d2c8d/storage/src/main/java/tech/pegasys/teku/storage/store/Store.java#L529), applying the new `blockTree` with its new block.
* Transaction B finishes committing, overwriting the `blockTree` with its version which is missing the new block from Transaction A.  Now, the new block is no longer tracked.

The fix is to only calculate and apply `blockTree` updates when the tree is actually modified (new blocks are added or a new finalized root is set).  Because all block updates are `synchronized`, we won't encounter this race condition.  

## Fixed Issue(s)
Fixes #2037

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: ethereum/core/src/main/java/tech/pegasys/teku/core/stategenerator/AsyncChainStateGenerator.java [hunk 1]
```diff
@@ -0,0 +1,148 @@
...
+                      .map(blocks::get)
+                      .filter(Objects::nonNull)
+                      .collect(Collectors.toList());
+              if (chainBlocks.size() < blockRoots.size()) {
+                final String missingBlocks =
+                    blockRoots.stream()
+                        .filter(root -> !blocks.containsKey(root))
+                        .map(Object::toString)
+                        .collect(Collectors.joining(", "));
+                throw new IllegalStateException("Failed to retrieve blocks: " + missingBlocks);
```
Comment (ajsutton) [inline ethereum/core/src/main/java/tech/pegasys/teku/core/stategenerator/AsyncChainStateGenerator.java]: Would be good to include as much information in this exception message as possible - it proved quite hard to understand when it was popping up a lot last time.  Ideally it would be good to start and end slots we were trying to load blocks for and the block root of the state we were trying to regenerate.

File: ethereum/core/src/main/java/tech/pegasys/teku/core/stategenerator/ChainStateGenerator.java [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+  private final BlockProcessor blockProcessor = new BlockProcessor();
+  private final List<SignedBeaconBlock> chain;
+  private final BeaconState baseState;
+
+  private ChainStateGenerator(
+      final List<SignedBeaconBlock> chain,
+      final BeaconState baseState,
+      final boolean skipValidation) {
+    if (!skipValidation) {
+      chain.sort(Comparator.comparing(SignedBeaconBlock::getSlot));
```
Comment (ajsutton) [inline ethereum/core/src/main/java/tech/pegasys/teku/core/stategenerator/ChainStateGenerator.java]: We probably shouldn't modify the list that's passed in by sorting it.  That said, we never seem to actually run this code so maybe just remove it?

File: storage/src/main/java/tech/pegasys/teku/storage/store/Store.java [hunk 3]
```diff
@@ -299,14 +334,17 @@ public SignedBeaconBlock getSignedBlock(Bytes32 blockRoot) {
     if (block == null) {
       return Optional.empty();
     }
-    return getOrGenerateBlockState(blockRoot).map((state) -> new SignedBlockAndState(block, state));
+    // TODO - handle future properly
```
Comment (ajsutton) [inline storage/src/main/java/tech/pegasys/teku/storage/store/Store.java]: nit: It may be worth logging an issue to tidy up the future handling then make all these `TODO` comments reference that issue number so they're easier to find (e.g. `// TODO(#xxxx) - handle future properly)

File: storage/src/test/java/tech/pegasys/teku/storage/store/StoreTest.java [hunk 4]
```diff
@@ -44,58 +48,50 @@
...
+              .withFailMessage(
+                  "Expected state for block %s to be available", blockAndState.getSlot())
+              .isNotNull();
+          assertThat(result.hash_tree_root())
+              .isEqualTo(blockAndState.getBlock().getMessage().getState_root());
+        });
   }
 
   @Test
   public void shouldApplyChangesWhenTransactionCommits() throws StateTransitionException {
```
Comment (ajsutton) [inline storage/src/test/java/tech/pegasys/teku/storage/store/StoreTest.java:71]: Should we have a version of this that commits an update to time (or anything else that doesn't affect the block tree) before the transaction applies?  Basically covering the race condition case we had previously.  Sorry if I missed it somewhere.

**Review by ajsutton — APPROVED** [review]
LGTM.  I've fully sync'd Altona and tracked head for a while and sync'd 76000 blocks of Onyx without any issues.

**Comment by ajsutton** [comment]
I've also back ported this to v0.11 and deployed it to our Witti validators box so we can see how it behaves with an insane period of non-finalisation.

File: ethereum/core/src/main/java/tech/pegasys/teku/core/stategenerator/AsyncChainStateGenerator.java (hunk 1 above)
Comment (mbaxter) [reply ethereum/core/src/main/java/tech/pegasys/teku/core/stategenerator/AsyncChainStateGenerator.java]: Added more info to these exceptions and added some logging

File: storage/src/test/java/tech/pegasys/teku/storage/store/StoreTest.java (hunk 4 above)
Comment (mbaxter) [reply storage/src/test/java/tech/pegasys/teku/storage/store/StoreTest.java:71]: I thought this test would be messy and involve spinning up various threads, but found a simple way to test using `StubAsyncRunner` 🎉
