### PR TITLE
[Issue-3806] Fix uint to bytes conversion bug

### LINKED ISSUE #3806: HF1 RefTests - Debug and enable fork upgrade ref tests
### Description
Debug and enable `ForkUpgradeTestExecutor` tests.  Currently, a few test cases (`random_misc_balances` and `random_low_balances`) are failing. 

See: 
* https://github.com/ConsenSys/teku/pull/3805
* [Ignored Tests](https://github.com/ConsenSys/teku/blob/e1135f06d0314688ea8de739547bef6eec66974e/eth-reference-tests/src/referenceTest/java/tech/pegasys/teku/reference/altair/fork/ForkUpgradeTestExecutor.java#L37-L38)

### PR DESCRIPTION
**Pull request by mbaxter**
## PR Description
Fix uint to bytes conversion bug and enable fork upgrade ref tests.

## Fixed Issue(s)
Fixes #3806

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/common/helpers/MathHelpers.java [hunk 1]
```diff
@@ -48,6 +48,10 @@ public static Bytes uintToBytes(long value, int numBytes) {
     }
   }
 
+  public static Bytes uint64ToBytes(long value) {
```
Comment (ajsutton) [inline ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/common/helpers/MathHelpers.java:51]: nit: Would it make more sense for this to take `UInt64` and call `.longValue()` itself?

**Review by ajsutton — APPROVED** [review]
LGTM.

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/common/helpers/MathHelpers.java (hunk 1 above)
Comment (mbaxter) [reply ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/common/helpers/MathHelpers.java:51]: yeah - we could probably just have 2 versions
