### PR TITLE
Increased attestation queue limits

### LINKED ISSUE #9214: [HOLESKY PECTRA] rejected execution stack trace!
{"@timestamp":"2025-03-08T06:30:37,605","level":"ERROR","thread":"beaconchain-async-20","class":"AttestationManager","message":"Failed to process received attestation.","throwable":" java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: Rejected execution on task queue - forkchoice\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)\n\tat java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)\n\tat java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)\n\tat java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.thenApply(SafeFuture.java:461)\n\tat tech.pegasys.teku.statetransition.forkchoice.ForkChoice.lambda$onAttestation$6(ForkChoice.java:255)\n\tat java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)\n\tat java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.thenCompose(SafeFuture.java:542)\n\tat tech.pegasys.teku.statetransition.forkchoice.ForkChoice.onAttestation(ForkChoice.java:236)\n\tat tech.pegasys.teku.statetransition.attestation.AttestationManager.onAttestation(AttestationManager.java:229)\n\tat tech.pegasys.teku.statetransition.attestation.AttestationManager.lambda$processInternallyValidatedAttestation$6(AttestationManager.java:165)\n\tat java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)\n\tat java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147)\n\tat java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)\n\tat java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)\n\tat java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2357)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:620)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:31)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$34(SafeFuture.java:424)\n\tat java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)\n\tat java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)\n\tat java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)\n\tat tech.pegasys.teku.statetransition.validation.signatures.AggregatingSignatureVerificationService$SignatureTask.lambda$completeAsync$0(AggregatingSignatureVerificationService.java:259)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:80)\n\tat tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:47)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:72)\n\tat tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: java.util.concurrent.RejectedExecutionException: Rejected execution on task queue - forkchoice\n\tat tech.pegasys.teku.infrastructure.async.MetricTrackingExecutorFactory.onRejectedExecution(MetricTrackingExecutorFactory.java:116)\n\tat tech.pegasys.teku.infrastructure.async.MetricTrackingExecutorFactory.lambda$newCachedThreadPool$0(MetricTrackingExecutorFactory.java:94)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376)\n\tat tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.runAsync(ScheduledExecutorAsyncRunner.java:73)\n\tat tech.pegasys.teku.infrastructure.async.AsyncRunner.runAsync(AsyncRunner.java:47)\n\tat tech.pegasys.teku.infrastructure.async.eventthread.AsyncRunnerEventThread.doExecute(AsyncRunnerEventThread.java:113)\n\tat tech.pegasys.teku.infrastructure.async.eventthread.AsyncRunnerEventThread.execute(AsyncRunnerEventThread.java:83)\n\^C

### PR DESCRIPTION
**Pull request by rolfyone**
Also quashed RejectedExecution on attestation processing, as it was causing excessive disk load because of the volume, and it really does increase load a lot when it occurs.

The queue size should reduce the chance of hitting that, but the log change should assist if we do hit it. The point of rejectedExecution was not to actually increase load on the system.

fixes #9214

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/attestation/AggregatingAttestationPool.java [hunk 1]
```diff
@@ -68,8 +68,8 @@ public class AggregatingAttestationPool implements SlotEventsChannel {
   /**
    * Default maximum number of attestations to store in the pool.
    *
-   * <p>With 1.2 million active validators, we'd expect around 37_500 attestations per slot; so 3
-   * slots worth of attestations is almost 120_000.
+   * <p>With 2 million active validators, we'd expect around 62_500 attestations per slot; so 3
+   * slots worth of attestations is almost 187_500.
    *
    * <p>128 attestations perfectly packed at a 1.2 million validator set would be 1_200_000 / 32 /
```
Comment (gfukushima) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/attestation/AggregatingAttestationPool.java]: do care to update this comment as well?

**Review by gfukushima — APPROVED** [review]
lgtm

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/attestation/AggregatingAttestationPool.java (hunk 1 above)
Comment (rolfyone) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/attestation/AggregatingAttestationPool.java]: i dont get it? i updated it?

Comment (rolfyone) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/attestation/AggregatingAttestationPool.java]: oooh the second-  ok on it
