### PR TITLE
[Issue 4034] Fix threading issue in LevelDbTransaction

### LINKED ISSUE #4034: Crash in LevelDB during shutdown
While working in my dev environment I got the following error on terminating Teku with "^C".  The process then hung for a while. Not critical, but would be nice if there were a way for this not to happen.

commit 79e49c48e0a6a78eac5b7760860d680a046e78af (latest master).

```
21:00:11.496 INFO  - Sync Event  *** Current slot: 1262399, Head slot: 48, Connected peers: 14
^CTeku is shutting down
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f82a465e9c6, pid=203385, tid=203441
#
# JRE version: OpenJDK Runtime Environment (11.0.11+9) (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
# Java VM: OpenJDK 64-Bit Server VM (11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libleveldbjni-64-1-3194925705089044006.8+0x409c6]  leveldb::crc32c::Extend(unsigned int, char const*, unsigned long)+0xb6
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/ben/Everything/ConsenSys/Teku/core.203385)
#
# An error report file with more information is saved as:
# /home/ben/Everything/ConsenSys/Teku/hs_err_pid203385.log
[thread 203529 also had an error]
#
# If you would like to submit a bug report, please visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

### PR DESCRIPTION
**Pull request by mbaxter**
## PR Description
Fix threading issue in `LevelDbTransaction`: we had nothing in place to prevent `tx.close()` from running concurrently with other tx update methods.  Individual transactions are not meant to be accessed across multiple threads, but when the database is closed, `tx.close()` can be invoked from a different thread.

Also:
* Move `RocksDbTransaction` out to a separate class
* Rename `AbstractRocksDbDatabaseTest ` to `AbstractKvStoreDatabaseTest`
* Fix `RocksDbTransaction.rollback()`
* Add leveldb instances to `StorageSystemArgumentsProvider`

## Fixed Issue(s)
Fixes #4034 

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: storage/src/main/java/tech/pegasys/teku/storage/server/leveldb/LevelDbInstance.java [hunk 1]
```diff
@@ -279,8 +279,9 @@ private synchronized void closeIterator(final DBIterator iterator) {
   }
 
   synchronized void onTransactionClosed(final LevelDbTransaction transaction) {
-    closedTransactionsCounter.inc();
-    openTransactions.remove(transaction);
+    if (openTransactions.remove(transaction)) {
+      closedTransactionsCounter.inc();
+    }
```
Comment (ajsutton) [inline storage/src/main/java/tech/pegasys/teku/storage/server/leveldb/LevelDbInstance.java:284]: ooo, good spot.

**Review by ajsutton — APPROVED** [review]
LGTM.
