### PR TITLE
Fix normal sync error, when EL is offline

### LINKED ISSUE #4936: Node throws an exception during normal sync while EL is offline
### Description

Node throws an exception on processing ExecutionPayload while EL is offline. Need to add and handle additional status of `ExecutionPayloadStatus` or resolve issue somehow else.

```
2022-02-04 11:11:09.978+03:00 | forkchoice-async-0 | ERROR | teku-status-log | PLEASE FIX OR REPORT | Unexpected exceptio
n thrown for forkchoice-async-0
java.util.NoSuchElementException: No value present
at java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.lambda$onExecutionPayloadResult$5(ForkChoice.java:336) ~[teku-
ethereum-statetransition-develop.jar:22.1.0+76-g4571e9a]
at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.lambda$onForkChoiceThread$18(ForkChoice.java:509) ~[teku-ether
eum-statetransition-develop.jar:22.1.0+76-g4571e9a]
at tech.pegasys.teku.infrastructure.async.eventthread.AsyncRunnerEventThread.recordEventThreadIdAndExecute(AsyncRunnerEve
ntThread.java:122) ~[teku-infrastructure-async-develop.jar:22.1.0+76-g4571e9a]
at tech.pegasys.teku.infrastructure.async.eventthread.AsyncRunnerEventThread.lambda$doExecute$1(AsyncRunnerEventThread.ja
va:105) ~[teku-infrastructure-async-develop.jar:22.1.0+76-g4571e9a]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[teku-infrastructure-async-develop.jar:22.1.
0+76-g4571e9a]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:38) ~[teku-infrastructure-async-
develop.jar:22.1.0+76-g4571e9a]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[teku-infrastructure-async-develop.jar:22.1.
0+76-g4571e9a]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutor
AsyncRunner.java:119) ~[teku-infrastructure-async-develop.jar:22.1.0+76-g4571e9a]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Steps to Reproduce (Bug)
Turn off EL during normal sync

**Expected behavior:** 
No unhandled exceptions. No peer penalization

### PR DESCRIPTION
**Pull request by zilm13**
## PR Description
There was a bug left, which throws an `Exception` while EL is down during normal sync. It was thrown before peer penalization so peer was not downgraded, though it's still error in code and should be fixed by this PR

## Fixed Issue(s)

Fixes #4936  
## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: protoarray/src/main/java/tech/pegasys/teku/protoarray/ForkChoiceStrategy.java [hunk 1]
```diff
@@ -452,10 +453,15 @@ void processBlock(
...
   }
 
-  public void onExecutionPayloadResult(
-      final Bytes32 blockRoot,
-      final ExecutionPayloadStatus status,
-      final Optional<Bytes32> latestValidHash) {
+  public void onExecutionPayloadResult(final Bytes32 blockRoot, final ExecutePayloadResult result) {
+    if (result.hasFailedExecution()) {
+      LOG.warn(
+          "Payload for block root {} not processed, failed execution, EL is offline",
```
Comment (tbenr) [inline protoarray/src/main/java/tech/pegasys/teku/protoarray/ForkChoiceStrategy.java]: What about: "Unable to Execute Payload for block root {}, Execution Engine is offline" ?

**Review by tbenr — APPROVED** [review]
LGTM. just a suggestion on the warning message

File: protoarray/src/main/java/tech/pegasys/teku/protoarray/ForkChoiceStrategy.java (hunk 1 above)
Comment (zilm13) [reply protoarray/src/main/java/tech/pegasys/teku/protoarray/ForkChoiceStrategy.java]: I like it!
