### PR TITLE
Log error when EL says terminal block that it provided is INVALID

### LINKED ISSUE #6042: Invalidated terminal block hash (by EL)
### Description
I stuck how should we handle this, so explaining the issue.
We reach the terminal block and are sending FCU to the EL:
```
2022-08-08 13:56:28.120 INFO  - Loaded initial state at epoch 0 (state root = 0x71ef5939afd6e13ef0bf496e51144e4a95381ecdd7eba875aee705adfd43a31a, block root = 0x9a13008edfae88d4c53c4a48d8ca1bc3a207e0facb37b175dc4096df4684f40c, block slot = 0).
2022-08-08 13:56:28.132 INFO  - [36mGenesis Event *** 
Genesis state root: 0x71ef5939afd6e13ef0bf496e51144e4a95381ecdd7eba875aee705adfd43a31a 
Genesis block root: 0x9a13008edfae88d4c53c4a48d8ca1bc3a207e0facb37b175dc4096df4684f40c 
Genesis time: 2022-08-08 13:56:34 GMT[0m
2022-08-08 13:56:48.086 TRACE  - engineForkChoiceUpdated(forkChoiceState=ForkChoiceState{headBlockRoot=0x9a13008edfae88d4c53c4a48d8ca1bc3a207e0facb37b175dc4096df4684f40c, headBlockSlot=0, headExecutionBlockHash=0x463bb01dc74aaf70ea402298240a43e40f323f535b00e9218da2df8a3a77552c, safeExecutionBlockHash=0x0000000000000000000000000000000000000000000000000000000000000000, finalizedExecutionBlockHash=0x0000000000000000000000000000000000000000000000000000000000000000, isHeadOptimistic=false}, payloadAttributes=Optional.empty) -> ForkChoiceUpdatedResult{payloadStatus=PayloadStatus{status=Optional[INVALID], latestValidHash=Optional[0x0fea94893de4066de64c5f3ad817b3370607cb1d95876f2e71b44ea7ad741aa1], validationError=Optional.empty, failureCause=Optional.empty}, payloadId=Optional.empty}
```
It looks like a correct answer by EL as it invalidates exact terminal block hash. But what we are doing next looks incorrect: we are trying to invalidate corresponding BeaconBlock which is not incorrect and getting an Exception:
```
2022-08-08 13:56:48.088 INFO  - node ProtoNode{blockSlot=0, stateRoot=0x71ef5939afd6e13ef0bf496e51144e4a95381ecdd7eba875aee705adfd43a31a, blockRoot=0x9a13008edfae88d4c53c4a48d8ca1bc3a207e0facb37b175dc4096df4684f40c, parentRoot=0x0000000000000000000000000000000000000000000000000000000000000000, justifiedCheckpoint=Checkpoint{epoch=0, root=0x0000000000000000000000000000000000000000000000000000000000000000}, finalizedCheckpoint=Checkpoint{epoch=0, root=0x0000000000000000000000000000000000000000000000000000000000000000}, unrealizedJustifiedCheckpoint=Checkpoint{epoch=0, root=0x0000000000000000000000000000000000000000000000000000000000000000}, unrealizedFinalizedCheckpoint=Checkpoint{epoch=0, root=0x0000000000000000000000000000000000000000000000000000000000000000}, executionBlockHash=0x0000000000000000000000000000000000000000000000000000000000000000, weight=0, parentIndex=Optional.empty, bestChildIndex=Optional.empty, bestDescendantIndex=Optional.empty, validationStatus=VALID} marking as invalid, 0x9a13008edfae88d4c53c4a48d8ca1bc3a207e0facb37b175dc4096df4684f40c, Optional[0x0fea94893de4066de64c5f3ad817b3370607cb1d95876f2e71b44ea7ad741aa1], true
2022-08-08 13:56:48.089 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for forkchoice-async-0
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Cannot change node validity from VALID to INVALID
```

From my view invalid terminal block hash should be handled here in the same way like in #5887 not invalidating transition BeaconBlock by default because it doesn't have any reference to the terminal block (and is not invalid btw). Do I understand it correctly?

### PR DESCRIPTION
**Pull request by zilm13**
## PR Description
Let's try this approach to get proper error when EL returns INVALID on previously provided terminal block hash.
I have no idea how to test it, exception is lost in `finish` part

## Fixed Issue(s)

Fixes #6042 
## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/forkchoice/ForkChoice.java [hunk 1]
```diff
@@ -143,12 +143,23 @@ public void onForkChoiceUpdatedResult(
...
+                    forkChoiceUpdatedResult -> {
+                      if (forkChoiceUpdatedResultNotification.isTerminalBlockCall()
+                          && forkChoiceUpdatedResult.getPayloadStatus().hasInvalidStatus()) {
+                        throw new IllegalStateException(
+                            String.format(
+                                "Execution engine considers INVALID recently provided terminal block %s. "
+                                    + "Probably an execution engine misconfiguration.",
+                                forkChoiceUpdatedResultNotification
+                                    .getForkChoiceState()
+                                    .getHeadExecutionBlockHash()));
```
Comment (ajsutton) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/forkchoice/ForkChoice.java]: I'd just log a message about this here and return rather than throwing an exception. And I'd omit the "Probably and execution engine misconfiguration." part - we can just stick to reporting what happened as we don't really know what's going on with the EL.

**Review by ajsutton — COMMENTED** [review]
You can test the logging using the `LogCaptor` class.  See `FallbackAwareEth1ProviderSelectorTest.shouldNotIncludeTimeoutExceptionStacktraceInLogs` for an example.

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/forkchoice/ForkChoice.java (hunk 1 above)
Comment (zilm13) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/forkchoice/ForkChoice.java]: LogCaptor is good, missed it, thank you

**Comment by zilm13** [comment]
@ajsutton updated

**Review by ajsutton — APPROVED** [review]
LGTM.
