### PR TITLE
limit weight to max_uint64 to avoid overflow

### LINKED ISSUE #9189: [HOLESKY PECTRA] `ArithmeticException`! FCU
```
{"@timestamp":"2025-03-02T20:53:40,855","level":"ERROR","thread":"forkchoice-async-0","class":"ForkChoiceRatchet","message":"Fork choice process head failed","throwable":" java.util.concurrent.CompletionException: java.lang.ArithmeticException: uint64 overflow\n\tat java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)\n\tat java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)\n\tat java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1097)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)\n\tat java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145)\n\tat java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)\n\tat java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)\n\tat java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2357)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:620)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:31)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:318)\n\tat tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: java.lang.ArithmeticException: uint64 overflow\n\tat tech.pegasys.teku.infrastructure.unsigned.UInt64.plus(UInt64.java:142)\n\tat tech.pegasys.teku.infrastructure.unsigned.UInt64.plus(UInt64.java:108)\n\tat tech.pegasys.teku.storage.protoarray.ProtoNode.adjustWeight(ProtoNode.java:108)\n\tat tech.pegasys.teku.storage.protoarray.ProtoArray.applyDelta(ProtoArray.java:728)\n\tat tech.pegasys.teku.storage.protoarray.ProtoArray.lambda$applyDeltas$8(ProtoArray.java:716)\n\tat tech.pegasys.teku.storage.protoarray.ProtoArray.applyToNodes(ProtoArray.java:744)\n\tat tech.pegasys.teku.storage.protoarray.ProtoArray.applyDeltas(ProtoArray.java:716)\n\tat tech.pegasys.teku.storage.protoarray.ProtoArray.applyScoreChanges(ProtoArray.java:429)\n\tat tech.pegasys.teku.storage.protoarray.ForkChoiceStrategy.applyPendingVotes(ForkChoiceStrategy.java:126)\n\tat tech.pegasys.teku.storage.store.StoreVoteUpdater.applyForkChoiceScoreChanges(StoreVoteUpdater.java:81)\n\tat tech.pegasys.teku.statetransition.forkchoice.ForkChoice.updateHeadTransaction(ForkChoice.java:380)\n\tat tech.pegasys.teku.statetransition.forkchoice.ForkChoice.lambda$processHead$11(ForkChoice.java:353)\n\tat tech.pegasys.teku.infrastructure.async.eventthread.AsyncRunnerEventThread.recordEventThreadIdAndExecute(AsyncRunnerEventThread.java:130)\n\tat tech.pegasys.teku.infrastructure.async.eventthread.AsyncRunnerEventThread.lambda$doExecute$1(AsyncRunnerEventThread.java:113)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:80)\n\tat tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:47)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:72)\n\t... 4 more\n"}
```

holesky-03

### PR DESCRIPTION
**Pull request by rolfyone**
fixes #9189

could be worked to larger value if we need? but this seems like a hard thing to get to currently...

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: storage/src/main/java/tech/pegasys/teku/storage/protoarray/ProtoNode.java [hunk 1]
```diff
@@ -105,7 +109,12 @@ public void adjustWeight(final long delta) {
       }
       weight = weight.minus(deltaAbsoluteValue);
     } else {
-      weight = weight.plus(delta);
+      if (UInt64.MAX_VALUE.minusMinZero(delta).isGreaterThan(weight)) {
+        weight = weight.plus(delta);
+      } else {
+        LOG.trace("Unable to add delta {} to weight {}", delta, weight);
+        weight = UInt64.MAX_VALUE;
+      }
```
Comment (lucassaldanha) [inline storage/src/main/java/tech/pegasys/teku/storage/protoarray/ProtoNode.java]: One option would be to add a `safePlus(..)` method on `Uint64`, similar to what we have with `safeMinus`. Something like this:

```
public UInt64 safePlus(final UInt64 other) {
    if (value != 0 && Long.compareUnsigned(other.value, MAX_VALUE.longValue() - value) > 0) {
      return UInt64.MAX_VALUE;
    }
    return plus(value, other.value);
  }
```

**Review by lucassaldanha — APPROVED** [review]
LGMT. Added a suggestion for a reusable option on `Uint64`
