### PR TITLE
Load the deposit contract from constants if it hasn't been set

### LINKED ISSUE #3723: Eth1 Deposit Contract should default to the provided spec constant
### Description
The spec constants yaml file contains the field `DEPOSIT_CONTRACT_ADDRESS`.  Teku should default to this deposit contract value unless it is explicitly overridden via `--eth1-deposit-contract-address`.

Currently when I read in a mainnet constants file manually (by supplying a constants.yaml file via `--network`) with an existing mainnet database I get the error:
> Supplied deposit contract () does not match the stored database (0x00000000219ab540356cbb839cbe05303d7705fa). Check that the existing database matches the current network settings.

I believe we should handle this by defaulting to the [`SpecConstants` value](https://github.com/mbaxter/teku/blob/3dd0c878f15d944f0827ead22bdadd41bccdb182/ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java#L149) if the configured value is empty [here](https://github.com/mbaxter/teku/blob/3dd0c878f15d944f0827ead22bdadd41bccdb182/ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java#L156).

### PR DESCRIPTION
**Pull request by rolfyone**
If the network configuration is missing a deposit contract address, attempt to load it from the constants.

Because all constants files have deposit contract set, the test for not having contract address has been removed, but the error has been left in case someone specifies a custom constants file that has the contract missing.

### Documentation
Deposit contract address can be loaded from constants, basically if the deposit contract isn't specified in the network configuration, it will be loaded from constants now. previously the doc stated it could be loaded from `--initial-state` or `--network`, which should continue to hold true, but now if it's not defined on startup by the network, then it will load from the defined constants.

fixes #3723

Signed-off-by: Paul Harris <paul.harris@consensys.net>

## Documentation

- [X] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by ajsutton — APPROVED** [review]
LGTM.

File: ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java [hunk 1]
```diff
@@ -146,8 +146,14 @@ public String toString() {
     public Eth2NetworkConfiguration build() {
       checkNotNull(constants, "Missing constants");
 
+      final Spec spec = SpecFactory.create(constants);
+      // if the deposit contract was not set, default from constants
+      if (eth1DepositContractAddress.isEmpty()) {
```
Comment (mbaxter) [inline ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java:151]: There are a few places in the builder where we explicitly set the deposit contract even though it is already set in the constants.yaml.  We should be able to cut these now.  For example [here](https://github.com/ConsenSys/teku/blob/e324db83ef0b009d709fdde280e4649ec5b887c0/ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java#L270).

File: ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java [hunk 2]
```diff
@@ -146,8 +146,14 @@ public String toString() {
...
+        eth1DepositContractAddress(
+            spec.getGenesisSpec().getConstants().getDepositContractAddress().toHexString());
+      }
       return new Eth2NetworkConfiguration(
```
Comment (mbaxter) [inline ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java:155]: We should now be able to make `Eth2NetworkConfiguration.eth1DepositContractAddress` a simple `Eth1Address` rather than an `Optional<Eth1Address>`.  The constants parsing will fail if any field is missing, so we can rely on that value being available.

Comment (rolfyone) [reply ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java:155]: ah ok i wasn't sure if the field wasn't required - that sounds like a good change to make

Comment (rolfyone) [reply ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java:155]: raised #3730
