### PR TITLE
Use Eth1HeadTracker to find initial chain head

### LINKED ISSUE #4135: InvalidDepositEventsException on restart
Getting the exception below on restart across a number of boxes including seen locally once.

First problem is that it's only being logged at debug level and should be a big clear error message on the console.

Second problem is it doesn't resolve and we lose track of eth1 and start voting poorly.  Restarting (possibly after enough time passes) solves the issue.

We seem to be calculating the first block to request incorrectly after startup.

```
{"timestamp":"2021-07-07T04:57:17,851","level":"DEBUG","thread":"pool-17-thread-201","class":"DepositFetcher","message":"Failed to request deposit events for block numbers in the range (5049706, 5049706). Retrying.","throwable":" java.util.concurrent.CompletionException: tech.pegasys.teku.ethereum.pow.api.InvalidDepositEventsException: Expected next deposit
at index 128373, but got 128372
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2315)
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:529)
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32)
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142)
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$27(SafeFuture.java:367)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2315)
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:529)
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32)
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142)
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$27(SafeFuture.java:367)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2315)
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:529)
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32)
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142)
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$27(SafeFuture.java:367)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2315)
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:529)
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32)
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142)
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$27(SafeFuture.java:367)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
at org.web3j.utils.Async.lambda$run$1(Async.java:38)
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)\nCaused by: tech.pegasys.teku.ethereum.pow.api.InvalidDepositEventsException: Expected next deposit
at index 128373, but got 128372
at tech.pegasys.teku.ethereum.pow.api.InvalidDepositEventsException.expectedDepositAtIndex(InvalidDepositEventsException.java:26)
at tech.pegasys.teku.pow.ValidatingEth1EventsPublisher.assertDepositEventIsValid(ValidatingEth1EventsPublisher.java:56)
at tech.pegasys.teku.pow.ValidatingEth1EventsPublisher.onDepositsFromBlock(ValidatingEth1EventsPublisher.java:46)
at tech.pegasys.teku.pow.DepositFetcher.postDeposits(DepositFetcher.java:220)
at tech.pegasys.teku.pow.DepositFetcher.postEventsForBlock(DepositFetcher.java:186)
at tech.pegasys.teku.pow.DepositFetcher.postDepositEvents(DepositFetcher.java:157)
at tech.pegasys.teku.pow.DepositFetcher.lambda$postDepositEvents$4(DepositFetcher.java:173)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)\n\t... 70 more\n"}
```

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
Previously the startup process for eth1 tracking reimplemented the follow distance logic which meant it was still following based on the number of blocks rather than time.  Now it uses the current head tracking implementation.

## Fixed Issue(s)
fixes #4135 

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: pow/src/main/java/tech/pegasys/teku/pow/Eth1DepositManager.java [hunk 1]
```diff
@@ -165,12 +168,11 @@ private void preGenesisSubscription(final BigInteger lastProcessedBlockNumber) {
   }
 
   private SafeFuture<EthBlock.Block> getHead() {
-    return eth1Provider
-        .getGuaranteedLatestEth1Block()
-        .thenApply(EthBlock.Block::getNumber)
-        .thenApply(UInt64::valueOf)
-        .thenCompose(this::waitForEth1ChainToReachFollowDistanceIfNecessary)
-        .thenApply(number -> number.minus(Constants.ETH1_FOLLOW_DISTANCE))
+    final SafeFuture<UInt64> headBlockNumber = new SafeFuture<>();
```
Comment (rolfyone) [inline pow/src/main/java/tech/pegasys/teku/pow/Eth1DepositManager.java]: nit: we're now a future, maybe rename variable?

**Review by rolfyone — APPROVED** [review]
LGTM just a nit

File: pow/src/main/java/tech/pegasys/teku/pow/Eth1DepositManager.java (hunk 1 above)
Comment (ajsutton) [reply pow/src/main/java/tech/pegasys/teku/pow/Eth1DepositManager.java]: Done.
