### PR TITLE
Exit early if ports aren't available

### LINKED ISSUE #2328: Fail better when P2P port is in use
### Description
When the P2P port is in use, Teku starts and continues running but the P2P network is unable to start. The P2P network can't be started until genesis is known which is after the usual startup, and thus when it fails to start Teku continues running.

We should find a way to provide a clear, helpful error message and not start Teku when the P2P port is in use.  Need to ensure we think through how it works if the network is pre-genesis and what happens if the port isn't in use at initial startup but is in use by the time the network actually starts.

### LINKED ISSUE #2388: Verify that received block by range responses contain blocks in order
### Description
Blocks returned by a BeaconBlocksByRange request must be in order.  Teku should validate this and report an error to the peer if they are out of order.

### PR DESCRIPTION
**Pull request by rolfyone**
- users should be told that a port is in use, and the process should not continue.

 - p2p and http ports are checked. Http failure used to result in a stack trace to command line, but now prints and exits.

 fixes #2328

Signed-off-by: Paul Harris <paul.harris@consensys.net>

## Documentation

- [X] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: util/src/main/java/tech/pegasys/teku/util/config/PortAvailability.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+    return false;
+  }
+
+  public static boolean isPortAvailableForUdp(final int port) {
+    if (!isPortValid(port)) {
+      return false;
+    }
+    DatagramSocket datagramSocket = null;
+    try {
+      datagramSocket = new DatagramSocket(port);
```
Comment (ajsutton) [inline util/src/main/java/tech/pegasys/teku/util/config/PortAvailability.java]: Can we use try with resources for this?
```suggestion
    DatagramSocket datagramSocket = null;
    try (DatagramSocket datagramSocket = new DatagramSocket(port)) {
      datagramSocket = new DatagramSocket(port);
```

File: networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/network/NetworkConfig.java [hunk 2]
```diff
@@ -87,10 +89,24 @@ public NetworkConfig(
...
+      if (PortAvailability.isPortAvailable(listenPort)) {
+        this.listenPort = listenPort;
+      } else {
+        throw new InvalidConfigurationException(
+            String.format(
+                "P2P Port %d (TCP/UDP) is already in use. "
+                    + "Check for other processes using this port.",
+                listenPort));
+      }
+    }
```
Comment (ajsutton) [inline networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/network/NetworkConfig.java]: We shouldn't be doing this check in the constructor.  Actually opening sockets is something that should be deliberately done, not just a side effect of creation. Probably better as a `validate` method that's specifically called as part of the startup sequence (or possibly just use the getters and keep the logic out of the config class).

Comment (ajsutton) [reply networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/network/NetworkConfig.java]: Also this will check if the port is in use at startup, but we need to also specifically handle when the port was free at startup and became in use before we actually opened the socket.  This would happen if you were tracking a chain prior to the genesis event being known and running either two Teku's or a Teku and a Lighthouse - both would use port 9000 for p2p by default and only start listening when genesis becomes known (after startup).

File: util/src/main/java/tech/pegasys/teku/util/config/PortAvailability.java (hunk 1 above)
Comment (rolfyone) [reply util/src/main/java/tech/pegasys/teku/util/config/PortAvailability.java]: fair point, i'll give that a go.

File: util/src/main/java/tech/pegasys/teku/util/config/PortAvailability.java [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+    }
+    return false;
+  }
+
+  public static boolean isPortAvailableForUdp(final int port) {
+    if (!isPortValid(port)) {
+      return false;
+    }
+    try (final DatagramSocket datagramSocket = new DatagramSocket(port)) {
+      datagramSocket.setReuseAddress(true);
```
Comment (ajsutton) [inline util/src/main/java/tech/pegasys/teku/util/config/PortAvailability.java]: Looking at the docs for `setReuseAddress` it looks like it needs to be set before the socket is bound to guarantee it works.  So we'd have to do something like:
```suggestion
    try (final DatagramSocket datagramSocket = new DatagramSocket()) {
      datagramSocket.setReuseAddress(true);
      datagramSocket.bind(new InetSocketAddress(port));
```

and the same above for TCP.

**Review by ajsutton — APPROVED** [review]
LGTM.
