### PR TITLE
Weak subjectivity failure will now report to console

### LINKED ISSUE #3753: Provide clearer log messages when weak subjectivity checks fail
### Description
In #3751 the sync appeared to stall with no message to the console when the weak subjectivity checkpoint was incorrect.  We should have a very clear error message printed to the console in this case so the user knows that peers are attempting to lead them onto an incorrect chain (or they messed up the checkpoint and are trying to lead themselves onto the wrong chain).

### PR DESCRIPTION
**Pull request by rolfyone**
Previously weak subjectivity failures would report to file, but not console and it was difficult to see that sync was having trouble matching because of weak subjectivity.

fixes #3753

Signed-off-by: Paul Harris <paul.harris@consensys.net>

## Documentation

- [X] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: infrastructure/logging/src/main/java/tech/pegasys/teku/infrastructure/logging/EventLogger.java [hunk 1]
```diff
@@ -83,6 +83,14 @@ public void syncEvent(final UInt64 nodeSlot, final UInt64 headSlot, final int nu
     info(syncEventLog, Color.WHITE);
   }
 
+  public void weakSubjectivityFailedEvent(final Bytes32 blockRoot, final UInt64 slot) {
+    final String weakSubjectivityFailedEventLog =
+        String.format(
+            "Sync Event  *** Weak subjectivity check failed block: %s, slot: %s",
+            LogFormatter.formatHashRoot(blockRoot), slot.toString());
+    info(weakSubjectivityFailedEventLog, Color.RED);
```
Comment (ajsutton) [inline infrastructure/logging/src/main/java/tech/pegasys/teku/infrastructure/logging/EventLogger.java]: This should probably be at warn level not just info.

**Review by ajsutton — APPROVED** [review]
LGTM. I'd just bump up the log level.

File: infrastructure/logging/src/main/java/tech/pegasys/teku/infrastructure/logging/EventLogger.java (hunk 1 above)
Comment (rolfyone) [reply infrastructure/logging/src/main/java/tech/pegasys/teku/infrastructure/logging/EventLogger.java]: ok sure - wasn't sure what the events concept was, but i'll bump it.
