### PR TITLE
streams will not be left open when shutting down any more.

### LINKED ISSUE #2241: RocksDB Produces fatal error on shutdown
### Description
When shutting down teku, the following error occurred:
```
Teku is shutting down
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000136e6c988, pid=6007, tid=46595
#
# JRE version: Java(TM) SE Runtime Environment (11.0.3+12) (build 11.0.3+12-LTS)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (11.0.3+12-LTS, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [librocksdbjni11922200677829895721.jnilib+0x5d988]  rocksdb::GetColumnFamilyID(rocksdb::ColumnFamilyHandle*)+0x8
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/mbaxter/code/consensys/teku/build/hs_err_pid6007.log
[thread 115975 also had an error]
[thread 64003 also had an error]
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

Error report: [hs_err_pid6007.log](https://github.com/PegaSysEng/teku/files/4840769/hs_err_pid6007.log)

Teku restarted fine after this error.

### PR DESCRIPTION
**Pull request by rolfyone**
- added test case to show behaviour when streams are accessed after the database is closed.

- added DEBUG for when a shutdown exception happens so that it's visible in trace.

fixes #2241

Signed-off-by: Paul Harris <paul.harris@consensys.net>

## Documentation

- [X] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: storage/src/testFixtures/java/tech/pegasys/teku/storage/server/rocksdb/core/MockRocksDbInstance.java [hunk 1]
```diff
@@ -120,7 +121,9 @@ public static MockRocksDbInstance createEmpty(final Class<? extends Schema> sche
   public <K, V> Stream<ColumnEntry<K, V>> stream(final RocksDbColumn<K, V> column) {
     assertOpen();
     assertValidColumn(column);
-    return columnData.get(column).entrySet().stream().map(e -> columnEntry(column, e));
+    return columnData.get(column).entrySet().stream()
+        .peek(value -> assertOpen())
```
Comment (cemozerr) [inline storage/src/testFixtures/java/tech/pegasys/teku/storage/server/rocksdb/core/MockRocksDbInstance.java:125]: nit: the `Streams.peek()` method to quote its Javadoc: "exists mainly to support debugging", so we might want to stay away from using it in production.

**Review by cemozerr — APPROVED** [review]
Made a comment on the usage of `Stream.peek()`. Rest looks good to me.

File: storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/core/RocksDbIterator.java [hunk 2]
```diff
@@ -93,6 +100,9 @@ public boolean hasNext() {
   }
 
   private void assertOpen() {
+    if (this.isDatabaseClosed.get()) {
+      throw new ShuttingDownException();
+    }
     if (closed.get()) {
       throw new IllegalStateException("Attempt to update a closed transaction");
```
Comment (mbaxter) [inline storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/core/RocksDbIterator.java]: (optional) While we're here:
```suggestion
      throw new IllegalStateException("Attempt to update a closed " + this.getClass().getSimpleName());
```

File: storage/src/testFixtures/java/tech/pegasys/teku/storage/server/rocksdb/core/MockRocksDbInstance.java (hunk 1 above)
Comment (rolfyone) [reply storage/src/testFixtures/java/tech/pegasys/teku/storage/server/rocksdb/core/MockRocksDbInstance.java:125]: yep its just so that the Mock db instance behaves 'similar' to the real one, so I think its ok here...
