### PR TITLE
Deliver EventChannel responses on a publisher owned thread

### LINKED ISSUE #2347: Teku deadlock
### Description
After running on Altona for a number of days without any issues, Teku silently stopped importing blocks (failed to recognise the chain head had moved forward at all).

Thread dump is attached which shows a lot of event bus threads all waiting on a lock which suggests something has deadlocked or gotten stuck.

[stack.txt](https://github.com/PegaSysEng/teku/files/4915374/stack.txt)

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
When an `EventChannel` returns a future, previously it was completed on the channel's subscriber thread, which meant that any chained actions also happened on the subscriber thread and had to complete before the subscriber could move on to the next event.

Instead, for any `EventChannel` that can return a future, creating a publisher now requires specifying an `AsyncRunner` which is used to complete the returned future.  This way the chained actions are all completed on a thread owned by the publisher's service, not the subscribers.  As a specific example, when the validator service makes a call to `ValidatorApiChannel`, the call is handled in the beacon chain on a thread dedicated to `ValidatorApiChannel`, but the returned future is completed by the `AsyncRunner` the validator service provided when creating its publisher.  So execution correctly moves from validator service to beacon service and then back.

If the channel doesn't return values (all methods return `void`), a publisher can be created without specifying an `AsyncRunner`, otherwise one is required.  This is achieved by introducing two marker interfaces - `ChannelInterface` and `NonReturningChannelInterface` which extends it.  All event channels must extend one of those and that's enforced by the compiler.  A runtime check is performed to reject creating an `EventChannel` for an interface that extends `NonReturningEventChannel` if it has any methods that return something other than `void`.

The additional benefit of the marker interfaces is that it's simple to find all interfaces which are used with event channels which was slightly challenging previously.

## Fixed Issue(s)
fixes #2347 

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: events/src/main/java/tech/pegasys/teku/events/EventChannel.java [hunk 1]
```diff
@@ -130,7 +129,14 @@ private static boolean hasAllowedAsyncReturnValue(final Class<?> returnType) {
         && returnType.isAssignableFrom(SafeFuture.class);
   }
 
-  public T getPublisher() {
+  public T getPublisher(final Optional<AsyncRunner> responseRunner) {
```
Comment (mbaxter) [inline events/src/main/java/tech/pegasys/teku/events/EventChannel.java]: Should this class and its methods be package-private?  It seems that we always go through `EventChannels` from outside this package.

**Review by cemozerr — APPROVED** [review]
LGTM.
