### PR TITLE
Report unknown block instead of throwing NullPointerException

### LINKED ISSUE #2313: Failed to process annotation
### Description
Got this exception on Altona (node was fully in sync):

```
2020-07-03 16:32:37.538 | P2PService-event-thread-0 | WARN  | gregateAttestationTopicHandler | Encountered exception while processing message for topic /eth2/fdca39b0/beacon_aggregate_and_proof/ssz_snappy
java.lang.NullPointerException: null
	at tech.pegasys.teku.datastructures.util.ValidatorsUtil.lambda$get_active_validator_indices$2(ValidatorsUtil.java:94) ~[classes/:?]
	at tech.pegasys.teku.util.cache.NoOpCache.get(NoOpCache.java:47) ~[classes/:?]
	at tech.pegasys.teku.datastructures.util.ValidatorsUtil.get_active_validator_indices(ValidatorsUtil.java:91) ~[classes/:?]
	at tech.pegasys.teku.datastructures.util.BeaconStateUtil.get_committee_count_at_slot(BeaconStateUtil.java:597) ~[classes/:?]
	at tech.pegasys.teku.datastructures.util.CommitteeUtil.lambda$get_beacon_committee$2(CommitteeUtil.java:255) ~[classes/:?]
	at tech.pegasys.teku.util.cache.NoOpCache.get(NoOpCache.java:47) ~[classes/:?]
	at tech.pegasys.teku.datastructures.util.CommitteeUtil.get_beacon_committee(CommitteeUtil.java:251) ~[classes/:?]
	at tech.pegasys.teku.datastructures.util.AttestationUtil.get_attesting_indices(AttestationUtil.java:117) ~[classes/:?]
	at tech.pegasys.teku.datastructures.util.AttestationUtil.get_indexed_attestation(AttestationUtil.java:90) ~[classes/:?]
	at tech.pegasys.teku.core.ForkChoiceUtil.indexAndValidateAttestation(ForkChoiceUtil.java:384) ~[classes/:?]
	at tech.pegasys.teku.core.ForkChoiceUtil.lambda$on_attestation$2(ForkChoiceUtil.java:352) ~[classes/:?]
	at tech.pegasys.teku.datastructures.util.AttestationProcessingResult.ifSuccessful(AttestationProcessingResult.java:43) ~[classes/:?]
	at tech.pegasys.teku.core.ForkChoiceUtil.on_attestation(ForkChoiceUtil.java:352) ~[classes/:?]
	at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.onAttestation(ForkChoice.java:93) ~[classes/:?]
	at tech.pegasys.teku.statetransition.attestation.ForkChoiceAttestationProcessor.processAttestation(ForkChoiceAttestationProcessor.java:36) ~[classes/:?]
	at tech.pegasys.teku.statetransition.attestation.AttestationManager.onAttestation(AttestationManager.java:115) ~[classes/:?]
	at tech.pegasys.teku.services.beaconchain.BeaconChainController.lambda$initP2PNetwork$6(BeaconChainController.java:396) ~[classes/:?]
	at tech.pegasys.teku.networking.eth2.gossip.topics.AggregateAttestationTopicHandler.handleMessage(AggregateAttestationTopicHandler.java:62) [classes/:?]
	at tech.pegasys.teku.networking.p2p.libp2p.gossip.GossipHandler.apply(GossipHandler.java:77) [classes/:?]
	at tech.pegasys.teku.networking.p2p.libp2p.gossip.GossipHandler.apply(GossipHandler.java:34) [classes/:?]
	at io.libp2p.pubsub.PubsubApiImpl.onNewMessage(PubsubApiImpl.kt:71) [jvm-libp2p-minimal-0.5.2-RELEASE.jar:?]
	at io.libp2p.pubsub.PubsubApiImpl.access$onNewMessage(PubsubApiImpl.kt:23) [jvm-libp2p-minimal-0.5.2-RELEASE.jar:?]
	at io.libp2p.pubsub.PubsubApiImpl$1.invoke(PubsubApiImpl.kt:55) [jvm-libp2p-minimal-0.5.2-RELEASE.jar:?]
	at io.libp2p.pubsub.PubsubApiImpl$1.invoke(PubsubApiImpl.kt:23) [jvm-libp2p-minimal-0.5.2-RELEASE.jar:?]
	at io.libp2p.pubsub.AbstractRouter.onInbound(AbstractRouter.kt:200) [jvm-libp2p-minimal-0.5.2-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService.streamInbound(P2PService.kt:149) [jvm-libp2p-minimal-0.5.2-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelRead$1.invoke(P2PService.kt:49) [jvm-libp2p-minimal-0.5.2-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelRead$1.invoke(P2PService.kt:35) [jvm-libp2p-minimal-0.5.2-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$sam$java_lang_Runnable$0.run(P2PService.kt) [jvm-libp2p-minimal-0.5.2-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Looks like back up at `ForkChoiceUtil.indexAndValidateAttestation` `getCheckpointState` returned null and we should have deferred attestation processing because we didn't have the block it referred to but didn't?

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
It's possible that the block targeted by an attestation is dropped from the store while we're processing the attestation. We could wind up passing the initial check that the block is known because it hasn't been pruned from protoarray when we do that check and then later fail to create the checkpoint state for that target because the block isn't available in the store resulting in a `NullPointerException`.

If the checkpoint state is unavailable, the target block must be unknown so defer the attestation. Worst case the block is invalid and the attestation gets dropped once it is too old.

To reduce the risk of this in future, `getCheckpointState` now returns an `Optional`.

## Fixed Issue(s)
fixes #2313 

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: ethereum/core/src/main/java/tech/pegasys/teku/core/ForkChoiceUtil.java [hunk 1]
```diff
@@ -370,26 +370,30 @@ public static AttestationProcessingResult on_attestation(
...
+      if (maybeTargetState.isEmpty()) {
+        return AttestationProcessingResult.UNKNOWN_BLOCK;
+      }
+      targetState = maybeTargetState.get();
     } catch (final InvalidCheckpointException e) {
       LOG.debug("on_attestation: Attestation target checkpoint is invalid", e);
       return AttestationProcessingResult.invalid("Invalid target checkpoint: " + e.getMessage());
     }
 
     // Get state at the `target` to validate attestation and calculate the committees
```
Comment (cemozerr) [inline ethereum/core/src/main/java/tech/pegasys/teku/core/ForkChoiceUtil.java]: nit: We might as well remove this stale "get state at the target" comment, or move it up to where it's appropriate.

**Review by cemozerr — APPROVED** [review]
LGTM

File: ethereum/core/src/main/java/tech/pegasys/teku/core/ForkChoiceUtil.java (hunk 1 above)
Comment (ajsutton) [reply ethereum/core/src/main/java/tech/pegasys/teku/core/ForkChoiceUtil.java]: Done.
