### PR TITLE
[BC-415] Rework CombinedChainDataClient.getStateAtSlot()

### LINKED ISSUE #1713: Unexpected exception thrown for java.lang.NullPointerException
### Description
On Schlesi, the client tells me to report the following exception after the sync seemingly completed:

```
13:36:24.118 FATAL - PLEASE FIX OR REPORT | Unexpected exception thrown for java.lang.NullPointerException: event 'interface tech.pegasys.artemis.validator.api.ValidatorApiChannel.getDuties' in handler 'tech.pegasys.artemis.validator.coordinator.ValidatorApiHandler'
java.lang.NullPointerException: null
	at tech.pegasys.artemis.storage.client.CombinedChainDataClient.getStateAtSlot(CombinedChainDataClient.java:204) ~[artemis-storage-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
```
### Steps to Reproduce (Bug)
1. Build Teku latest master
2. Configure for Schlesi https://github.com/goerli/schlesi
3. Connect to a local node
4. Wait for a full sync to complete

**Expected behavior:**

Run Smoothly.

**Actual behavior:**

Runtime Exception:

```
13:35:48.116 INFO  - Sync Event *** Current slot: 36479, Head block: 35705, Connected peers: 2
13:36:00.116 INFO  - Sync Event *** Current slot: 36480, Head block: 35919, Connected peers: 2
13:36:12.116 INFO  - Sync Event *** Current slot: 36481, Head block: 36132, Connected peers: 2
13:36:24.118 FATAL - PLEASE FIX OR REPORT | Unexpected exception thrown for java.lang.NullPointerException: event 'interface tech.pegasys.artemis.validator.api.ValidatorApiChannel.getDuties' in handler 'tech.pegasys.artemis.validator.coordinator.ValidatorApiHandler'
java.lang.NullPointerException: null
	at tech.pegasys.artemis.storage.client.CombinedChainDataClient.getStateAtSlot(CombinedChainDataClient.java:204) ~[artemis-storage-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.storage.client.CombinedChainDataClient.lambda$getStateAtSlot$6(CombinedChainDataClient.java:180) ~[artemis-storage-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at java.util.Optional.map(Optional.java:258) ~[?:?]
	at tech.pegasys.artemis.storage.client.CombinedChainDataClient.getStateAtSlot(CombinedChainDataClient.java:180) ~[artemis-storage-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.validator.coordinator.ValidatorApiHandler.getDuties(ValidatorApiHandler.java:112) ~[artemis-validator-coordinator-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at tech.pegasys.artemis.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:67) ~[artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:60) ~[artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:70) ~[artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111) [artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103) [artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
13:36:24.122 FATAL - PLEASE FIX OR REPORT | Unexpected exception thrown for java.lang.NullPointerException: event 'interface tech.pegasys.artemis.validator.api.ValidatorApiChannel.getDuties' in handler 'tech.pegasys.artemis.validator.coordinator.ValidatorApiHandler'
java.lang.NullPointerException: null
	at tech.pegasys.artemis.storage.client.CombinedChainDataClient.getStateAtSlot(CombinedChainDataClient.java:204) ~[artemis-storage-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.storage.client.CombinedChainDataClient.lambda$getStateAtSlot$6(CombinedChainDataClient.java:180) ~[artemis-storage-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at java.util.Optional.map(Optional.java:258) ~[?:?]
	at tech.pegasys.artemis.storage.client.CombinedChainDataClient.getStateAtSlot(CombinedChainDataClient.java:180) ~[artemis-storage-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.validator.coordinator.ValidatorApiHandler.getDuties(ValidatorApiHandler.java:112) ~[artemis-validator-coordinator-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at tech.pegasys.artemis.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:67) ~[artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:60) ~[artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:70) ~[artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111) [artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103) [artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
13:36:27.262 FATAL - PLEASE FIX OR REPORT | Unexpected exception thrown for java.lang.NullPointerException: event 'interface tech.pegasys.artemis.validator.api.ValidatorApiChannel.getDuties' in handler 'tech.pegasys.artemis.validator.coordinator.ValidatorApiHandler'
java.lang.NullPointerException: null
	at tech.pegasys.artemis.storage.client.CombinedChainDataClient.getStateAtSlot(CombinedChainDataClient.java:204) ~[artemis-storage-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.storage.client.CombinedChainDataClient.lambda$getStateAtSlot$6(CombinedChainDataClient.java:180) ~[artemis-storage-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at java.util.Optional.map(Optional.java:258) ~[?:?]
	at tech.pegasys.artemis.storage.client.CombinedChainDataClient.getStateAtSlot(CombinedChainDataClient.java:180) ~[artemis-storage-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.validator.coordinator.ValidatorApiHandler.getDuties(ValidatorApiHandler.java:112) ~[artemis-validator-coordinator-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at tech.pegasys.artemis.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:67) ~[artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:60) ~[artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:70) ~[artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111) [artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103) [artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
13:36:27.264 FATAL - PLEASE FIX OR REPORT | Unexpected exception thrown for java.lang.NullPointerException: event 'interface tech.pegasys.artemis.validator.api.ValidatorApiChannel.getDuties' in handler 'tech.pegasys.artemis.validator.coordinator.ValidatorApiHandler'
java.lang.NullPointerException: null
	at tech.pegasys.artemis.storage.client.CombinedChainDataClient.getStateAtSlot(CombinedChainDataClient.java:204) ~[artemis-storage-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.storage.client.CombinedChainDataClient.lambda$getStateAtSlot$6(CombinedChainDataClient.java:180) ~[artemis-storage-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at java.util.Optional.map(Optional.java:258) ~[?:?]
	at tech.pegasys.artemis.storage.client.CombinedChainDataClient.getStateAtSlot(CombinedChainDataClient.java:180) ~[artemis-storage-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.validator.coordinator.ValidatorApiHandler.getDuties(ValidatorApiHandler.java:112) ~[artemis-validator-coordinator-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at tech.pegasys.artemis.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:67) ~[artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:60) ~[artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:70) ~[artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111) [artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at tech.pegasys.artemis.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103) [artemis-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-e8d96cf0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
13:36:28.116 INFO  - Slot Event *** Slot: 36482, Block:  x ... empty, Epoch: 1140, Finalized Epoch: 1133, Finalized Root: 0xa9b1..ca36
13:36:40.116 INFO  - Slot Event *** Slot: 36483, Block:  x ... empty, Epoch: 1140, Finalized Epoch: 1133, Finalized Root: 0xa9b1..ca36
13:36:52.116 INFO  - Slot Event *** Slot: 36484, Block:  x ... empty, Epoch: 1140, Finalized Epoch: 1133, Finalized Root: 0xa9b1..ca36
```

Note how finalized epoch is lacking behind (even though the chain is finalized at 1138) and the blocks are empty (even though they aren't).

**Frequency:**

1 - Only did one full sync so far.

### Versions (Add all that apply)
* Software version: teku/v0.11.0-dev-e8d96cf0/linux-x86_64/-na-openjdk64bitservervm-java-13
* Java version: openjdk version "13.0.2" 2020-01-14
* OS Name & Version: Arch Linux
* Kernel Version: Linux intan 5.6.5-arch3-1 #1 SMP PREEMPT Sun, 19 Apr 2020 13:14:25 +0000 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by mbaxter**
## PR Description
Rework `CombinedChainDataClient.getStateAtSlot()`.

To avoid race conditions, don't query based on head block root.  First try to query from recent data, and then query from historical state to control for case where blocks are being rapidly imported, and the slot being queried is finalized during processing.

Also, added some test utilities to make it easier to write integration tests:  
- Added `MockRocksDbInstance`, which allows us to create an in-memory version of `RocksDbDatabase`
- Added `InMemoryStorageSystem` which sets up and wires together an in-memory database with a `RecentChainData` instance, and makes the `RecentChainData` instance as well as a `CombinedChainData` instance available.
- Added a `ChainUpdater` that generates chain data with `ChainGenerator` and immediately adds the data to a `RecentChainData` instance.  

Fixes https://github.com/PegaSysEng/teku/issues/1713

### CODE REVIEW

File: storage/src/main/java/tech/pegasys/teku/storage/client/CombinedChainDataClient.java [hunk 1]
```diff
@@ -149,11 +147,6 @@ public CombinedChainDataClient(
     return getBlockByBlockRoot(get_block_root_at_slot(state, slot));
   }
 
-  private boolean isHistoricalData(final UnsignedLong slot) {
-    final boolean finalizedPastFirstEpoch = !recentChainData.getFinalizedEpoch().equals(ZERO);
```
Comment (mbaxter) [inline storage/src/main/java/tech/pegasys/teku/storage/client/CombinedChainDataClient.java:153]: I don't see why we need a special case for the first epoch / genesis block, so I cut this.  But if there's a valid reason, I can add this back in.

Comment (ajsutton) [reply storage/src/main/java/tech/pegasys/teku/storage/client/CombinedChainDataClient.java:153]: I believe it was added because we were always going to disk to retrieve the genesis state due to it being inherently finalised.  But I think we've fixed `isFinalized` now so the last finalized slot is expected to be in memory.

Basically as long as the genesis state is retrieved from the memory store instead of disk it's fine to cut it.

Comment (mbaxter) [reply storage/src/main/java/tech/pegasys/teku/storage/client/CombinedChainDataClient.java:153]: Ok, so basically we want to retrieve latest finalized data from memory, whether or not its on the epoch boundary?  And this applies for all finalized data, not just genesis?

File: storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/RocksDbDatabase.java [hunk 2]
```diff
@@ -53,7 +53,11 @@
 
   public static Database createV3(
       final RocksDbConfiguration configuration, final StateStorageMode stateStorageMode) {
-    final RocksDbInstance db = RocksDbInstanceFactory.create(configuration, V3Schema.class);
+    final RocksDbAccessor db = RocksDbInstanceFactory.create(configuration, V3Schema.class);
+    return createV3(db, stateStorageMode);
+  }
+
+  static Database createV3(final RocksDbAccessor db, final StateStorageMode stateStorageMode) {
```
Comment (mbaxter) [inline storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/RocksDbDatabase.java:60]: Created this `RocksDbAccessor` interface so that we could have a mock in-memory replacement for the core RocksDB access logic.  Not super happy with the current implementation, but leaving a larger refactor for the future since we have active development in this area.

File: storage/src/main/java/tech/pegasys/teku/storage/client/CombinedChainDataClient.java [hunk 3]
```diff
@@ -107,7 +106,7 @@ public CombinedChainDataClient(
       LOG.trace("Block root at slot {} is the specified head block root", slot);
       return getBlockByBlockRoot(headBlockRoot);
     }
-    if (isHistoricalData(slot)) {
+    if (!isRecentData(slot)) {
       LOG.trace("Block at slot {} is in a finalized epoch. Retrieving from historical data", slot);
       return historicalChainData.getLatestFinalizedBlockAtSlot(slot);
     }
```
Comment (ajsutton) [inline storage/src/main/java/tech/pegasys/teku/storage/client/CombinedChainDataClient.java:112]: Aren't we at risk of race conditions here?  ie we check if the slot is recent and it is, but then before we actually get the block the store is changed and the slot we're interested in is dropped.  Seems like we should try to get it from the Store and if it's not there, then fall back to getting it from disk.  That would be a reasonable way to handle the case where we need to request a block that's more than `SLOTS_PER_HISTORICAL_ROOT` behind the current state as well - we'd fail to get it from the store and fallback to getting it from disk.

File: storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/schema/Schema.java [hunk 4]
```diff
@@ -35,4 +35,18 @@
               }
             });
   }
+
+  static Stream<RocksDbVariable<?>> streamVariables(Class<? extends Schema> schema) {
+    return Arrays.stream(schema.getDeclaredFields())
+        .filter(f -> (f.getModifiers() & Modifier.STATIC) > 0)
```
Comment (ajsutton) [inline storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/schema/Schema.java]:
```suggestion
        .filter(f -> Modifiers.isState(f.getModifiers()))
```
and could apply the same change above in `streamColumns` because apparently you should use the `java.lang.reflect.Modifiers` class to decode modifiers...

**Review by ajsutton — APPROVED** [review]
LGTM.

File: storage/src/main/java/tech/pegasys/teku/storage/client/CombinedChainDataClient.java (hunk 3 above)
Comment (mbaxter) [reply storage/src/main/java/tech/pegasys/teku/storage/client/CombinedChainDataClient.java:112]: I think this method currently has a few problems - coming back to it in a follow-up PR.
