### PR TITLE
EL logging improvements

### LINKED ISSUE #6952: Improve EL logging
The following log messages could be misleading, since INVALID is a 200 response status per the engine API spec, but we return it in case of any error or if EL is syncing. Also INVALID could be understood as the endpoint is incorrectly configured. This log statement could be improved to avoid confusion.

```
2023-03-16 02:14:15.348 WARN  - Endpoint 10.0.1.254:8545 [1] is INVALID | Still syncing
2023-03-16 04:13:01.986 WARN  - Endpoint http://10.0.1.254:8551 is INVALID | Connection refused
```

### PR DESCRIPTION
**Pull request by StefanBratanov**
## PR Description

- Logging changes in `Web3jEth1Provider` to avoid confusion with INVALID|VALID
- Some other small logging nits

## Fixed Issue(s)
fixes #6952 

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java [hunk 1]
```diff
@@ -96,20 +97,15 @@ protected void handleError(final Throwable error) {
...
-              if (lastErrorTime == NO_ERROR_TIME
-                  || givenErrorTimeUpdate - lastErrorTime > ERROR_REPEAT_DELAY_MILLIS) {
-                return givenErrorTimeUpdate;
-              }
-              return lastErrorTime;
-            });
-    if (maybeUpdatedTime == timeNow) {
-      logExecutionClientError(error, couldBeAuthError);
+    if (error instanceof SocketException) { // indicates that EL is offline
+      if (shouldReportError()) {
```
Comment (mehdi-aouadi) [inline ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java]: I think it would be better to keep the `executionClientEventsPublisher.onAvailabilityUpdated(false)` in here to keep considering the `ERROR_REPEAT_DELAY_MILLIS`. In my understanding, we shouldn't consider the EL unavailable at the first error (There could be some minor network issues or timeouts and that doesn't necessarily mean that the EL is unavailable)

**Review by mehdi-aouadi — CHANGES_REQUESTED** [review]
The logs improvements LGTM.
I am not sure of considering the `SocketException` only to report the EL unavailable though.
If another issue occurs (Other than `SocketException`) and is recurrent, that could also mean the EL is unavailable...
I'd suggest checking what are the errors usually reported to have an idea of what we could prioritise

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java [hunk 2]
```diff
@@ -96,20 +97,15 @@ protected void handleError(final Throwable error) {
...
-            (lastErrorTime, givenErrorTimeUpdate) -> {
-              if (lastErrorTime == NO_ERROR_TIME
-                  || givenErrorTimeUpdate - lastErrorTime > ERROR_REPEAT_DELAY_MILLIS) {
-                return givenErrorTimeUpdate;
-              }
-              return lastErrorTime;
-            });
-    if (maybeUpdatedTime == timeNow) {
-      logExecutionClientError(error, couldBeAuthError);
+    if (error instanceof SocketException) { // indicates that EL is offline
```
Comment (zilm13) [inline ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java]: Works good for http and websockets, but doesn't work for IPC
```
2023-03-17 01:07:17.894+04:00 | pool-4-thread-2 | ERROR | teku-event-log | ESC[31mExecution Client request failed. Make sure the Execution Client is online and can respond to requests.ESC[0m
java.lang.RuntimeException: Provided file socket cannot be opened: /home/zilm/projects/goerli/geth-data/geth.ipc
at org.web3j.protocol.ipc.UnixDomainSocket.<init>(UnixDomainSocket.java:51) ~[core-4.9.7.jar:?]
at org.web3j.protocol.ipc.UnixDomainSocket.<init>(UnixDomainSocket.java:37) ~[core-4.9.7.jar:?]
at org.web3j.protocol.ipc.UnixIpcService.getIO(UnixIpcService.java:31) ~[core-4.9.7.jar:?]
at org.web3j.protocol.ipc.IpcService.performIO(IpcService.java:43) ~[core-4.9.7.jar:?]
at org.web3j.protocol.Service.send(Service.java:48) ~[core-4.9.7.jar:?]
at org.web3j.protocol.Service.lambda$sendAsync$0(Service.java:60) ~[core-4.9.7.jar:?]
at org.web3j.utils.Async.lambda$run$1(Async.java:38) ~[core-4.9.7.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.io.IOException: No such file or directory
at jnr.unixsocket.UnixSocketChannel.doConnect(UnixSocketChannel.java:130) ~[jnr-unixsocket-0.38.17.jar:?]
at jnr.unixsocket.UnixSocketChannel.connect(UnixSocketChannel.java:139) ~[jnr-unixsocket-0.38.17.jar:?]
at jnr.unixsocket.UnixSocketChannel.open(UnixSocketChannel.java:68) ~[jnr-unixsocket-0.38.17.jar:?]
at org.web3j.protocol.ipc.UnixDomainSocket.<init>(UnixDomainSocket.java:45) ~[core-4.9.7.jar:?]
... 10 more
```

Comment (StefanBratanov) [reply ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java]: Good point. Thanks for testing. Will think about it. May only leave the logging improvements.

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java (hunk 1 above)
Comment (StefanBratanov) [reply ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java]: Agree, left only the logging changes, since I am not sure as well.

**Review by mehdi-aouadi — APPROVED** [review]
LGTM.
Those `INVALID` were really misleading. It's way better this way!

**Review by rolfyone — APPROVED** [review]
nice!
