### PR TITLE
Rocksdb performance improvements

### LINKED ISSUE #8939: JVM crash when restarting teku (24.10.3) running rocksDB
```
Teku is shutting down
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000001, pid=692, tid=1558552
#
# JRE version: OpenJDK Runtime Environment (21.0.5+11) (build 21.0.5+11-Ubuntu-1ubuntu122.04)
# Java VM: OpenJDK 64-Bit Server VM (21.0.5+11-Ubuntu-1ubuntu122.04, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [librocksdbjni4770057874007981762.so+0x68f758]{"@timestamp":"2024-12-19T11:12:26,793","level":"INFO","thread":"Thread-12","class":"Javalin","message":"Stopping Javalin ...","throwable":""}
{"@timestamp":"2024-12-19T11:12:26,794","level":"INFO","thread":"Thread-12","class":"Server","message":"Stopped Server@60a43613{STOPPING}[11.0.23,sto=0]","throwable":""}
  rocksdb::RandomAccessFileReader::Read(rocksdb::IOOptions const&, unsigned long, unsigned long, rocksdb::Slice*, char*, std::unique_ptr<char [], std::default_delete<char []> >*) const+0xa58
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /opt/teku/teku-24.10.3/core.692)
#
```

### PR DESCRIPTION
**Pull request by gfukushima**
## PR Description

This PR is a alean up after #9059 which was used mostly for tests/deployment. It adds a couple params that are bringing the db to much healthier state. Iterators are performing much better now looking at the timestamps of logs (order of ms against minutes using the current config).
Example:
```
"@timestamp":"2025-02-03T22:52:44,526","level":"DEBUG","thread":"CombinedStorageChannel-0","class":"CombinedKvStoreDao","message":"Fetching earliest beacon block from db","throwable":""}
{"@timestamp":"2025-02-03T22:52:44,585","level":"DEBUG","thread":"CombinedStorageChannel-0","class":"CombinedKvStoreDao","message":"Earliest block slot in column: Optional[SignedBeaconBlockDeneb{message=BeaconBlockDeneb{slot=2503200, proposer_index=254597, parent_root=0x09071872d788a160ce5c4f7f01214157a719c2c1ccb80a0114300bc62c691568, state_root=0x44cb56c1b485427921866e3907665bca04ff5c1579af5c48bc742ef925ec4752, body=BeaconBlockBodyDeneb{randao_reveal=SszByteVector{0x97c9b4986e
```

Increasing the cache allowed to rocksdb hasn't shown any negative impacts on the memory consumption.
Log rotation also helps to keep the amount of log files we keep to a minimum reusing already created ones.

Testing node running these configs usage:
```
| ----------------------------------- | --------------- | ----------- | --------------- | ---------------- |
| Column Family                       | Keys            | Total Size  | SST Files Size  | Blob Files Size  |
| ----------------------------------- | --------------- | ----------- | --------------- | ---------------- |
| null                                | 14              | 138 MiB     | 138 MiB         | 0 B              |
| HOT_BLOCKS_BY_ROOT                  | 56              | 6 MiB       | 6 MiB           | 0 B              |
| HOT_STATES_BY_ROOT                  | 1               | 138 MiB     | 138 MiB         | 0 B              |
| HOT_BLOCK_CHECKPOINT_EPOCHS_BY_ROOT | 56              | 20 KiB      | 20 KiB          | 0 B              |
| SLOTS_BY_FINALIZED_ROOT             | 969506          | 38 MiB      | 38 MiB          | 0 B              |
| FINALIZED_BLOCKS_BY_SLOT            | 974629          | 35 GiB      | 35 GiB          | 0 B              |
| BLOB_SIDECAR_BY_SLOT_AND_BLOCK_ROOT_AND_BLOB_INDEX | 298522          | 10 GiB      | 10 GiB          | 0 B              |
| ----------------------------------- | --------------- | ----------- | --------------- | ---------------- |
| ESTIMATED TOTAL                     | 2242784         | 45 GiB      | 45 GiB          | 0 B              |
| ----------------------------------- | --------------- | ----------- | --------------- | ---------------- |
```

```
Displaying column usage from RocksDB folder /db
| ----------------------------------- | --------------- | ----------- | --------------- | ---------------- |
| Column Family                       | Keys            | Total Size  | SST Files Size  | Blob Files Size  |
| ----------------------------------- | --------------- | ----------- | --------------- | ---------------- |
| null                                | 10              | 256 MiB     | 256 MiB         | 0 B              |
| HOT_BLOCKS_BY_ROOT                  | 63              | 6 MiB       | 6 MiB           | 0 B              |
| STATE_ROOT_TO_SLOT_AND_BLOCK_ROOT   | 6               | 10 KiB      | 10 KiB          | 0 B              |
| HOT_STATES_BY_ROOT                  | 1               | 256 MiB     | 256 MiB         | 0 B              |
| HOT_BLOCK_CHECKPOINT_EPOCHS_BY_ROOT | 63              | 44 KiB      | 44 KiB          | 0 B              |
| SLOTS_BY_FINALIZED_ROOT             | 974595          | 47 MiB      | 47 MiB          | 0 B              |
| FINALIZED_BLOCKS_BY_SLOT            | 973159          | 128 GiB     | 128 GiB         | 0 B              |
| BLOB_SIDECAR_BY_SLOT_AND_BLOCK_ROOT_AND_BLOB_INDEX | 298362          | 77 GiB      | 77 GiB          | 0 B              |
| ----------------------------------- | --------------- | ----------- | --------------- | ---------------- |
| ESTIMATED TOTAL                     | 2246259         | 206 GiB     | 206 GiB         | 0 B              |
| ----------------------------------- | --------------- | ----------- | --------------- | ---------------- |
```

Memory consumption seems similar to what we currently see on canary-02.

Screenshot 2025-02-05 at 11 47 38 am

## Fixed Issue(s)

Fixes #8939 and #9051
## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/KvStoreConfiguration.java [hunk 1]
```diff
@@ -51,7 +51,7 @@ public class KvStoreConfiguration {
 
   public static final int DEFAULT_MAX_BACKGROUND_JOBS = 6;
   public static final int DEFAULT_BACKGROUND_THREAD_COUNT = 6;
-  public static final long DEFAULT_CACHE_CAPACITY = 8 << 20; // 8MB
+  public static final long DEFAULT_CACHE_CAPACITY = 134217728; // 128MB
```
Comment (rolfyone) [inline storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/KvStoreConfiguration.java]: i left this in `DEFAULT_CACHE_CAPACITY = 128 << 20; // 128MB` in the other PR, would be more clear

File: storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/RocksDbInstanceFactory.java [hunk 2]
```diff
@@ -165,7 +170,7 @@ private static ColumnFamilyOptions createColumnFamilyOptions(
       final KvStoreConfiguration configuration, final Cache cache) {
     return new ColumnFamilyOptions()
         .setCompressionType(configuration.getCompressionType())
-        .setBottommostCompressionType(configuration.getBottomMostCompressionType())
```
Comment (rolfyone) [inline storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/RocksDbInstanceFactory.java:168]: we should leave bottom most compression type in

Comment (gfukushima) [reply storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/RocksDbInstanceFactory.java:168]: I'll let your PR merge that change since you've been testing that.

File: storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/KvStoreConfiguration.java (hunk 1 above)
Comment (gfukushima) [reply storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/KvStoreConfiguration.java]: why do the bit shifting when we can actually specify a constant? I'm not strongly in favour of any tbh, but I'd rather use a constant number and have the comment clarifying that.

Comment (rolfyone) [reply storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/KvStoreConfiguration.java]: its a little clearer than 134xxxxxx == 128mb

Comment (gfukushima) [reply storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/KvStoreConfiguration.java]: alright, changed back to the old notation

File: storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/RocksDbInstanceFactory.java (hunk 2 above)
Comment (gfukushima) [reply storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/RocksDbInstanceFactory.java:168]: added this back after our chat, don't know why I removed this

**Review by rolfyone — APPROVED** [review]
