### PR TITLE
Store pending subnet subscriptions to be activated once the network starts

### LINKED ISSUE #1897: Attestation committee can not be subscribed due to gossip manager not being initialized
```
~/.opt/PegaSysEng/teku master 1h 14m 18s
❯ teku \
--config-file="/home/user/.opt/goerli/witti/teku/config.yaml" \
--network="/home/user/.opt/goerli/witti/teku/chain.yaml"
2020-05-22 21:04:01,323 main INFO Configuring logging for destination: console and file   
2020-05-22 21:04:01,324 main INFO Logging file location: /home/user/.local/share/teku/logs/teku.log
2020-05-22 21:04:01,325 main INFO Logging includes events: true
2020-05-22 21:04:01,325 main INFO Logging includes color: true
21:04:01.379 INFO  - Using data path: /home/user/.local/share/teku/data                   
21:04:01.396 INFO  - Initializing storage
21:04:06.404 INFO  - Storage initialization complete
21:04:06.405 INFO  - No genesis state available. Loading deposits from ETH1 chain
21:04:06.777 INFO  - PreGenesis Local ENR: enr:-KG4QLt4sp2CvRPwWhpk7-LzaVxigB6Pa4zsM0haUWQcRjQYes3o4mibcFfr2cwYzRrASa80zEFt0ikD36A00dbcMIYChGV0aDKQgGboQQAAARP__________4JpZIJ2NIJpcIQAAAAAiXNlY3AyNTZrMaECDDPsX1bTHaXfzuNfxItn2HgCLvBNLkzkRMdORDHyTSODdGNwgnUwg3VkcIJ1MA
21:04:17.056 INFO  - Activated 2 of 6 validators required for genesis (33%)               
21:04:17.116 INFO  - Activated 4 of 6 validators required for genesis (66%)               
21:04:17.414 FATAL - PLEASE FIX OR REPORT | Unexpected exception thrown for java.lang.IllegalStateException: Attestation committee can not be subscribed due to gossip manager not being initialized: event 'interface tech.pegasys.teku.validator.api.ValidatorApiChannel.subscribeToPersistentSubnets' in handler 'tech.pegasys.teku.validator.coordinator.ValidatorApiHandler'
java.lang.IllegalStateException: Attestation committee can not be subscribed due to gossip manager not being initialized
        at tech.pegasys.teku.networking.eth2.ActiveEth2Network.subscribeToAttestationSubnetId(ActiveEth2Network.java:154) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-e60fa13f]
        at tech.pegasys.teku.networking.eth2.gossip.AttestationTopicSubscriber.lambda$subscribeToPersistentSubnets$0(AttestationTopicSubscriber.java:63) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-e60fa13f]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1133) ~[?:?]
        at tech.pegasys.teku.networking.eth2.gossip.AttestationTopicSubscriber.subscribeToPersistentSubnets(AttestationTopicSubscriber.java:60) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-e60fa13f]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.subscribeToPersistentSubnets(ValidatorApiHandler.java:211) ~[teku-validator-coordinator-0.11.3-SNAPSHOT.jar:0.11.3-dev-e60fa13f]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]    
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at tech.pegasys.teku.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:67) ~[teku-events-0.11.3-SNAPSHOT.jar:0.11.3-dev-e60fa13f]
        at tech.pegasys.teku.events.DirectEventDeliverer.deliverTo(DirectEventDeliverer.java:54) ~[teku-events-0.11.3-SNAPSHOT.jar:0.11.3-dev-e60fa13f]
        at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverTo$0(AsyncEventDeliverer.java:60) ~[teku-events-0.11.3-SNAPSHOT.jar:0.11.3-dev-e60fa13f]
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111) [teku-events-0.11.3-SNAPSHOT.jar:0.11.3-dev-e60fa13f]             
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103) [teku-events-0.11.3-SNAPSHOT.jar:0.11.3-dev-e60fa13f]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
21:04:17.518 INFO  - Listening for connections on: /ip4/192.168.0.121/tcp/30000/p2p/16Uiu2HAkvFJnz2TvYeetr3orLXUeFsupKrY6o7rWc8QjzegTcCdx
21:04:17.533 INFO  - Genesis Event *** Initial state root: 0xd41cc44a345826d44c3efc18bfaf661f2a840e4c37489946dcd1a1ad4deee6d5, Genesis block root: 0x97e9ca93d15557d5314d8a2d112b3f0dc25227b5143232d863d4cb434bd469fa
21:04:17.581 INFO  - Local ENR: enr:-KG4QBsvSLPQ83UAcj2UIHlQm57iYExOzZy1hiFyVDEKClpWKYfCqZEDA1b9jRr-PmAy2TnmfdVmHfFAFth3ygXn_3MDhGV0aDKQbF7qsQAAARP__________4JpZIJ2NIJpcIQAAAAAiXNlY3AyNTZrMaECDDPsX1bTHaXfzuNfxItn2HgCLvBNLkzkRMdORDHyTSODdGNwgnUwg3VkcIJ1MA
21:04:21.396 INFO  - Slot Event *** Slot: 21, Block:    ... empty, Epoch: 0, Finalized checkpoint: 0, Finalized root: 0x97e9..69fa, Peers: 1
21:04:29.403 INFO  - Slot Event *** Slot: 22, Block: 0x45ef..54a4, Epoch: 0, Finalized checkpoint: 0, Finalized root: 0x97e9..69fa, Peers: 1
21:04:40.389 INFO  - Slot Event *** Slot: 23, Block: 0xcfae..515b, Epoch: 0, Finalized checkpoint: 0, Finalized root: 0x97e9..69fa, Peers: 1                
```

master @ e60fa13f

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
Fix a race condition during genesis event by storing attestation subnet subscriptions to be activated once the network starts.  Otherwise the validator client may request subscriptions before the network has started and throw `IllegalStateException`.

## Fixed Issue(s)
fixes #1897

### CODE REVIEW

File: networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/ActiveEth2Network.java [hunk 1]
```diff
@@ -149,21 +155,23 @@ public BeaconChainMethods getBeaconChainMethods() {
   }
 
   @Override
-  public void subscribeToAttestationSubnetId(final int subnetId) {
-    if (aggregateGossipManager == null) {
-      throw new IllegalStateException(
-          "Attestation committee can not be subscribed due to gossip manager not being initialized");
+  public synchronized void subscribeToAttestationSubnetId(final int subnetId) {
+    if (attestationGossipManager == null) {
+      System.out.println("Adding pending subscription to " + subnetId);
```
Comment (macfarla) [inline networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/ActiveEth2Network.java]: System.out

File: networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/ActiveEth2Network.java [hunk 2]
```diff
@@ -149,21 +155,23 @@ public BeaconChainMethods getBeaconChainMethods() {
...
+      pendingSubnetSubscriptions.add(subnetId);
+    } else {
+      System.out.println("Subscribing to " + subnetId);
```
Comment (macfarla) [inline networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/ActiveEth2Network.java]: System.out

**Review by cemozerr — APPROVED** [review]
