### PR TITLE
Exit cleanly if remote host is not available for voluntary exit.

### LINKED ISSUE #3272: Voluntary exit should fail gracefully when beacon node API endpoint is incorrect
When the beacon node API endpoint is incorrectly specified (note that I used the wrong port number), the voluntary exit command should fail with a helpful error message rather than a stack trace:

```
$ sudo -u teku ./build/install/teku/bin/teku voluntary-exit --epoch=24500 --validator-keys=/var/lib/teku/keys_medalla:/var/lib/teku/keys_medalla --beacon-node-api-endpoint=http://localhost:5555
Loading configuration...
java.lang.RuntimeException: Error communicating with Beacon Node API: Failed to connect to localhost/127.0.0.1:5555
        at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.executeCall(OkHttpValidatorRestApiClient.java:315)
        at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.get(OkHttpValidatorRestApiClient.java:262)
        at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.getFork(OkHttpValidatorRestApiClient.java:98)
        at tech.pegasys.teku.cli.subcommand.VoluntaryExitCommand.getFork(VoluntaryExitCommand.java:156)
        at tech.pegasys.teku.cli.subcommand.VoluntaryExitCommand.initialise(VoluntaryExitCommand.java:176)
        at tech.pegasys.teku.cli.subcommand.VoluntaryExitCommand.run(VoluntaryExitCommand.java:87)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at tech.pegasys.teku.cli.BeaconNodeCommand.parse(BeaconNodeCommand.java:229)
        at tech.pegasys.teku.Teku.main(Teku.java:32)
Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:5555
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.executeCall(OkHttpValidatorRestApiClient.java:311)
        ... 14 more
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:579)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:339)
        at java.base/java.net.Socket.connect(Socket.java:603)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        ... 30 more
```

The scenario when the remote port is open but is still incorrect should also be handled gracefully. This has affected at least one user on [the Teku Discord](https://discord.com/channels/697535391594446898/697539289042649190/778217594179026944):

```
$ sudo -u teku ./build/install/teku/bin/teku voluntary-exit --epoch=24500 --validator-keys=/var/lib/teku/keys_medalla:/var/lib/teku/keys_medalla --beacon-node-api-endpoint=http://localhost:9000
Loading configuration...
java.lang.RuntimeException: Error communicating with Beacon Node API: Unexpected status line: /multistream/1.0.0
        at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.executeCall(OkHttpValidatorRestApiClient.java:315)
        at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.get(OkHttpValidatorRestApiClient.java:262)
        at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.getFork(OkHttpValidatorRestApiClient.java:98)
        at tech.pegasys.teku.cli.subcommand.VoluntaryExitCommand.getFork(VoluntaryExitCommand.java:156)
        at tech.pegasys.teku.cli.subcommand.VoluntaryExitCommand.initialise(VoluntaryExitCommand.java:176)
        at tech.pegasys.teku.cli.subcommand.VoluntaryExitCommand.run(VoluntaryExitCommand.java:87)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at tech.pegasys.teku.cli.BeaconNodeCommand.parse(BeaconNodeCommand.java:229)
        at tech.pegasys.teku.Teku.main(Teku.java:32)
Caused by: java.net.ProtocolException: Unexpected status line: /multistream/1.0.0
        at okhttp3.internal.http.StatusLine$Companion.parse(StatusLine.kt:80)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.executeCall(OkHttpValidatorRestApiClient.java:311)
        ... 14 more
```

### PR DESCRIPTION
**Pull request by rolfyone**
Fixes #3272

Signed-off-by: Paul Harris <paul.harris@consensys.net>

## Documentation

- [X] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: teku/src/main/java/tech/pegasys/teku/cli/subcommand/VoluntaryExitCommand.java [hunk 1]
```diff
@@ -149,15 +153,31 @@ private void submitExitForValidator(final BLSPublicKey publicKey, final Integer
...
   private Optional<Bytes32> getGenesisRoot() {
-    return apiClient.getGenesis().map(response -> response.getData().getGenesisValidatorsRoot());
+    try {
+      return apiClient.getGenesis().map(response -> response.getData().getGenesisValidatorsRoot());
+    } catch (RuntimeException ex) {
+      if (Throwables.getRootCause(ex) instanceof ConnectException) {
+        SUB_COMMAND_LOG.error(getFailedToConnectMessage());
+        System.exit(1);
+      }
+    }
```
Comment (ajsutton) [inline teku/src/main/java/tech/pegasys/teku/cli/subcommand/VoluntaryExitCommand.java]: Would be good to avoid the duplication in this try catch.  Given it's a `RuntimeException` I wonder if we can just catch it higher up instead of in these private methods and handle it in one place?

Would also be kind of nice if the api client threw `UncheckedIOException` instead of `RuntimeException` so we don't have to catch something so generic.

**Review by ajsutton — APPROVED** [review]
LGTM.
