### PR TITLE
Default to burn address for fee recipient

### LINKED ISSUE #5763: Default to 0x00 fee recipient if not set
### Description
Rather than failing to produce a block, Teku should use 0x00 as the fee recipient if none is set (and continue to log very loudly).

### PR DESCRIPTION
**Pull request by rolfyone**
Rather than forcing inactivity penalties, default to the burn address if eth1address has not been specified.

fixes #5763

Signed-off-by: Paul Harris <paul.harris@consensys.net>

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by rolfyone** [comment]
looks like #5767 also fixes this so only raising draft.

**Comment by ThreeMuskets12** [comment]
Probably makes more sense for this to be an error rather than a warning like I had it, closed #5767 so this can move forward from draft to open

**Comment by rolfyone** [comment]
I was going to let someone else decide @ThreeMuskets12 but ok :) 
I think we were fixing it at the same time, thanks for the efforts anyway, we do always appreciate involvement from everyone :)

File: infrastructure/logging/src/main/java/tech/pegasys/teku/infrastructure/logging/ValidatorLogger.java [hunk 1]
```diff
@@ -184,6 +184,15 @@ public void executionPayloadPreparedUsingBeaconDefaultFeeRecipient(final UInt64
             Color.YELLOW));
   }
 
+  public void executionPayloadPreparedUsingBurnAddressForFeeRecipient(final UInt64 slot) {
+    log.error(
+        ColorConsolePrinter.print(
+            "Producing block at slot "
+                + slot
+                + ", no proposer was prepared, and no default fee recipient defined, using 0x00 BURN address",
```
Comment (ajsutton) [inline infrastructure/logging/src/main/java/tech/pegasys/teku/infrastructure/logging/ValidatorLogger.java]:
```suggestion
            "Producing block at slot "
                + slot
                + ", no proposer was prepared, and no default fee recipient defined, inclusion fees will be lost",
```

not sure how well people understand the idea of a burn address so probably slightly better to just be clear about what will be lost.

**Review by ajsutton — APPROVED** [review]
LGTM
