### PR TITLE
Handle peers limiting request block by range responses

### LINKED ISSUE #1957: Update sync algorithm to be lenient when peer fails to send all blocks
See:  https://github.com/ethereum/eth2.0-specs/blob/v0.11.1/specs/phase0/p2p-interface.md#whats-the-effect-of-empty-slots-on-the-sync-algorithm

Our current sync algorithm can incorrectly disconnect peers who return only a subset of blocks requested.  We currently assume that all blocks requested are returned (we request our next batch of blocks [assuming it starts at the first slot after our previous request](https://github.com/PegaSysEng/teku/blob/caaa8095ad8b5d8b1a7dd27d927931048f425768/sync/src/main/java/tech/pegasys/teku/sync/PeerSync.java#L133)).  This means that if a peer only responds with a subset of requested blocks, our next batch of blocks will not connect to the previous batch, and we'll end up with an [UNKNOWN_PARENT error which we handle by disconnecting the peer](https://github.com/PegaSysEng/teku/blob/caaa8095ad8b5d8b1a7dd27d927931048f425768/sync/src/main/java/tech/pegasys/teku/sync/PeerSync.java#L146-L149).

**Note**:  We can expect that honest peers will only omit blocks at then end of a range (for example, if the peer is under heavy load it may truncate its responses).  If blocks at the beginning or in the middle are omitted, the peer is misbehaving.

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
Handle peers responding with only some of the blocks in the requested range.  If the peer excessively throttles the responses (for example only returning one block) then we fail the sync against that peer.  The `SyncManager` will avoid selecting that peer as a sync target for a period and select a different target peer.  We don't disconnect the peer.

If the peer's response allows us to progress at least 50 slots in our sync, we consider it reasonable throttling and continue using the peer as our sync target.

It is possible for a peer to hit this condition when they aren't throttling excessively if there are a lot of empty blocks. e.g if we request block 1-200 and the only block in that range is at slot 2, we will assume the peer is throttling excessively.  The next peer we selected would then return no blocks and we'd then know that all blocks were empty and move on.

## Fixed Issue(s)
fixes #1957

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: sync/src/main/java/tech/pegasys/teku/sync/PeerSync.java [hunk 1]
```diff
@@ -119,18 +128,29 @@ public void stop() {
...
+              return peer.requestBlocksByRange(startSlot, count, STEP, request)
+                  .thenApply((res) -> request);
             })
         .thenCompose(
-            (readyForNextRequest) -> {
+            (blockRequest) -> {
+              final UnsignedLong nextSlot = blockRequest.getActualEndSlot().plus(UnsignedLong.ONE);
               LOG.trace(
-                  "Completed request for {} blocks starting at {} from peer {}",
+                  "Completed request for {} blocks starting at {} from peer {}. Next request starts from {}",
```
Comment (rolfyone) [inline sync/src/main/java/tech/pegasys/teku/sync/PeerSync.java]: isn't this more like `Completed request for {} blocks starting at {} from peer {}, got {} blocks. Next request starts from {}`?

File: sync/src/main/java/tech/pegasys/teku/sync/PeerSyncBlockRequest.java [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+    return blockResponseListener.onResponse(response);
+  }
+
+  public SafeFuture<Void> getReadyForNextRequest() {
+    return readyForNextRequest;
+  }
+
+  public UnsignedLong getActualEndSlot() {
+    // The peer must return at least one block if it has it, so if no blocks were returned they
+    // must all of have been empty.
```
Comment (rolfyone) [inline sync/src/main/java/tech/pegasys/teku/sync/PeerSyncBlockRequest.java:50]: `so if no blocks were returned they must have all been empty`

**Review by rolfyone — APPROVED** [review]
LGTM, a couple of minor things, and the test cases are hard to read but not deal breakers.

File: sync/src/main/java/tech/pegasys/teku/sync/PeerSyncBlockRequest.java (hunk 2 above)
Comment (ajsutton) [reply sync/src/main/java/tech/pegasys/teku/sync/PeerSyncBlockRequest.java:50]: Yes.  The spec says a peer must return at least one block if it has one in the range.  So if we get no blocks either all slots were empty or the peer is lying.  If the peer is lying the next block we get from them will have a parent root that doesn't line up or we'll get to the peers head and not have the blocks they claim to have - in either case we wind up disconnecting the peer.

File: sync/src/main/java/tech/pegasys/teku/sync/PeerSync.java (hunk 1 above)
Comment (ajsutton) [reply sync/src/main/java/tech/pegasys/teku/sync/PeerSync.java]: We don't actually count the number of blocks received - we just track what the last slot we got up to was. Reworded to talk about slots since that's technically what the range specifies.
