### PR TITLE
Do not add attestations from different forks to produced block

### LINKED ISSUE #2576: Failed to propose block due to invalid attestation signature
### Description
Seeing a [failed block production error](https://kibana-logs-ohio.ops.pegasys.tech/app/kibana#/discover/doc/8edd65d0-a9f4-11ea-9961-599210e124ad/logs-2020.08.14?id=hJFX7nMBnWi7MlZ4cD4E&_g=()) on one of our medalla nodes (dev-teku-ohio-medalla-2):

```
Failed to import proposed block for reason + FAILED_STATE_TRANSITION: tech.pegasys.teku.statetransition.events.block.ProposedBlockEvent@ebc7edb5
tech.pegasys.teku.core.StateTransitionException: tech.pegasys.teku.core.exceptions.BlockProcessingException: tech.pegasys.teku.core.exceptions.BlockProcessingException: Invalid attestation: Signature is invalid
	at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:118)
	at tech.pegasys.teku.core.ForkChoiceUtil.on_block(ForkChoiceUtil.java:228)
	at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.onBlock(ForkChoice.java:94)
	at tech.pegasys.teku.statetransition.blockimport.BlockImporter.lambda$importBlock$0(BlockImporter.java:73)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2158)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.thenApply(SafeFuture.java:320)
	at tech.pegasys.teku.statetransition.blockimport.BlockImporter.importBlock(BlockImporter.java:71)
	at tech.pegasys.teku.statetransition.blockimport.BlockImporter.onBlockProposed(BlockImporter.java:101)
	at jdk.internal.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: tech.pegasys.teku.core.exceptions.BlockProcessingException: tech.pegasys.teku.core.exceptions.BlockProcessingException: Invalid attestation: Signature is invalid
	at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:109)
	... 18 more
Caused by: tech.pegasys.teku.core.exceptions.BlockProcessingException: Invalid attestation: Signature is invalid
	at tech.pegasys.teku.core.BlockProcessorUtil.verify_attestations(BlockProcessorUtil.java:380)
	at tech.pegasys.teku.core.blockvalidator.SimpleBlockValidator.validatePreState(SimpleBlockValidator.java:78)
	at tech.pegasys.teku.core.blockvalidator.BatchBlockValidator.validatePreState(BatchBlockValidator.java:43)
	at tech.pegasys.teku.core.blockvalidator.BlockValidator.validate(BlockValidator.java:88)
	at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:106)
	... 18 more
```

### Versions (Add all that apply)
* Software version: teku/v0.12.4-dev-4855f89c/linux-x86_64/-redhatinc-openjdk64bitservervm-java-14
* Java version: 14
* OS Name & Version: Amazon Linux, Version 2
* Kernel Version: Linux 4.14.181-140.257.amzn2.x86_64 x86_64
* Cloud VM, type, size: Amazon t3.xlarge

### PR DESCRIPTION
**Pull request by cemozerr**
## PR Description
Check the attestation fork before including the attestation in a block, and if the attestation is from a different fork, (detect it by looking at the seed at the attestation epoch and attested block state vs the seed at the attestation epoch and created block pre-state) do not include the attestation.

Also, use the already generated indexed attestation during `AttestationManager.onAttestation` validations.

To improve, instead of saving the seed for each Attestation, we can also save it for each block root, but that might be a bit more complex. 

## Fixed Issue(s)

Fixes #2576

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/attestation/ValidateableAttestation.java [hunk 1]
```diff
@@ -50,15 +56,37 @@ private ValidateableAttestation(
...
+  }
+
+  public void setIndexedAttestation(IndexedAttestation indexedAttestation) {
+    this.maybeIndexedAttestation = Optional.of(indexedAttestation);
+  }
+
+  public void saveCommitteeShufflingSeed(BeaconState state) {
+    Bytes32 committeeShufflingSeed =
+        get_seed(
+            state, compute_epoch_at_slot(attestation.getData().getSlot()), DOMAIN_BEACON_ATTESTER);
```
Comment (ajsutton) [inline ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/attestation/ValidateableAttestation.java:78]: I think we should simplify this further to just store the randao rather than spending time calculating the entire shuffling seed.  If the randao matches, the shuffling seed will as well.  So just:

`get_randao_mix(state, compute_epoch_at_slot(attestation.getData().getSlot()))`

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/attestation/AggregatingAttestationPool.java [hunk 2]
```diff
@@ -126,11 +129,23 @@ public int getSize() {
         .filter(group -> isValid(stateAtBlockSlot, group.getAttestationData()))
         .flatMap(MatchingDataAttestationGroup::stream)
         .limit(attestations.getMaxSize())
+        .filter(attestation -> fromCorrectFork(stateAtBlockSlot, attestation))
```
Comment (ajsutton) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/attestation/AggregatingAttestationPool.java]: We should apply this filter to the `MatchingDataAttestationGroup` as a whole rather than to every individual attestation.  If the attestation data matches and the signature is valid (both already checked), then either the entire group can be included, or the entire group can be excluded because they're all pointing to the same block root.

And we should get the randao for the block's state prior to this stream so that we only get it once rather than for every group.

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/forkchoice/ForkChoice.java [hunk 3]
```diff
@@ -136,15 +136,18 @@ private void processHead(Optional<UInt64> nodeSlot) {
   public SafeFuture<AttestationProcessingResult> onAttestation(
       final ValidateableAttestation attestation) {
     return recentChainData
-        .retrieveCheckpointState(attestation.getData().getTarget())
+        .retrieveBlockState(attestation.getData().getBeacon_block_root())
```
Comment (ajsutton) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/forkchoice/ForkChoice.java]: This is going to destroy us performance-wise.   We will suddenly be missing checkpoint state caches a whole lot more.

Given that the target checkpoint must be for the epoch matching the slot we should continue using the state for the target state.  ie from `ForkChoiceUtil.validateOnAttestation`:
```
    if (!target.getEpoch().equals(compute_epoch_at_slot(attestation.getData().getSlot()))) {
      return AttestationProcessingResult.invalid("Attestation slot must be within specified epoch");
    }
```

Remember that if the randao in the state we validate against was different to the one used when creating the attestation, the signature would be invalid because the committees wouldn't match up.  So we can safely validate against any state from one epoch prior to the attestation's slot.

File: ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/attestation/ValidateableAttestation.java (hunk 1 above)
Comment (ajsutton) [reply ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/attestation/ValidateableAttestation.java:78]: Sorry, this is wrong - we need to do the same randaoIndex calculation as in `get_seed` so worth extracting that bit of `get_seed` as a method we can reuse but it effectively becomes:
```suggestion
    UInt64 epoch = compute_epoch_at_slot(attestation.getData().getSlot());
    UInt64 randaoIndex = epoch.plus(EPOCHS_PER_HISTORICAL_VECTOR - MIN_SEED_LOOKAHEAD - 1);
    return get_randao_mix(state, randaoIndex);
```

Comment (ajsutton) [reply ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/attestation/ValidateableAttestation.java:78]: Following conversation with Proto, sticking with seed probably does make sense - just make sure that we calculate the seed for the block only once, not once per attestation or group.

Comment (cemozerr) [reply ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/attestation/ValidateableAttestation.java:78]: Makes sense to me.

Comment (cemozerr) [reply ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/attestation/ValidateableAttestation.java:78]: Done.

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/attestation/AggregatingAttestationPool.java (hunk 2 above)
Comment (cemozerr) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/attestation/AggregatingAttestationPool.java]: The slot of the attestation data is important for the randao mix, so we have to get it for every group. Because different attestation groups might be from different epochs. 

Maybe if only attestation groups that point to the last two epochs are valid, we could get the randao mixes for those two epochs, and check if any groups randao mixes match those.

Comment (cemozerr) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/attestation/AggregatingAttestationPool.java]: Applying the filter to the Group as a whole makes sense to me.

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/forkchoice/ForkChoice.java (hunk 3 above)
Comment (cemozerr) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/forkchoice/ForkChoice.java]: I had forgotten the rule above, i.e. `target.getEpoch().equals(compute_epoch_at_slot(attestation.getData().getSlot())`, in light of that, what you say makes total sense.

File: ethereum/core/src/main/java/tech/pegasys/teku/core/ForkChoiceUtil.java [hunk 4]
```diff
@@ -399,6 +402,11 @@ private static AttestationProcessingResult indexAndValidateAttestation(
         .ifSuccessful(
             () -> {
               attestation.setIndexedAttestation(indexedAttestation);
+
+              if (attestation.getMaybeIndexedAttestation().isEmpty()) {
+                attestation.saveRandaoMix(targetState);
+              }
```
Comment (ajsutton) [inline ethereum/core/src/main/java/tech/pegasys/teku/core/ForkChoiceUtil.java]: It may be cleaner to just call `attestation.saveRandoMix` here and have the method do nothing if it already has a randaoMix saved.  Otherwise it takes a bit of reasoning to understand why the absence of an indexed attestation means we need to save randao mix.

File: ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/attestation/ValidateableAttestation.java [hunk 5]
```diff
@@ -50,15 +57,38 @@ private ValidateableAttestation(
...
   public IndexedAttestation getIndexedAttestation() {
     return maybeIndexedAttestation.orElseThrow(
         () ->
             new UnsupportedOperationException(
                 "ValidateableAttestation does not have an IndexedAttestation yet."));
   }
 
-  public void setIndexedAttestation(IndexedAttestation maybeIndexedAttestation) {
-    this.maybeIndexedAttestation = Optional.of(maybeIndexedAttestation);
+  public Optional<Bytes32> getMaybeRandaoMix() {
```
Comment (ajsutton) [inline ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/attestation/ValidateableAttestation.java]: I'm not really a fan of the `Maybe` in these method names.  I'd be tempted to just move to having a single `getRandaoMix` which returns an optional and do the `orElseThrow` in the caller if desired (and same for `getIndexedAttestation`).

File: ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/attestation/ValidateableAttestation.java [hunk 6]
```diff
@@ -50,15 +57,38 @@ private ValidateableAttestation(
...
+  public void setIndexedAttestation(IndexedAttestation indexedAttestation) {
+    this.maybeIndexedAttestation = Optional.of(indexedAttestation);
+  }
+
+  public void saveRandaoMix(BeaconState state) {
+    UInt64 randaoIndex =
+        compute_epoch_at_slot(attestation.getData().getSlot())
+            .plus(EPOCHS_PER_HISTORICAL_VECTOR - MIN_SEED_LOOKAHEAD - 1);
+    Bytes32 mix = get_randao_mix(state, randaoIndex);
+    this.maybeRandaoMix = Optional.of(mix);
```
Comment (ajsutton) [inline ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/attestation/ValidateableAttestation.java]: Didn't we circle back round to storing the seed? Sorry, I know I said randao mix but I was overthinking the performance implications I think.  As long as we don't have to calculate a seed for every attestation when producing blocks it will be fine.

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/attestation/AttestationForkChecker.java [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+import static tech.pegasys.teku.util.config.Constants.EPOCHS_PER_HISTORICAL_VECTOR;
+import static tech.pegasys.teku.util.config.Constants.MIN_SEED_LOOKAHEAD;
+
+import java.util.HashSet;
+import java.util.Set;
+import org.apache.tuweni.bytes.Bytes32;
+import tech.pegasys.teku.datastructures.state.BeaconState;
+import tech.pegasys.teku.infrastructure.unsigned.UInt64;
+
+public class AttestationForkChecker {
```
Comment (ajsutton) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/attestation/AttestationForkChecker.java:26]: Good idea to make this its own class.

**Review by ajsutton — APPROVED** [review]
LGTM. It will work as-is but my understanding is that I was wrong to push you towards storing the randao mix and storing the seed is more easily understandable and not a performance concern.  Probably worth undoing my damage and going back to using seed unless there's some reason not too.

File: ethereum/core/src/main/java/tech/pegasys/teku/core/ForkChoiceUtil.java (hunk 4 above)
Comment (cemozerr) [reply ethereum/core/src/main/java/tech/pegasys/teku/core/ForkChoiceUtil.java]: My bad, I was actually trying to call `attestation.getMaybeRandaoMix().isEmpty()`

Comment (cemozerr) [reply ethereum/core/src/main/java/tech/pegasys/teku/core/ForkChoiceUtil.java]: But your suggestion below makes sense. I'll apply that one.

Comment (cemozerr) [reply ethereum/core/src/main/java/tech/pegasys/teku/core/ForkChoiceUtil.java]: Done.

File: ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/attestation/ValidateableAttestation.java (hunk 5 above)
Comment (cemozerr) [reply ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/attestation/ValidateableAttestation.java]: Done.

File: ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/attestation/ValidateableAttestation.java (hunk 6 above)
Comment (cemozerr) [reply ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/attestation/ValidateableAttestation.java]: Done.
