### PR TITLE
return error when contributions are invalid

### LINKED ISSUE #4138: No error returned when invalid signed contribution and proof sent to REST API
if I send a signed contribution and proof that is invalid I get an error in the logs but the API endpoint returns 200.  The specific error in the logs is:

```
2021-07-08 17:30:25.445+01:00 | beaconchain-async-2 | TRACE | SignedContributionAndProofValidator | Rejecting proof because batch signature check failed
```

### PR DESCRIPTION
**Pull request by rolfyone**
Previously when a contribution and proof was rejected, the error reason was only in trace. Now the errors should be returned, in a semi-colon separated list if there are multiple.

Ignored entries will still not result in an error being returned to the user.

fixes #4138

Signed-off-by: Paul Harris <paul.harris@consensys.net>

## Documentation

- [X] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/synccommittee/SignedContributionAndProofValidator.java [hunk 1]
```diff
@@ -80,10 +80,13 @@ public SignedContributionAndProofValidator(
...
-          "Rejecting proof because the fork active at slot {} does not support sync committees",
-          contribution.getSlot());
-      return SafeFuture.completedFuture(REJECT);
+      final String failureReason =
+          String.format(
+              "Rejecting proof because the fork active at slot %s does not support sync committees",
+              contribution.getSlot());
+      LOG.trace(failureReason);
+      return SafeFuture.completedFuture(
+          InternalValidationResult.create(ValidationResultCode.REJECT, failureReason));
```
Comment (ajsutton) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/synccommittee/SignedContributionAndProofValidator.java]: I wonder if we should extract a private method for this so it becomes something like:

```
return failureResult("Rejecting proof blah blah %s", contribution.getSlot());
```

The private method would take `String message, String... args` and do the `String.format` call for you.

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/validation/InternalValidationResult.java [hunk 2]
```diff
@@ -23,8 +23,11 @@
       InternalValidationResult.create(ValidationResultCode.ACCEPT);
   public static InternalValidationResult IGNORE =
       InternalValidationResult.create(ValidationResultCode.IGNORE);
+
+  @Deprecated
   public static InternalValidationResult REJECT =
       InternalValidationResult.create(ValidationResultCode.REJECT);
```
Comment (ajsutton) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/validation/InternalValidationResult.java]: I'd suggest inlining this rather than deprecating.  We have so much stuff deprecated now that it's not a particularly helpful signal so may as well just clean it up even if not everywhere is passing a message yet.

Comment (ajsutton) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/validation/InternalValidationResult.java]: Or actually I'd provide a generic error message here, then inline it.  That way everywhere that calls it will wind up with a generic "Failed validation" error message instead of an empty optional which is obviously unhelpful but doesn't wind up being ignored because it's an empty optional like happened in this case.

**Review by ajsutton — APPROVED** [review]
LGTM.
