### PR TITLE
Fix unhandled exception on stream abort

### LINKED ISSUE #3028: Sync Stalling
### Description
Three times in a row since updating this afternoon my Medalla sync has stalled.  At INFO level there's no sign of anything going wrong, it just stops progressing after an hour or two.  Still has peers, but seems to have stopped requesting new blocks entirely.  I tried again with debug level enabled for the `tech.pegasys.teku.sync` package and got the exception below:

```
 slot 435936 by replaying 20 blocks. Took 2252ms","throwable":""}
{"timestamp":"2020-10-20T06:36:48,547","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 552483, Head slot: 435980, Connected peers: 74","throwable":""}
{"timestamp":"2020-10-20T06:36:56,389","level":"DEBUG","thread":"forkchoice-0","class":"PeerSync","message":"Request 200 blocks starting at 436012 from peer 16Uiu2HAkyjDgW6orCnb1RLkm21Voho617U8ay89tZGzUQcx8fbjL","throwable
":""}
{"timestamp":"2020-10-20T06:36:56,806","level":"WARN","thread":"nioEventLoopGroup-3-2","class":"DefaultChannelPipeline","message":"An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usuall
y means the last handler in the pipeline did not handle the exception.","throwable":" io.netty.channel.ChannelPipelineException: tech.pegasys.teku.networking.p2p.libp2p.rpc.RpcHandler$Controller.handlerRemoved() has thrown
 an exception.\n\tat io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:640)\n\tat io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:876)\n\tat io.netty.ch
annel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:844)\n\tat io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:836)\n\tat io.netty.channel.DefaultChannelPipeline.access$700(Defaul
tChannelPipeline.java:46)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1392)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(Abstr
actChannelHandlerContext.java:198)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:184)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelUnregistere
d(DefaultChannelPipeline.java:821)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:826)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)\n\ta
t io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)\n\tat io.netty.util.concurrent.SingleThreadEventExecut
or$4.run(SingleThreadEventExecutor.java:989)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat
 java.base/java.lang.Thread.run(Thread.java:832)\nCaused by: java.lang.IllegalStateException: Trying to reuse disposable LengthPrefixedPayloadDecoder\n\tat tech.pegasys.teku.networking.eth2.rpc.core.encodings.LengthPrefixe
dPayloadDecoder.complete(LengthPrefixedPayloadDecoder.java:108)\n\tat tech.pegasys.teku.networking.eth2.rpc.core.RpcResponseDecoder.complete(RpcResponseDecoder.java:115)\n\tat tech.pegasys.teku.networking.eth2.rpc.core.Rpc
ResponseDecoder.close(RpcResponseDecoder.java:105)\n\tat tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.abortRequest(Eth2OutgoingRequestHandler.java:222)\n\tat tech.pegasys.teku.networking.eth2.rpc.c
ore.Eth2OutgoingRequestHandler.abortRequest(Eth2OutgoingRequestHandler.java:212)\n\tat tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.readComplete(Eth2OutgoingRequestHandler.java:159)\n\tat tech.pega
sys.teku.networking.p2p.libp2p.rpc.RpcHandler$Controller.onRemoteWriteClosed(RpcHandler.java:191)\n\tat tech.pegasys.teku.networking.p2p.libp2p.rpc.RpcHandler$Controller.onChannelClosed(RpcHandler.java:197)\n\tat tech.pega
sys.teku.networking.p2p.libp2p.rpc.RpcHandler$Controller.handlerRemoved(RpcHandler.java:178)\n\tat io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:946)\n\tat io.netty.ch
annel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)\n\t... 16 more\n"}
{"timestamp":"2020-10-20T06:36:57,148","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 552484, Head slot: 436011, Connected peers: 73","throwable":""}
{"timestamp":"2020-10-20T06:37:09,112","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 552485, Head slot: 436013, Connected peers: 74","throwable":""}
{"timestamp":"2020-10-20T06:37:21,170","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 552486, Head slot: 436013, Connected peers: 73","throwable":""}
{"timestamp":"2020-10-20T06:37:33,123","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 552487, Head slot: 436013, Connected peers: 74","throwable":""}
{"timestamp":"2020-10-20T06:37:45,108","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 552488, Head slot: 436013, Connected peers: 74","throwable":""}
{"timestamp":"2020-10-20T06:37:57,105","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 552489, Head slot: 436013, Connected peers: 74","throwable":""}
{"timestamp":"2020-10-20T06:38:09,365","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 552490, Head slot: 436013, Connected peers: 73","throwable":""}
{"timestamp":"2020-10-20T06:38:21,105","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 552491, Head slot: 436013, Connected peers: 73","throwable":""}
{"timestamp":"2020-10-20T06:38:22,958","level":"WARN","thread":"p2p-async-0","class":"LoggingWeakSubjectivityViolationPolicy","message":"The latest finalized checkpoint at epoch 13623 (67417 active validators) fell outside
 of the weak subjectivity period after epoch 14721, which is prior to the current epoch 17265.","throwable":""}
{"timestamp":"2020-10-20T06:38:22,958","level":"WARN","thread":"p2p-async-0","class":"teku-status-log","message":"The latest finalized checkpoint at epoch 13623 is outside of the weak subjectivity period.  Please supply a
recent weak subjectivity checkpoint using --ws-checkpoint=<BLOCK_ROOT>:<EPOCH>.","throwable":""}
{"timestamp":"2020-10-20T06:38:33,234","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 552492, Head slot: 436013, Connected peers: 72","throwable":""}
{"timestamp":"2020-10-20T06:38:45,113","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 552493, Head slot: 436013, Connected peers: 72","throwable":""}
```

### PR DESCRIPTION
**Pull request by Nashatyrev**
## PR Description

Fixes the regression introduced in #3001 

A remote party may abruptly close a truncated stream. The `Eth2OutgoingRequestHandler.readComplete()` generates an error in this case which causes `abortRequest()` call. `RpcResponseDecoder.close()` throws unexpected `IllegalStateException` which is not caught and the `responseStream` remains uncompleted. 

## Fixed Issue(s)

Fix #3028 

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/core/encodings/compression/snappy/SnappyFramedCompressor.java [hunk 1]
```diff
@@ -103,16 +94,24 @@ public SnappyFramedDecompressor(int uncompressedPayloadSize) {
 
     @Override
     public void complete() throws CompressionException {
-      if (broken) throw new CompressionException("Compressed stream is broken");
-      if (disposed) throw new DisposedDecompressorException();
-      disposed = true;
-      boolean unreturnedFrames = !decodedSnappyFrames.isEmpty();
+      try {
+        if (broken) throw new CompressionException("Compressed stream is broken");
+        if (disposed) throw new DisposedDecompressorException();
```
Comment (mbaxter) [inline networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/core/encodings/compression/snappy/SnappyFramedCompressor.java]: (nit)
```suggestion
        if (broken) {
            throw new CompressionException("Compressed stream is broken");
        }
        if (disposed) {
            throw new DisposedDecompressorException();
        }
```

**Review by mbaxter — APPROVED** [review]
LGTM
