### PR TITLE
Add data column sidecars by root handler test + fix bugs

### LINKED ISSUE #9615: [PeerDAS] Serve DataColumnSidecarsByRoot for finalized epochs
(We need to double-check if we are already doing this)

Reference: https://github.com/ethereum/consensus-specs/pull/4394

### PR DESCRIPTION
**Pull request by zilm13**
## PR Description
Also added tests +fixed some bugs found during test implementation

## Fixed Issue(s)

Fixes #9615 

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/DataColumnSidecarsByRootMessageHandler.java [hunk 1]
```diff
@@ -90,29 +91,45 @@ public DataColumnSidecarsByRootMessageHandler(
...
+    return Optional.empty();
+  }
+
   @Override
   public void onIncomingMessage(
       final String protocolId,
       final Eth2Peer peer,
       final DataColumnSidecarsByRootRequestMessage message,
       final ResponseCallback<DataColumnSidecar> responseCallback) {
+    final int requestDataColumnSidecars = calculateRequestDataColumnSidecars(message);
```
Comment (mehdi-aouadi) [inline networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/DataColumnSidecarsByRootMessageHandler.java]: I'd rename it to `requestedDataColumnSidecarsCount`

**Review by mehdi-aouadi — APPROVED** [review]
Some nits in the end

File: networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/DataColumnSidecarsByRootMessageHandler.java [hunk 2]
```diff
@@ -196,12 +211,11 @@ private SafeFuture<Optional<DataColumnSidecar>> getNonCanonicalDataColumnSidecar
             });
   }
 
-  private UInt64 getFinalizedEpoch() {
-    return combinedChainDataClient
-        .getFinalizedBlock()
-        .map(SignedBeaconBlock::getSlot)
-        .map(spec::computeEpochAtSlot)
-        .orElse(UInt64.ZERO);
+  private int getMaxRequestDataColumnSidecars() {
```
Comment (mehdi-aouadi) [inline networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/DataColumnSidecarsByRootMessageHandler.java]: We'd better inject the `SpecConfigFulu` and call `getMaxRequestDataColumnSidecars` like we do in the by range method

File: networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/DataColumnSidecarsByRootMessageHandler.java [hunk 3]
```diff
@@ -242,6 +251,16 @@ private SafeFuture<Void> validateMinimumRequestEpoch(
             });
   }
 
+  private int calculateRequestDataColumnSidecars(
+      final DataColumnSidecarsByRootRequestMessage message) {
+    return message.stream()
+        .reduce(
+            0,
+            (current, dataColumnsByRootIdentifier) ->
+                current + dataColumnsByRootIdentifier.getColumns().size(),
```
Comment (mehdi-aouadi) [inline networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/DataColumnSidecarsByRootMessageHandler.java]: I'm wondering if we should handle any overflow here. We've added an explicit check in the blob sidecars by range method which was reported as a DOS attack vector

**Review by mehdi-aouadi — CHANGES_REQUESTED** [review]

File: networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/DataColumnSidecarsByRootMessageHandler.java (hunk 3 above)
Comment (zilm13) [reply networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/DataColumnSidecarsByRootMessageHandler.java]: Nice catch. I've checkd it carefully, it's not possible to overflow it, I've added a test claryfing it, see last test here https://github.com/Consensys/teku/pull/9629/commits/84c093ab0ab6d5b11c540844a63c25ff6becdf43

**Comment by zilm13** [comment]
@mehdi-aouadi I've addressed your feedback

**Review by mehdi-aouadi — APPROVED** [review]
LGTM
