### PR TITLE
Ignore aggregate if falling behind

### LINKED ISSUE #9187: [HOLESKY PECTRA] noisy stacktrace message
```
{"@timestamp":"2025-03-02T02:37:46,008","level":"WARN","thread":"p2p-async-4","class":"Eth2TopicHandler","message":"Encountered exception while processing message for topic /eth2/019e21ad/beacon_aggregate_and_proof/ssz_snappy","throwable":" java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Committee information must be derived from a state no older than the previous epoch. State at slot 3748341 is older than cutoff slot 3748352\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)\n\tat java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1194)\n\tat java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.thenCompose(SafeFuture.java:542)\n\tat tech.pegasys.teku.statetransition.validation.AttestationValidator.singleOrAggregateAttestationChecks(AttestationValidator.java:145)\n\tat tech.pegasys.teku.statetransition.validation.AggregateAttestationValidator.singleOrAggregateAttestationChecks(AggregateAttestationValidator.java:270)\n\tat tech.pegasys.teku.statetransition.validation.AggregateAttestationValidator.verifyAggregate(AggregateAttestationValidator.java:126)\n\tat tech.pegasys.teku.statetransition.validation.AggregateAttestationValidator.validate(AggregateAttestationValidator.java:100)\n\tat tech.pegasys.teku.statetransition.attestation.AttestationManager.addAggregate(AttestationManager.java:152)\n\tat tech.pegasys.teku.networking.eth2.gossip.AggregateGossipManager.lambda$new$0(AggregateGossipManager.java:48)\n\tat tech.pegasys.teku.networking.eth2.gossip.topics.topichandlers.Eth2TopicHandler.lambda$handleMessage$2(Eth2TopicHandler.java:129)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:72)\n\tat tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: java.lang.IllegalArgumentException: Committee information must be derived from a state no older than the previous epoch. State at slot 3748341 is older than cutoff slot 3748352\n\tat com.google.common.base.Preconditions.checkArgument(Preconditions.java:448)\n\tat tech.pegasys.teku.spec.logic.common.helpers.BeaconStateAccessors.validateStateForCommitteeQuery(BeaconStateAccessors.java:340)\n\tat tech.pegasys.teku.spec.logic.common.helpers.BeaconStateAccessors.getBeaconCommittee(BeaconStateAccessors.java:294)\n\tat tech.pegasys.teku.spec.Spec.getBeaconCommittee(Spec.java:867)\n\tat tech.pegasys.teku.statetransition.validation.AttestationValidator.lambda$singleOrAggregateAttestationChecks$3(AttestationValidator.java:178)\n\tat java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)\n\t... 14 more\n"}
```
doesnt appear to be value in the stacktrace here, and when the network isnt healthy we get a lot. can we clean this up?

### PR DESCRIPTION
**Pull request by rolfyone**
Currently if we're falling behind and receive an aggregate we attempt to validate it but our state is too old in some circumstances.

We can't validate this aggregate, but currently we're rejecting it, which is worse than ignoring it for gossip rules, so we're better off just ignoring it.

fixes #9187

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/validation/AttestationValidator.java [hunk 1]
```diff
@@ -174,14 +176,18 @@ SafeFuture<InternalValidationResultWithState> singleOrAggregateAttestationChecks
 
               if (!attestation.isSingleAttestation()) {
                 // [REJECT] The number of aggregation bits matches the committee size
```
Comment (gfukushima) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/validation/AttestationValidator.java:177]: I'd take the opportunity here to move the comment to the `if` check so it continues to matche what the code is doing.

Comment (rolfyone) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/validation/AttestationValidator.java:177]: but this whole block only does that... i was just making it not go boom... not sure it'll be v. clear if its down 2 levels?

**Review by gfukushima — APPROVED** [review]
