### PR TITLE
Deferred dynamic blinded-unblinded block production

### LINKED ISSUE #7881: /eth/v3/validator/blocks/{slot} returning blinded block when built locally
### Description

A call to `/eth/v3/validator/blocks/{slot}` on devnet-12 is returning a blinded block even when using the local execution engine.

The specific endpoint called was:

```
/eth/v3/validator/blocks/326383?randao_reveal=0x97e375d4cdd3943d5eb42d26b08efcd34e2700110d6adf97b04593908e292a26acb215a14bd1b24a7edf05a4c8f8bf7a0ece69394bc25379582b669735ff1f6bfd12ea661a4b0d832bc348a05faaee9b236fbd095fa3ed5391e82a04175bddbe&graffiti=0x417474657374616e742f566f7563680000000000000000000000000000000000
```

and the data returned was:

```
{"version":"deneb","execution_payload_blinded":true,"execution_payload_value":"84000000000000","consensus_block_value":"2448542000000000","data":{"slot":"326383","proposer_index":"2789","parent_root":"0x09aa548b87a292c2ee9acd5d819ac9c8f90ab44f2d40278aa5b1d7cfe04caad3","state_root":"0xe2e9eb68c9524b283b906c716ffba6f9a7f313901141901c98d9cee2df0b4f22","body":{"randao_reveal":"0x97e375d4cdd3943d5eb42d26b08efcd34e2700110d6adf97b04593908e292a26acb215a14bd1b24a7edf05a4c8f8bf7a0ece69394bc25379582b669735ff1f6bfd12ea661a4b0d832bc348a05faaee9b236fbd095fa3ed5391e82a04175bddbe","eth1_data":{"deposit_root":"0xe5700ac7bf08aa474241beaab310610d5944343c12b12b9710fbce881d30f157","deposit_count":"850","block_hash":"0x66f5796139b34c313ab45843f45dae4367c2ba1a83ed81ddd21fcd584457433a"},"graffiti":"0x417474657374616e742f566f7563680000000000000000000000000000000000","proposer_slashings":[],"attester_slashings":[],"attestations":[{"aggregation_bits":"0xfffff5fbbffffffeffeffffff77e","data":{"slot":"326382","index":"0","beacon_block_root":"0x09aa548b87a292c2ee9acd5d819ac9c8f90ab44f2d40278aa5b1d7cfe04caad3","source":{"epoch":"10198","root":"0x8b897c93f370edfab5211ae25e18989d977d4c84831af6ba7e2549047326c458"},"target":{"epoch":"10199","root":"0xaf2ba49648846c9619da933e2e4631226bbd40b76b1f3a282995402b0a48f823"}},"signature":"0x89d761e8d5d0a733eebb11b8d2ff25d4ddc61d104e83915d6a04f462f18ab5cfd29b0919802fd9e046b3fa55c7698b2718d62b28da5e37aeac99a3472552b0e84aec6b5df84b4583d10311d1c46320b5c80984a1b7d88e9388320cdcae6e6bc7"}],"deposits":[],"voluntary_exits":[],"sync_aggregate":{"sync_committee_bits":"0xfdfbffe9f77dffbffdefdd75ffeeffddbff7717f7fffffde7ef7fefd7fff7feffffafbfffffffffdfdffdfffbdb7fffffdfeffffbfffffdfb36bfffffe9ffeff","sync_committee_signature":"0xae1f1ab7813410ac8d5e396107d81b29e09255986be2fd103b68ecc6d1382b1106ff45227a9961e87c8ecd785b728dcb16ed029ce35d63bcba6cf08942a4502a17ba061896349096796598eed6216bd6a1cb2760e1ca6f4482fef875f6aa9102"},"execution_payload_header":{"parent_hash":"0x7b593fd14b592752d23f49cf8f6f8a0d9105fd91b7a3d8c7452cdf741f498395","fee_recipient":"0xf4e8263979a89dc357d7f9f79533febc7f3e287b","state_root":"0xbe2973e213251edc8c0aafd0b2d06487d80aeb644e92a77812041db0a26a4a5e","receipts_root":"0x10457e39b8c68ced2071538b4c7034fe68f9c666187fd6b2d6ddcc21149f0d10","logs_bloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","prev_randao":"0xcff5d48b6f99b957ea23e05d6423986795e032b8dd5655760dd7bfd81be5ce88","block_number":"310806","gas_limit":"30000000","gas_used":"42000","timestamp":"1705179396","extra_data":"0xd883010d0a846765746888676f312e32312e35856c696e7578","base_fee_per_gas":"9","block_hash":"0x2b86e660e082d22c8f6ccfaf4426d42a77b5d657ae7a7cf1578dee863f8013f6","transactions_root":"0x436df0931151a904326940fd7d22ee9f1d04e7c68b2967145948953c0ed5f7b6","withdrawals_root":"0xfdfd6478c5ec785b97ca5ef6d09e419455b13709acdf534f0960e3ab9be635d5","blob_gas_used":"262144","excess_blob_gas":"131072"},"bls_to_execution_changes":[],"blob_kzg_commitments":["0x8feedb4eb3d5ce4828293092abec3fef7d435296947978e14155a559413fc2abec5e3efe7dff39f4afd663b68d31333b","0x8a190e2961b87db7a6ec9e732edfc8e2added420af4f6eb98171a99486cd8fd5e02a14bd0930a351284094707b208698"]}}}
```

Note that this includes `"execution_payload_blinded":true`.  However, looking at the logs this block was built with a local payload:

```
2024-01-13 20:56:36.045 INFO  - Creating unsigned block for slot 326383
2024-01-13 20:56:36.086 ERROR - Unable to obtain a valid bid from builder. Falling back to local execution engine.
java.util.concurrent.CompletionException: tech.pegasys.teku.ethereum.executionclient.response.InvalidRemoteResponseException: Invalid remote response from the builder: {"code":500,"message":"Failed to obtain bid"}
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:146) ~[teku-infrastructure-async-24.1.0.jar:24.1.0]
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:146) ~[teku-infrastructure-async-24.1.0.jar:24.1.0]
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:619) ~[teku-infrastructure-async-24.1.0.jar:24.1.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:31) ~[teku-infrastructure-async-24.1.0.jar:24.1.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:141) ~[teku-infrastructure-async-24.1.0.jar:24.1.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$34(SafeFuture.java:423) ~[teku-infrastructure-async-24.1.0.jar:24.1.0]
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at tech.pegasys.teku.ethereum.executionclient.rest.OkHttpRestClient.handleFailure(OkHttpRestClient.java:175) ~[teku-ethereum-executionclient-24.1.0.jar:24.1.0]
at tech.pegasys.teku.ethereum.executionclient.rest.OkHttpRestClient$2.onResponse(OkHttpRestClient.java:151) ~[teku-ethereum-executionclient-24.1.0.jar:24.1.0]
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.12.0.jar:?]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: tech.pegasys.teku.ethereum.executionclient.response.InvalidRemoteResponseException: Invalid remote response from the builder: {"code":500,"message":"Failed to obtain bid"}
at tech.pegasys.teku.ethereum.executionclient.response.ResponseUnwrapper.unwrapResponseOrThrow(ResponseUnwrapper.java:39) ~[teku-ethereum-executionclient-24.1.0.jar:24.1.0]
at tech.pegasys.teku.ethereum.executionclient.response.ResponseUnwrapper.unwrapBuilderResponseOrThrow(ResponseUnwrapper.java:26) ~[teku-ethereum-executionclient-24.1.0.jar:24.1.0]
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
... 25 more
2024-01-13 20:56:40.000 INFO  - Slot Event  *** Slot: 326383, Block: d755e673827919b6de2a8c92ca6184a8d7ec37221e31b3c0a897d7275116715b, Justified: 10198, Finalized: 10197, Peers: 53
```

As per the spec at https://ethereum.github.io/beacon-APIs/#/ValidatorRequiredApi/produceBlockV3 "The beacon node must return an unblinded block if it obtains the execution payload from its paired execution node."

### Steps to Reproduce (Bug)

Call the `v3` blocks endpoint as per above.

**Expected behavior:**

An unblinded block should be returned, as per the spec.

**Actual behavior:**

A blinded block should be returned.

**Frequency:**

Every time for devnet 12 (on deneb).

### Versions (Add all that apply)
```
teku/v24.1.0/linux-x86_64/-privatebuild-openjdk64bitservervm-java-17
```

### LINKED ISSUE #7889: Make the block production automatically choose blinded or unblinded blocks
once fixed we can close #7881

### PR DESCRIPTION
**Pull request by tbenr**
This PR makes async the block creation selector created by `BlockOperationSelectorFacotry`.
This means that it can support async flow when providing values to the BlockBuilder. This feature enables deferring the decision to pass full payload or payloadHeader after the interaction with the builder.
This way we can completely remove `SafeFuture`(s) from BlockBuilders so they are now fully synchronous.

fixes #7889
fixes #7881

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: data/serializer/src/main/java/tech/pegasys/teku/api/schema/BeaconBlockBody.java [hunk 1]
```diff
@@ -80,39 +81,44 @@ public BeaconBlockBody(
...
-                      deposits.stream()
-                          .map(Deposit::asInternalDeposit)
-                          .collect(schema.getDepositsSchema().collector()))
-                  .voluntaryExits(
-                      voluntary_exits.stream()
-                          .map(SignedVoluntaryExit::asInternalSignedVoluntaryExit)
-                          .collect(schema.getVoluntaryExitsSchema().collector()));
-            })
+            builder ->
+                SafeFuture.allOf(
```
Comment (tbenr) [inline data/serializer/src/main/java/tech/pegasys/teku/api/schema/BeaconBlockBody.java:90]: The idea here is that we can apply builders in parallel, but thinking twice here the usage is actually not async and all futures are immediately completed because the data is already here. So we could switch to a chained `apply` if it is more readable (which was my initial implementation)

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/datastructures/blocks/blockbody/BeaconBlockBodySchema.java [hunk 2]
```diff
@@ -32,7 +32,7 @@
 
 public interface BeaconBlockBodySchema<T extends BeaconBlockBody> extends SszContainerSchema<T> {
   SafeFuture<? extends BeaconBlockBody> createBlockBody(
-      Consumer<BeaconBlockBodyBuilder> bodyBuilder);
+      final Function<BeaconBlockBodyBuilder, SafeFuture<Void>> bodyBuilder);
```
Comment (zilm13) [inline ethereum/spec/src/main/java/tech/pegasys/teku/spec/datastructures/blocks/blockbody/BeaconBlockBodySchema.java]: final not needed here

File: beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/BlockOperationSelectorFactory.java [hunk 3]
```diff
@@ -172,174 +166,197 @@ public Consumer<BeaconBlockBodyBuilder> createSelector(
...
-      final Bytes32 parentRoot,
       final BeaconState blockSlotState,
       final BlockProductionPerformance blockProductionPerformance) {
-    final SafeFuture<Optional<ExecutionPayloadContext>> executionPayloadContextFuture =
-        forkChoiceNotifier.getPayloadId(parentRoot, blockSlotState.getSlot());
+
+    // if blinded flow is explicitly requested, we should try to use it
+    // otherwise, we should use it only if we have a validator registration
+    final boolean shouldTryBuilderFlow =
+        requestedBlinded.orElse(true)
```
Comment (zilm13) [inline beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/BlockOperationSelectorFactory.java]: it should be `orElse(false)` if I read it correct. Also I'd split it to 3 vars for better readability. Also the name `shouldTryBuilderFlow` is a bit confusing, as it could be true when validator registration is not present

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/datastructures/blocks/blockbody/versions/phase0/BeaconBlockBodyBuilderPhase0.java [hunk 4]
```diff
@@ -110,14 +109,14 @@ public BeaconBlockBodyBuilder syncAggregate(final SyncAggregate syncAggregate) {
   }
 
   @Override
-  public BeaconBlockBodyBuilder executionPayload(SafeFuture<ExecutionPayload> executionPayload) {
+  public BeaconBlockBodyBuilder executionPayload(ExecutionPayload executionPayload) {
```
Comment (zilm13) [inline ethereum/spec/src/main/java/tech/pegasys/teku/spec/datastructures/blocks/blockbody/versions/phase0/BeaconBlockBodyBuilderPhase0.java]: final as you are here

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/datastructures/blocks/blockbody/versions/phase0/BeaconBlockBodyBuilderPhase0.java [hunk 5]
```diff
@@ -110,14 +109,14 @@ public BeaconBlockBodyBuilder syncAggregate(final SyncAggregate syncAggregate) {
...
     // No execution payload in phase 0
     return this;
   }
 
   @Override
   public BeaconBlockBodyBuilder executionPayloadHeader(
```
Comment (zilm13) [inline ethereum/spec/src/main/java/tech/pegasys/teku/spec/datastructures/blocks/blockbody/versions/phase0/BeaconBlockBodyBuilderPhase0.java:118]: final as you are here

File: beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/BlockOperationSelectorFactory.java [hunk 6]
```diff
@@ -172,174 +166,197 @@ public Consumer<BeaconBlockBodyBuilder> createSelector(
...
+            || executionPayloadContext
+                .map(ExecutionPayloadContext::isValidatorRegistrationPresent)
+                .orElse(false);
+
+    // we should try to return unblinded content only if we try the builder flow with no explicit
+    // request
+    final boolean setUnblindedContentIfPossible =
```
Comment (zilm13) [inline beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/BlockOperationSelectorFactory.java]: how about `setLocalPayloadIfBuilderFailed`? Current name is too abstract, I think we'd better use name more tied with domain. Also comment could describe why and in what case this variable is used

File: beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/BlockOperationSelectorFactory.java [hunk 7]
```diff
@@ -172,174 +166,197 @@ public Consumer<BeaconBlockBodyBuilder> createSelector(
...
-          executionPayloadResultFuture.thenCompose(
-              executionPayloadResult ->
-                  executionPayloadResult.getExecutionPayloadFuture().orElseThrow()));
+      final boolean setUnblindedPayloadIfPossible,
+      final ExecutionPayloadResult executionPayloadResult) {
+
+    if (executionPayloadResult.getExecutionPayloadFuture().isPresent()) {
+      // local flow
+      return executionPayloadResult
+          .getExecutionPayloadFuture()
```
Comment (zilm13) [inline beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/BlockOperationSelectorFactory.java:271]: I don't like some lack of transparency when this object contains what fields. Not to change something in this PR, just thoughts

Comment (zilm13) [reply beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/BlockOperationSelectorFactory.java:271]: maybe add some booleans with talking names like `isLocalPayloadResult` to ExecutionPayloadResult and use them to decide which flow we should go

File: beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/BlockOperationSelectorFactory.java [hunk 8]
```diff
@@ -446,18 +463,27 @@ private IllegalStateException executionBlobsBundleIsNotAvailableException(final
...
         .thenApply(
-            headerWithFallbackData ->
-                headerWithFallbackData
-                    .getBlobKzgCommitments()
-                    .orElseThrow(
-                        () ->
-                            new IllegalStateException(
-                                "builder BlobKzgCommitments are not available")));
+            headerWithFallbackData -> {
+              if (setUnblindedPayloadIfPossible
```
Comment (zilm13) [inline beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/BlockOperationSelectorFactory.java]: I think we need to detach this if contents into some function and use it 3 times in class code to be sure we switched to local payload and local kzg commitments simultaniously. Yeah, I see it's the same in 3 places but it's fraglile. Maybe even make it `Function<HeaderFallbackWithData, Boolean> shouldFallbackToLocal` instead of boolean you send currently to methods.

**Review by zilm13 — APPROVED** [review]
LGTM, just few nits

File: beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/BlockOperationSelectorFactory.java (hunk 3 above)
Comment (zilm13) [reply beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/BlockOperationSelectorFactory.java]: it was old code comment, not relevant now

File: beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/BlockOperationSelectorFactory.java (hunk 8 above)
Comment (tbenr) [reply beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/BlockOperationSelectorFactory.java]: I agree, I was having the same feeling while implementing.
