### PR TITLE
Fix Websockets issues before and during merge

### LINKED ISSUE #5738: Ropsten Merge - loss of websockets connection
A user reports the following.

`teku v22.5.2 + geth v1.10.18`

Shortly before the Merge, we had an issue connecting teku to geth via Websockets. Our configuration looked like this:

```
TEKU_EE_ENDPOINT=ws://localhost:8551
```

And we were getting the following output:

```
2022-06-08 14:36:24.100 ERROR - Unexpected error while checking TTD
java.util.concurrent.CompletionException: org.java_websocket.exceptions.WebsocketNotConnectedException
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
at
java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1141) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[teku-infrastructure-async-22.5.2.jar:22.5.2]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at
java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
Caused by: org.java_websocket.exceptions.WebsocketNotConnectedException
at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:664) ~[Java-WebSocket-1.5.2.jar:?]
at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:640) ~[Java-WebSocket-1.5.2.jar:?]
at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:431) ~[Java-WebSocket-1.5.2.jar:?]
at org.web3j.protocol.websocket.WebSocketService.sendRequest(WebSocketService.java:234) ~[core-4.9.1.jar:?]
at org.web3j.protocol.websocket.WebSocketService.sendAsync(WebSocketService.java:185) ~[core-4.9.1.jar:?]
at org.web3j.protocol.core.Request.sendAsync(Request.java:91) ~[core-4.9.1.jar:?]
at tech.pegasys.teku.ethereum.executionclient.web3j.Web3JExecutionEngineClient.getPowChainHead(Web3JExecutionEngineClient.java:68) ~[teku-ethereum-executionclient-22.5.2.jar:22.5.2]
at tech.pegasys.teku.ethereum.executionclient.ThrottlingExecutionEngineClient.lambda$getPowChainHead$1(ThrottlingExecutionEngineClient.java:56) ~[teku-ethereum-executionclient-22.5.2.jar:22.5.2]
at tech.pegasys.teku.infrastructure.async.ThrottlingTaskQueue.lambda$queueTask$0(ThrottlingTaskQueue.java:42) ~[teku-infrastructure-async-22.5.2.jar:22.5.2]
at tech.pegasys.teku.infrastructure.async.ThrottlingTaskQueue.processQueuedTasks(ThrottlingTaskQueue.java:58) ~[teku-infrastructure-async-22.5.2.jar:22.5.2]
```

Changing to http resolved the issue: `TEKU_EE_ENDPOINT=http://localhost:8551/`

After the Merge, Websockets started working again and we were unable to reproduce the issue.

### PR DESCRIPTION
**Pull request by zilm13**
## PR Description
In `Web3JExecutionEngineClient` there are 2 usages of `web3JClient.doWeb3JRequest` which is flawed and wraps already started action. So applying to Websockets, request started before connection is initiated.

Just test written to clarify that bug is not fixed at the moment plus hacky fix.
TODO:
- ~~Fix it correctly~~
- ~~Add log line for JWT loading~~
- ~~Add better logs for JWT auth issues (see below)~~

Regarding the last one:
HTTP:
```
18:21:48.275 ERROR - Execution Client is offline org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: 403; signature is invalid (See log file for full stack trace)
```

JWT is not mentioned and message could be improved, but you could guess the reason as it's 403

Websockets:

```
18:23:15.259 ERROR - Execution Client is offline java.net.ConnectException: Failed to connect to WebSocket (See log file for full stack trace)
```

You have smaller chances to guess the reason here. And we couldn't catch auhorization error because library we use doesn't provide such information and from the first view it's not straightforward to implement exception there to make a PR. So it could be tricky to detect it but we could just blindly mention JWT in error message as it could be a unrare reason during transition to authorized execution engine link.
## Fixed Issue(s)

Fixes #5738 
## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by zilm13** [comment]
Finished, blocked by Besu's authorization issues

**Comment by zilm13** [comment]
I've disabled test, so we could enable fix and later enable the test
Test is blocked by https://github.com/hyperledger/besu/issues/3990

File: infrastructure/logging/src/main/java/tech/pegasys/teku/infrastructure/logging/EventLogger.java [hunk 1]
```diff
@@ -129,8 +129,12 @@ public void syncCompletedWhileHeadIsOptimistic() {
     info("Beacon chain syncing complete, waiting for Execution Client", Color.YELLOW);
   }
 
-  public void executionClientIsOffline(Throwable error) {
-    error("Execution Client is offline", Color.RED, error);
+  public void executionClientIsOffline(final Throwable error, final boolean couldBeAuthError) {
+    error(
+        "Execution Client is offline"
+            + (couldBeAuthError ? ". Make sure you have correct JWT configuration" : ""),
```
Comment (ajsutton) [inline infrastructure/logging/src/main/java/tech/pegasys/teku/infrastructure/logging/EventLogger.java]:
```suggestion
            + (couldBeAuthError ? ". Check the same JWT secret is configured for Teku and the execution client." : ""),
```

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java [hunk 2]
```diff
@@ -67,7 +60,12 @@ public <T> SafeFuture<Response<T>> doRequest(
         .handle(
             (response, exception) -> {
               if (exception != null) {
-                handleError(exception);
+                final boolean authError =
+                    exception instanceof ClientConnectionException
+                        && exception.getMessage() != null
+                        // Could be different authorization error codes, depends on client
+                        && exception.getMessage().contains("received: 40");
```
Comment (ajsutton) [inline ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java]: This would include 404 errors which shouldn't be considered an auth error. In theory it should always be a 401 Unauthorised if authentication fails - unless I'm missing something else relevant.  I'd be tempted to just check for that explicitly given this only affects logging and then raise issues with clients returning a different code.  Possibly something that should be specified in the execution engine API spec as well.

**Review by ajsutton — APPROVED** [review]
LGTM.

File: ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java (hunk 2 above)
Comment (zilm13) [reply ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/web3j/Web3JClient.java]: I saw both 401 and 403 errors with different ELs, wanted to join it, but you are definitely right about 404. I will limit it to 401 and 403
