### PR TITLE
Fix exit code when confirmation is rejected for validator register command

### LINKED ISSUE #2455: teku validator register should return non-zero exit code when confirmation rejected
### Description
When running `teku validator register` an error exit code should be returned if the deposit is not sent for any reason. The command currently exits successfully if the user says no when prompted to confirm.

This creates a problem for scripts which are now unable to tell if the deposit was sent or not.

### PR DESCRIPTION
**Pull request by cemozerr**
## PR Description
Return non-zero exit code when confirmation is rejected for validator register command.

## Fixed Issue(s)

Fixes #2455

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

**Review by mbaxter — APPROVED** [review]

File: teku/src/main/java/tech/pegasys/teku/cli/deposit/RegisterAction.java [hunk 1]
```diff
@@ -114,7 +114,7 @@ public void displayConfirmation(final int totalNumberOfDeposits) {
       return;
     }
     System.out.println("Transaction cancelled.");
-    shutdownFunction.accept(0);
+    shutdownFunction.accept(1);
```
Comment (rolfyone) [inline teku/src/main/java/tech/pegasys/teku/cli/deposit/RegisterAction.java:117]: is this the only case we needed to change? I know this was the concrete example given in the ticket, but if the transaction fails to submit somehow, like the eth1 node didn't respond or something i guess? Insufficient credit to consume maybe?

Comment (cemozerr) [reply teku/src/main/java/tech/pegasys/teku/cli/deposit/RegisterAction.java:117]: That case is already covered here in `DepositRegisterCommand.java`: 
```
  @Override
  public void run() {
    final BLSKeyPair validatorKey = getValidatorKey();

    try (final RegisterAction registerAction =
        registerParams.createRegisterAction(verboseOutputParam.isVerboseOutputEnabled())) {
      registerAction.displayConfirmation(1);
      registerAction.sendDeposit(validatorKey).get();
    } catch (final Throwable t) {
      SUB_COMMAND_LOG.sendDepositFailure(t);
      shutdownFunction.accept(1);
    }
    shutdownFunction.accept(0);
  }
```
