### PR TITLE
Better handle p2p target peer bounds

### LINKED ISSUE #2641: Better handling of p2p target peer bounds
Default values for p2p target peer bounds are as follows:
  - p2p-peer-upper-bound: 74
  - p2p-peer-lower-bound: 64

If I try to run:
`./teku --p2p-peer-upper-bound=63` or `./teku --p2p-peer-lower-bound=75` (without setting the other parameter) then Teku fails to start with a message:

```
Teku failed to start.
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Invalid target peer count range
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
```

We should handle this better. Maybe by setting them equal if only one is specified and is incomaptible with the defaults. For example:
  - If only `--p2p-peer-upper-bound=N` is set and N < 64 (the default lower bound), set the lower bound also to N.
  - If only `--p2p-peer-lower-bound=N` is set and N > 74 (the default upper bound), set the upper bound also to N.

When doing this, output a nice, clear warning message.

Alternatively, improve the existing error message significantly.

### PR DESCRIPTION
**Pull request by cemozerr**
## PR Description
Better handle p2p target peer bounds.

## Fixed Issue(s)

Fixes #2641

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: teku/src/main/java/tech/pegasys/teku/cli/options/P2POptions.java [hunk 1]
```diff
@@ -150,11 +150,19 @@ public String getP2pPrivateKeyFile() {
   }
 
   public int getP2pLowerBound() {
-    return p2pLowerBound;
+    if (p2pLowerBound > p2pUpperBound) {
+      return p2pUpperBound;
+    } else {
+      return p2pLowerBound;
+    }
```
Comment (ajsutton) [inline teku/src/main/java/tech/pegasys/teku/cli/options/P2POptions.java]: Math.min?

File: teku/src/main/java/tech/pegasys/teku/cli/options/P2POptions.java [hunk 2]
```diff
@@ -150,11 +150,19 @@ public String getP2pPrivateKeyFile() {
...
   }
 
   public int getP2pUpperBound() {
-    return p2pUpperBound;
+    if (p2pUpperBound < p2pLowerBound) {
+      return p2pLowerBound;
+    } else {
+      return p2pUpperBound;
+    }
```
Comment (ajsutton) [inline teku/src/main/java/tech/pegasys/teku/cli/options/P2POptions.java]: Math.max?

**Review by ajsutton — COMMENTED** [review]
We should also log a warning when we adjust the peer bounds like this.

File: teku/src/main/java/tech/pegasys/teku/cli/options/P2POptions.java (hunk 1 above)
Comment (cemozerr) [reply teku/src/main/java/tech/pegasys/teku/cli/options/P2POptions.java]: I just added the warnings and with those warnings embedded in the body of the if statements, I don't know how I can incorporate Math.min and max.

```  
public int getP2pLowerBound() {
    if (p2pLowerBound > p2pUpperBound) {
      LOG.warn("Adjusting target number of peers lower bound to equal upper bound, which is {}", p2pUpperBound);
      return p2pUpperBound;
    } else {
      return p2pLowerBound;
    }
  }
```

File: teku/src/main/java/tech/pegasys/teku/cli/options/P2POptions.java [hunk 3]
```diff
@@ -150,11 +154,25 @@ public String getP2pPrivateKeyFile() {
   }
 
   public int getP2pLowerBound() {
-    return p2pLowerBound;
+    if (p2pLowerBound > p2pUpperBound) {
+      LOG.warn(
+          "Adjusting target number of peers lower bound to equal upper bound, which is {}",
+          p2pUpperBound);
```
Comment (ajsutton) [inline teku/src/main/java/tech/pegasys/teku/cli/options/P2POptions.java]: This will get lost in the log file but probably should go to the console instead (via `StatusLogger`).

**Review by ajsutton — APPROVED** [review]
LGTM. Just would be good to make sure the warning messages actually wind up on the console.

File: teku/src/main/java/tech/pegasys/teku/cli/options/P2POptions.java (hunk 3 above)
Comment (cemozerr) [reply teku/src/main/java/tech/pegasys/teku/cli/options/P2POptions.java]: Done.
