### PR TITLE
7549 fix attestation validation

### LINKED ISSUE #8099: Update p2p aggregation gossip topic
[Spec link](https://github.com/ethereum/consensus-specs/blob/dev/specs/electra/p2p-interface.md#beacon_aggregate_and_proof)

##### `beacon_aggregate_and_proof`

The following convenience variables are re-defined
- `index = get_committee_indices(aggregate.committee_bits)[0]`

The following validations are added:
* [REJECT] `len(committee_indices) == 1`, where `committee_indices = get_committee_indices(aggregate)`.
* [REJECT] `aggregate.data.index == 0`

### LINKED ISSUE #8100: Update the attestation gossip topic
https://raw.githubusercontent.com/ethereum/consensus-specs/dev/specs/electra/p2p-interface.md

##### `beacon_attestation_{subnet_id}`

The following convenience variables are re-defined
- `index = get_committee_indices(attestation.committee_bits)[0]`

The following validations are added:
* [REJECT] `len(committee_indices) == 1`, where `committee_indices = get_committee_indices(attestation)`.
* [REJECT] `attestation.data.index == 0`

### PR DESCRIPTION
**Pull request by tbenr**
Implements new rules for attestations and aggregations.

Enables ELECTRA for tests for attestation validation

fixes #8099
fixes #8100

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/spec/src/testFixtures/java/tech/pegasys/teku/spec/generator/AttestationGenerator.java [hunk 1]
```diff
@@ -374,7 +381,12 @@ private void generateNextAttestationFromSchedule() {
         nextAttestation =
             Optional.of(
                 createAttestation(
-                    headState, validatorKeyPair, indexIntoCommittee, cc, genericAttestationData));
+                    headState,
+                    validatorKeyPair,
+                    indexIntoCommittee,
+                    cc,
+                    genericAttestationData,
+                    cc.getIndex()));
```
Comment (rolfyone) [inline ethereum/spec/src/testFixtures/java/tech/pegasys/teku/spec/generator/AttestationGenerator.java]: i know cc was existing but ..... name?

File: ethereum/spec/src/testFixtures/java/tech/pegasys/teku/spec/generator/AttestationGenerator.java [hunk 2]
```diff
@@ -384,7 +396,8 @@ private Attestation createAttestation(
         BLSKeyPair attesterKeyPair,
         int indexIntoCommittee,
         Committee committee,
-        AttestationData attestationData) {
+        AttestationData attestationData,
+        UInt64 committeeIndex) {
```
Comment (rolfyone) [inline ethereum/spec/src/testFixtures/java/tech/pegasys/teku/spec/generator/AttestationGenerator.java]: final

File: ethereum/spec/src/testFixtures/java/tech/pegasys/teku/spec/generator/AttestationGenerator.java [hunk 3]
```diff
@@ -384,7 +396,8 @@ private Attestation createAttestation(
...
       int committeeSize = committee.getCommitteeSize();
```
Comment (rolfyone) [inline ethereum/spec/src/testFixtures/java/tech/pegasys/teku/spec/generator/AttestationGenerator.java]: final

**Review by rolfyone — APPROVED** [review]

File: ethereum/spec/src/testFixtures/java/tech/pegasys/teku/spec/generator/AttestationGenerator.java [hunk 4]
```diff
@@ -101,7 +103,11 @@ private static Attestation aggregateAttestations(List<Attestation> srcAttestatio
                 .map(attestation -> attestation.getAggregateSignature())
                 .collect(Collectors.toList()));
 
-    return attestationSchema.create(targetBitlist, srcAttestations.get(0).getData(), targetSig);
+    return attestationSchema.create(
+        targetBitlist,
+        srcAttestations.get(0).getData(),
+        () -> srcAttestations.get(0).getCommitteeBitsRequired(),
+        targetSig);
```
Comment (rolfyone) [inline ethereum/spec/src/testFixtures/java/tech/pegasys/teku/spec/generator/AttestationGenerator.java:112]: final

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/validation/AggregateAttestationValidator.java [hunk 5]
```diff
@@ -149,6 +149,23 @@ private SafeFuture<InternalValidationResult> verifyAggregate(
                         "Rejecting aggregate attestation because it does not have participants"));
               }
 
+              if (attestation.getAttestation().requiresCommitteeBits()) {
```
Comment (rolfyone) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/validation/AggregateAttestationValidator.java]: duplicate?
