### PR TITLE
Convert to subnet id when processing sync committee subscriptions

### LINKED ISSUE #3942: Altair: Sync committee subnet subscriptions out of range
### Description
When handling requests to subscribe to sync committee subnets, the validator's index in the committee is provided which should be converted to the subcommittee index by `ValidatorApiHandler.subscribeToSyncCommitteeSubnets` but is currently being passed through as-is resulting in the exception below.

```
2021-05-07 09:49:19.369 | SlotEventsChannel-9       | ERROR | ObservableValue                | Error in callback: 
java.lang.IndexOutOfBoundsException: index (31) must be less than size (8)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1345) ~[guava-29.0-jre.jar:?]
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1327) ~[guava-29.0-jre.jar:?]
	at tech.pegasys.teku.ssz.collections.impl.BitvectorImpl.<init>(BitvectorImpl.java:67) ~[classes/:?]
	at tech.pegasys.teku.ssz.collections.impl.BitvectorImpl.<init>(BitvectorImpl.java:73) ~[classes/:?]
	at tech.pegasys.teku.ssz.collections.impl.SszBitvectorImpl.ofBits(SszBitvectorImpl.java:33) ~[classes/:?]
	at tech.pegasys.teku.ssz.schema.collections.impl.SszBitvectorSchemaImpl.ofBits(SszBitvectorSchemaImpl.java:47) ~[classes/:?]
	at tech.pegasys.teku.ssz.schema.collections.SszBitvectorSchema.ofBits(SszBitvectorSchema.java:38) ~[classes/:?]
	at tech.pegasys.teku.networking.p2p.discovery.DiscoveryNetwork.setSyncCommitteeSubnetSubscriptions(DiscoveryNetwork.java:167) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.subscribers.ObservableValue.notify(ObservableValue.java:121) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.subscribers.ObservableValue.lambda$set$1(ObservableValue.java:116) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.forEachRemaining(CopyOnWriteArrayList.java:1152) ~[?:?]
	at tech.pegasys.teku.infrastructure.subscribers.ObservableValue.set(ObservableValue.java:116) ~[classes/:?]
	at tech.pegasys.teku.networking.eth2.SubnetSubscriptionService.removeSubscription(SubnetSubscriptionService.java:42) ~[classes/:?]
	at tech.pegasys.teku.networking.eth2.ActiveEth2P2PNetwork.unsubscribeFromSyncCommitteeSubnetId(ActiveEth2P2PNetwork.java:287) ~[classes/:?]
	at tech.pegasys.teku.networking.eth2.gossip.subnets.SyncCommitteeSubscriptionManager.onSlot(SyncCommitteeSubscriptionManager.java:43) ~[classes/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverTo(DirectEventDeliverer.java:54) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverTo$0(AsyncEventDeliverer.java:61) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) [classes/:?]
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
Convert the committee index to subcommittee ID when processing sync committee subscription requests.

## Fixed Issue(s)
fixes #3942 

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: validator/coordinator/src/test/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandlerTest.java [hunk 1]
```diff
@@ -519,6 +521,18 @@ public void subscribeToBeaconCommittee_shouldUpdateActiveValidatorTrackerWhenNot
...
+  @Test
+  void subscribeToSyncCommitteeSubnets_shouldConvertCommitteeIndexToSubnetId() {
+    final SyncCommitteeSubnetSubscription subscription1 =
+        new SyncCommitteeSubnetSubscription(1, Set.of(1, 2, 15, 30), UInt64.valueOf(44));
+    final SyncCommitteeSubnetSubscription subscription2 =
+        new SyncCommitteeSubnetSubscription(1, Set.of(5, 10), UInt64.valueOf(35));
+    validatorApiHandler.subscribeToSyncCommitteeSubnets(List.of(subscription1, subscription2));
+    System.out.println(spec.getSyncCommitteeUtilRequired(ZERO).getSubcommitteeSize());
+    verify(syncCommitteeSubscriptionManager).subscribe(0, subscription1.getUntilEpoch());
+    verify(syncCommitteeSubscriptionManager).subscribe(0, subscription1.getUntilEpoch());
```
Comment (rolfyone) [inline validator/coordinator/src/test/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandlerTest.java]: so does this convert to subnet 0 calls the subscription manager 4 times and subnet1 calls it 2 times?
can probably use `verify(syncCommitteeSubscriptionManager, times(4))`
and second call should be checking subscription 2 i think?

Comment (ajsutton) [reply validator/coordinator/src/test/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandlerTest.java]: Ah yes, that test got far enough to reveal the problem but didn't actually get finished to be completely explicit about what we are expecting.

**Review by rolfyone — APPROVED** [review]
LGTM
