### PR TITLE
Check head state and assignments before attempting sync committee duty.

### LINKED ISSUE #4370: after upgrading to 21.9.0, see illegal state exception: "Unable to perform aggregation for sync committee"

### PR DESCRIPTION
**Pull request by rolfyone**
If a sync committee duty cannot get the current chain head, and there are no assignments, generating an error has limited value, so in the case where this condition is met, treat the duty as a no op.

Also, if there are no assignments, there is no need to subscribe to any subnets.

fixes #4370

Signed-off-by: Paul Harris <paul.harris@consensys.net>

## Documentation

- [X] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: validator/client/src/main/java/tech/pegasys/teku/validator/client/duties/synccommittee/SyncCommitteeScheduledDuties.java [hunk 1]
```diff
@@ -126,15 +129,17 @@ public int countDuties() {
...
+      validatorApiChannel.subscribeToSyncCommitteeSubnets(
+          assignments.stream()
+              .map(
+                  assignment ->
+                      new SyncCommitteeSubnetSubscription(
+                          assignment.getValidatorIndex(),
+                          assignment.getCommitteeIndices(),
+                          lastEpochInCommitteePeriod.increment()))
+              .collect(Collectors.toSet()));
+    }
```
Comment (ajsutton) [inline validator/client/src/main/java/tech/pegasys/teku/validator/client/duties/synccommittee/SyncCommitteeScheduledDuties.java]: nit:
```suggestion
    if (assignments.isEmpty()) {
      return;
    }
    validatorApiChannel.subscribeToSyncCommitteeSubnets(
        assignments.stream()
            .map(
                assignment ->
                    new SyncCommitteeSubnetSubscription(
                        assignment.getValidatorIndex(),
                        assignment.getCommitteeIndices(),
                        lastEpochInCommitteePeriod.increment()))
            .collect(Collectors.toSet()));
```

File: validator/client/src/main/java/tech/pegasys/teku/validator/client/duties/synccommittee/SyncCommitteeScheduledDuties.java [hunk 2]
```diff
@@ -77,6 +77,9 @@ public boolean requiresRecalculation(final Bytes32 newHeadDependentRoot) {
   public SafeFuture<DutyResult> performProductionDuty(final UInt64 slot) {
     lastSignatureBlockRoot = chainHeadTracker.getCurrentChainHead(slot);
     lastSignatureSlot = Optional.of(slot);
+    if (assignments.isEmpty() && lastSignatureBlockRoot.isEmpty()) {
+      return SafeFuture.completedFuture(DutyResult.NO_OP);
+    }
```
Comment (ajsutton) [inline validator/client/src/main/java/tech/pegasys/teku/validator/client/duties/synccommittee/SyncCommitteeScheduledDuties.java]: We're still performing this check after we get the current chain head but isn't the point to make sure we don't ask for the chain head if we aren't going to use it? There's no point going beyond here even if the chain head is known.

File: validator/client/src/test/java/tech/pegasys/teku/validator/client/duties/synccommittee/SyncCommitteeScheduledDutiesTest.java [hunk 3]
```diff
@@ -78,6 +79,15 @@ void shouldSubscribeToSubnets() {
                     70, Set.of(2, 6), PERIOD_END_EPOCH.increment())));
   }
 
+  @Test
+  void shouldNotSubscribeToSubnetsWithoutValidatorsPresent() {
+    final SyncCommitteeScheduledDuties duties = validBuilder().build();
+
+    duties.subscribeToSubnets();
+
+    verifyNoInteractions(validatorApiChannel);
```
Comment (ajsutton) [inline validator/client/src/test/java/tech/pegasys/teku/validator/client/duties/synccommittee/SyncCommitteeScheduledDutiesTest.java:89]: We probably should confirm we don't call `chainHeadTracker.getCurrentChainHead` here either since we have no validators.

**Review by ajsutton — APPROVED** [review]
LGTM.
