### PR TITLE
fix retrieval of validators from beacon state.

### LINKED ISSUE #3071: API /eth/v1/beacon/headers/[finalized|head] return 404
`/eth/v1/beacon/headers/{block_id}` returns 404 for `head` and `finalized` rather than the expected headers.

For the second and third queries below I expect to see block headers, as per the interface documentation, rather than the 404 message:

```
ben@metalalbert:~/teku$ curl localhost:5051/eth/v1/beacon/headers/genesis
{"data":{"root":"0xebe49843e96e538592c9e1976e155e9057c251ed9312eba517afce3ca1a0660c","canonical":true,"header":{"message":{"slot":"0","proposer_index":"0","parent_root":"0x0000000000000000000000000000000000000000000000000000000000000000","state_root":"0xaf6aafa94dcc22a5cf0253c4f5dd886397900034bf7c149c54635b537f34f64e","body_root":"0xebe49843e96e538592c9e1976e155e9057c251ed9312eba517afce3ca1a0660c"},"signature":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"}}}

ben@metalalbert:~/teku$ curl localhost:5051/eth/v1/beacon/headers/head
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>404 - Page not found</title>
</head>
<body>
<p>The page you have requested doesn't seem to be one we were expecting.</p>
<P>In better news, you can go and check <a href="/swagger-ui">swagger</a> to hopefully find what you need.</P>
</body>
</html>

ben@metalalbert:~/teku$ curl localhost:5051/eth/v1/beacon/headers/finalized
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>404 - Page not found</title>
</head>
<body>
<p>The page you have requested doesn't seem to be one we were expecting.</p>
<P>In better news, you can go and check <a href="/swagger-ui">swagger</a> to hopefully find what you need.</P>
</body>
</html>

ben@metalalbert:~/teku$ curl localhost:5051/eth/v1/beacon/headers/foobarbaz
{"status":400,"message":"Invalid block: foobarbaz"}
```

It looks like #3011 implemented this, but something is broken.

Version: `teku/v0.12.12-dev-5cefb9a2/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13`

### LINKED ISSUE #3077: API endpoint /eth/v1/beacon/states/{state_id}/validators returns error
The endpoint `/eth/v1/beacon/states/{state_id}/validators` without query parameters should return all validators.  Teku rejects such a request as invalid, due to not having an `id` query parameter.

Tested on a recent `master`:

```
git rev-parse HEAD
2884db66a0fa28c8b6607fe76c4878555c95cb05
```

Requesting this URL provides the following error log:

```
07:22:42.245 ERROR - Failed to process request to URL http://localhost:5051/eth/v1/beacon/states/head/validators
java.lang.IllegalArgumentException: Query parameter id not found
	at tech.pegasys.teku.beaconrestapi.ListQueryParameterUtils.validateQueryParameter(ListQueryParameterUtils.java:39) ~[teku-data-beaconrestapi-0.12.12-SNAPSHOT.jar:0.12.12-dev-2884db66]
	at tech.pegasys.teku.beaconrestapi.ListQueryParameterUtils.getParameterAsStringList(ListQueryParameterUtils.java:62) ~[teku-data-beaconrestapi-0.12.12-SNAPSHOT.jar:0.12.12-dev-2884db66]
	at tech.pegasys.teku.beaconrestapi.handlers.v1.beacon.StateValidatorsUtil.parseValidatorsParam(StateValidatorsUtil.java:30) ~[teku-data-beaconrestapi-0.12.12-SNAPSHOT.jar:0.12.12-dev-2884db66]
	at tech.pegasys.teku.beaconrestapi.handlers.v1.beacon.GetStateValidators.handle(GetStateValidators.java:89) ~[teku-data-beaconrestapi-0.12.12-SNAPSHOT.jar:0.12.12-dev-2884db66]
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23) ~[javalin-3.11.0.jar:?]
	at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:121) ~[javalin-3.11.0.jar:?]
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45) ~[javalin-3.11.0.jar:?]
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24) ~[javalin-3.11.0.jar:?]
	at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:129) ~[javalin-3.11.0.jar:?]
	at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40) ~[javalin-3.11.0.jar:?]
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:81) ~[javalin-3.11.0.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at io.javalin.websocket.JavalinWsServlet.service(JavalinWsServlet.kt:51) ~[javalin-3.11.0.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at io.javalin.core.JavalinServer$start$wsAndHttpHandler$1.doHandle(JavalinServer.kt:49) ~[javalin-3.11.0.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at java.lang.Thread.run(Thread.java:830) [?:?]
```

### LINKED ISSUE #3105: Incorrect response from /eth/v1/beacon/states/{state_id}/validators endpoint
### Description
Sending an invalid value for the state ID should return a 400 error, but Teku returns a 500 error.

For example, sending to `/eth/v1/beacon/states/invalid/validators` returns:

```
{"status":500,"message":"An unexpected error occurred"}
```

This problem also occurs for the `/eth/v1/beacon/states/invalid/validator_balances` endpoint.

This is from a recent master:

```
git rev-parse HEAD
f56f853509670ca81fb8e749c06777bf89d361a8
```

### PR DESCRIPTION
**Pull request by rolfyone**
- Error codes were returning 500 for any issue, rather than the expected codes (#3105)

 - `/eth/v1/state/{state_id}/validators/{validator_id}` needed to get the correct state to work from (#3071)

 Fixes #3077 
 Fixes #3105

Signed-off-by: Paul Harris <paul.harris@consensys.net>

## Documentation

- [X] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java [hunk 1]
```diff
@@ -617,9 +614,28 @@ public void requireStoreAvailable() {
     return getValidatorSelector(state, validators)
         .filter(getStatusPredicate(state, statusFilter))
         .mapToObj(index -> ValidatorResponse.fromState(state, index))
```
Comment (ajsutton) [inline data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java:612]: Maybe rather than having a `ValidatorResponse.EMPTY` `ValidatorResponse.fromState` could return an `Optional<ValidatorResponse>` then this could just flat map?

File: data/provider/src/test/java/tech/pegasys/teku/api/ChainDataProviderTest.java [hunk 2]
```diff
@@ -798,6 +798,29 @@ public void filteredValidatorsList_shouldFilterByValidatorPubkey() {
...
+
+  @Test
+  public void validatorParameterToIndex_shouldThrowBadRequestExceptionWhenIndexTooHigh() {
+    final ChainDataProvider provider =
+        new ChainDataProvider(recentChainData, combinedChainDataClient);
+    assertThrows(BadRequestException.class, () -> provider.validatorParameterToIndex("1024000"));
+  }
+
+  @Test
+  public void validatorParameterToIndex_shouldThrowBadRequestExceptionWhenKeyNotFound() {
```
Comment (ajsutton) [inline data/provider/src/test/java/tech/pegasys/teku/api/ChainDataProviderTest.java:808]: We throw when the key isn't found or only when it's an invalid key?

File: data/serializer/src/main/java/tech/pegasys/teku/api/response/v1/beacon/ValidatorResponse.java [hunk 3]
```diff
@@ -60,14 +63,18 @@ public ValidatorResponse(
...
+      tech.pegasys.teku.datastructures.state.Validator validatorInternal =
+          state.getValidators().get(index);
+      final UInt64 current_epoch = compute_epoch_at_slot(state.getSlot());
+      return new ValidatorResponse(
+          UInt64.valueOf(index),
+          state.getBalances().get(index),
+          getValidatorStatus(current_epoch, validatorInternal),
+          new Validator(validatorInternal));
+    } catch (IndexOutOfBoundsException ex) {
+      return ValidatorResponse.EMPTY;
```
Comment (ajsutton) [inline data/serializer/src/main/java/tech/pegasys/teku/api/response/v1/beacon/ValidatorResponse.java]: Would be better to check the index is valid ahead of time rather than catching the `IndexOutOfBoundsException`.

**Review by ajsutton — COMMENTED** [review]
Looks good generally just a few tweaks. Mostly I'm unsure why we need an `EMPTY` response rather than being able to use `Optional.empty` but I may be missing something.

File: data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java (hunk 1 above)
Comment (rolfyone) [reply data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java:612]: it wanted `SafeFuture<Optional<Optional<ValidatorResponse>>`...

File: data/provider/src/test/java/tech/pegasys/teku/api/ChainDataProviderTest.java (hunk 2 above)
Comment (rolfyone) [reply data/provider/src/test/java/tech/pegasys/teku/api/ChainDataProviderTest.java:808]: key not found is basically search by root, index not found is basically index out of bounds...

File: data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java (hunk 1 above)
Comment (ajsutton) [reply data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java:612]: That sounds like you need a `flatMap` somewhere instead of just `map`.

File: data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java [hunk 4]
```diff
@@ -562,6 +559,7 @@ public void requireStoreAvailable() {
       final tech.pegasys.teku.datastructures.state.BeaconState state) {
     return validatorIndices.stream()
         .map(index -> ValidatorResponse.fromState(state, index))
+        .flatMap(Optional::stream)
```
Comment (ajsutton) [inline data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java]: nit: this one can just use `.flatMap` instead of `.map` as it's not an `IntStream`.

File: data/serializer/src/main/java/tech/pegasys/teku/api/response/v1/beacon/ValidatorResponse.java [hunk 5]
```diff
@@ -59,15 +62,20 @@ public ValidatorResponse(
     this.validator = validator;
   }
 
-  public static ValidatorResponse fromState(final BeaconState state, final Integer index) {
+  public static Optional<ValidatorResponse> fromState(
+      final BeaconState state, final Integer index) {
+    if (index >= state.getValidators().size()) {
+      throw new BadRequestException("Validator index out of bounds: " + index);
+    }
```
Comment (ajsutton) [inline data/serializer/src/main/java/tech/pegasys/teku/api/response/v1/beacon/ValidatorResponse.java]: If this is going to throw an exception if the index is too big then it doesn't need to return `Optional` because it will never return empty.  I wouldn't have expected a validator index being too big to be a bad request, it's just not found and so the validator wouldn't be included in the results.

**Review by ajsutton — COMMENTED** [review]
Given that the query params are intended as filters, the only time they should result in a bad request is if they can't be parsed.  If they are parsed but don't match any validators (public key not mapping to an index, or index larger than the number of validators) they would just not match anything so effectively be ignored.

File: data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java (hunk 4 above)
Comment (rolfyone) [reply data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java]: im doing something wrong, because i the compiler didnt like me on this one...

File: data/serializer/src/main/java/tech/pegasys/teku/api/response/v1/beacon/ValidatorResponse.java (hunk 5 above)
Comment (rolfyone) [reply data/serializer/src/main/java/tech/pegasys/teku/api/response/v1/beacon/ValidatorResponse.java]: was getting index out of bounds, which you didnt want to catch, so this was option b, i'll have to have another look.

Comment (ajsutton) [reply data/serializer/src/main/java/tech/pegasys/teku/api/response/v1/beacon/ValidatorResponse.java]: Just return `Optional.empty()` here instead of throwing an exception.

File: data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java [hunk 6]
```diff
@@ -448,28 +447,26 @@ public void requireStoreAvailable() {
...
         }
         final int validatorIndex = numericValidator.intValue();
         final int validatorCount = state.getValidators().size();
         if (validatorIndex > validatorCount) {
-          throw new IllegalArgumentException(
+          throw new BadRequestException(
               String.format(
                   "Invalid validator index: %d, exceeds validator count: %d",
                   validatorIndex, validatorCount));
         }
```
Comment (ajsutton) [inline data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java]: This looks like a case where it should result in not found rather than BadRequestException - the index can be parsed but there is no validator at that index. Suspect this should just return `Optional.empty` which matches the behaviour of a public key not being found and avoids a lot of places needing to check for an index being too large later.

**Review by ajsutton — APPROVED** [review]
LGTM.  I think just one last place to switch from throwing an exception to returning empty.
