### PR TITLE
Fix electra attestation performance tracker

### LINKED ISSUE #9004: [Devnet5] `IndexOutOfBoundsException` at every epoch transition
```
2025-01-16 14:15:48.002 INFO  - Epoch Event *** Epoch: 7, Justified checkpoint: 6, Finalized checkpoint: 5, Finalized root: c07337b7e297583c4c9141636e8724ffb5b59aaa7b254441c129db87b1827fa4
2025-01-16 14:15:48.004 INFO  - Block performance: epoch 6, expected 2, produced 2, included 2 (100%)
2025-01-16 14:15:48.006 INFO  - Sync committee performance: epoch 6, expected 224, produced 224, correct 224, included 196 (88%)
2025-01-16 14:15:48.140 ERROR - java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: index (353) must be less than size (353)
```

I suspect it is related to attestation performance calculation. (Indeed Attestation Performance is not printed out)

### PR DESCRIPTION
**Pull request by tbenr**
The bug was that we were getting committeeSizes for the **inclusion** slot, not actual attestation data slot!

Moreover now I avoid to ask for committeeSizes if they are not needed (pre-electra)

fixes #9004

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/performance/DefaultPerformanceTracker.java [hunk 1]
```diff
@@ -147,10 +147,10 @@ public void onSlot(final UInt64 slot) {
     }
 
     SafeFuture.allOf(reportingTasks.toArray(SafeFuture[]::new))
-        .handleException(LOG::error)
+        .handleException(error -> LOG.error("Failed to report performance metrics", error))
```
Comment (tbenr) [inline beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/performance/DefaultPerformanceTracker.java:150]: this allows us to get a stackTrace when an error occurs

File: validator/client/src/main/java/tech/pegasys/teku/validator/client/duties/BlockProductionDuty.java [hunk 2]
```diff
@@ -125,7 +125,7 @@ private SafeFuture<BlockContainer> validateBlock(
 
     if (!blockContainerAndMetaData.consensusBlockValue().isZero()) {
       LOG.info(
-          "Received block for slot {}, block rewards {} ETH, execution payload value {} ETH",
+          "Validator client received block for slot {}, block rewards {} ETH, execution payload value {} ETH",
```
Comment (tbenr) [inline validator/client/src/main/java/tech/pegasys/teku/validator/client/duties/BlockProductionDuty.java:128]: This is annoying me for a while.
Reading the logs is unclear who is saying this. Better to clarify that is VC speaking here.

**Review by mehdi-aouadi — APPROVED** [review]
LGTM
