### PR TITLE
initial draft

### LINKED ISSUE #3977: Validate initial state fork matches ForkSchedule
### Description
When an `--initial-state` is loaded, verify that the fork in the loaded state matches the expected fork at that epoch from `ForkSchedule`.  An incorrect fork should be treated as a fatal error and the initial state not stored to the database.

This ensures that people can't accidentally use a state from pyrmont while running mainnet configuration.  Currently the state loads and they just never find any peers because the finalized root doesn't match.

### PR DESCRIPTION
**Pull request by vishaljhala**
## PR Description
Currently, some one can accidentally use a state from pyrmont while running mainnet configuration. Currently the state loads and they just never find any peers because the finalized root doesn't match.

This PR validates that fork from --initial-state matches the expected fork at that epoch from ForkSchedule. An incorrect fork should be treated as a fatal error and the initial state not stored to the database.

This ensures that people can't 
## Fixed Issue(s)
fixes <https://github.com/ConsenSys/teku/issues/3977>

## Documentation

- [ ] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/spec/src/testFixtures/java/tech/pegasys/teku/spec/util/DataStructureUtil.java [hunk 1]
```diff
@@ -846,6 +846,16 @@ public AnchorPoint randomAnchorPoint(final UInt64 epoch) {
     return AnchorPoint.fromInitialBlockAndState(anchorBlockAndState);
   }
 
+  public AnchorPoint randomAnchorPoint(final UInt64 epoch, final Fork currentFork) {
+    UInt64 slot = computeStartSlotAtEpoch(epoch);
+    final BeaconBlockAndState blockAndState =
+        randomBlockAndState(
+            slot,
+            stateBuilderPhase0().slot(slot).build(),
+            currentFork.getBackingNode().hashTreeRoot());
```
Comment (ajsutton) [inline ethereum/spec/src/testFixtures/java/tech/pegasys/teku/spec/util/DataStructureUtil.java]: This is setting the parent root of the block to the current fork's hash tree root, whereas you need to put the current fork into the state:

```suggestion
        randomBlockAndState(
            slot, stateBuilderPhase0().slot(slot).fork(currentFork).build(), randomBytes32());
```

File: services/beaconchain/src/test/java/tech/pegasys/teku/services/beaconchain/WeakSubjectivityInitializerTest.java [hunk 2]
```diff
@@ -222,9 +222,11 @@ public void validateInitialAnchor_atMostRecentPotentiallyFinalizedEpoch() {
     final UInt64 currentSlot = compute_start_slot_at_epoch(currentEpoch);
 
     final DataStructureUtil dataStructureUtil = new DataStructureUtil();
-    final AnchorPoint anchor = dataStructureUtil.randomAnchorPoint(currentEpoch.minus(2));
+    final AnchorPoint anchor =
+        dataStructureUtil.randomAnchorPoint(
+            currentEpoch, spec.getForkSchedule().getFork(currentEpoch));
```
Comment (ajsutton) [inline services/beaconchain/src/test/java/tech/pegasys/teku/services/beaconchain/WeakSubjectivityInitializerTest.java]: The original version of this test was using an anchor point from `currentEpoch.minus(2)` which has been lost with this change and that's why it's failing - we can't have finalized epoch 10 if we're only up to the first slot in that epoch.

We can fix the deprecation warnings in this test and the failure by changing it to:

```
    
  @Test
  public void validateInitialAnchor_atMostRecentPotentiallyFinalizedEpoch() {
    final UInt64 currentEpoch = UInt64.valueOf(10);
    final UInt64 currentSlot = spec.computeStartSlotAtEpoch(currentEpoch);

    final DataStructureUtil dataStructureUtil = new DataStructureUtil(spec);
    final UInt64 anchorEpoch = currentEpoch.minus(2);
    final AnchorPoint anchor =
        dataStructureUtil.randomAnchorPoint(
            anchorEpoch, spec.getForkSchedule().getFork(anchorEpoch));

    // Should not throw
    initializer.validateInitialAnchor(anchor, currentSlot, spec);
  }
```

**Review by ajsutton — COMMENTED** [review]
Thanks for this. The main logic here looks good. Left a couple of suggestions to get the tests passing and it should be good to go.

**Review by ajsutton — APPROVED** [review]
LGTM. Thanks for taking this on.
