### PR TITLE
Use the CLI argument to disable p2p logging.

### LINKED ISSUE #4329: Improve logging of invalid blocks
Teku v21.7.0 on mainnet.

I occasionally get a console warning as follows:

```
Sep 08 02:55:11 metalalbert teku[2327]: 02:55:11.488 WARN  - Rejecting invalid block at slot 2020474 with root 0xcbdc592b5b4c49783a9487c05107bfd372968dff65ee0c083943adc09f7c36fd because FAILED_STATE_TRANSITION. Full block data: 0x64000000a2....
```

Questions:
1. Does this need to be at `WARN` level? If this is just junk from another client that I can't do anything about then it's a good way to DOS my logs and should probably be moved to `DEBUG`. Otoh, if this is a useful message indicating that my node might be on a wrong fork or something, then it's probably worth keeping at `WARN`.
2. Notwithstanding the above, I don't need to see the full block data (which is enormous) in my console. If it is a useful message, maybe log a one-liner up to the full stop at `WARN` level, then output the full block data at `DEBUG` level.

### PR DESCRIPTION
**Pull request by rolfyone**
There have been reports of users getting p2p warnings without the CLI flag being set, so simplified the logic to ensure this should not happen.

The log message comes through as a warning, so it can be confusing to see.

fixes #4329

Signed-off-by: Paul Harris <paul.harris@consensys.net>

## Documentation

- [X] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: infrastructure/logging/src/main/java/tech/pegasys/teku/infrastructure/logging/LoggingConfigurator.java [hunk 1]
```diff
@@ -246,12 +250,9 @@ private static LoggerConfig setUpValidatorLogger(final Appender appender) {
...
-    // Don't disable p2p error logs unless the root log level disables error.
-    final Level p2pLogLevel =
-        INCLUDE_P2P_WARNINGS || ROOT_LOG_LEVEL.isMoreSpecificThan(Level.ERROR)
-            ? ROOT_LOG_LEVEL
-            : Level.ERROR;
+    final Level p2pLogLevel = INCLUDE_P2P_WARNINGS ? Level.INFO : Level.OFF;
     final LoggerConfig logger = new LoggerConfig(P2P_LOGGER_NAME, p2pLogLevel, true);
+    StatusLogger.getLogger().info("Include P2P warnings set to: {}", INCLUDE_P2P_WARNINGS);
     logger.addAppender(appender, ROOT_LOG_LEVEL, null);
     return logger;
```
Comment (ajsutton) [inline infrastructure/logging/src/main/java/tech/pegasys/teku/infrastructure/logging/LoggingConfigurator.java]: I think we should just be removing this whole section.  The logger doesn't need to be treated specially anymore because we're toggling whether to log or not in `P2PLogger` itself now.

**Review by ajsutton — APPROVED** [review]
LGTM.
