### PR TITLE
Fix off by one error when validating required deposits are available

### LINKED ISSUE #2047: Unable to create block because ETH1 deposits are not available
I believe my local Besu is up to date and functioning and should be viewable by the beacon node.

```
2020-06-03 15:26:48.074+00:00 | ValidatorApiChannel-0 | ERROR | teku-validator-log | ^[[31mValidator   *** Failed to produce block  Slot: 55034^[[0m
tech.pegasys.teku.validator.coordinator.MissingDepositsException: Unable to create block because ETH1 deposits are not available. Missing deposits 806 to 806
        at tech.pegasys.teku.validator.coordinator.DepositProvider.getDeposits(DepositProvider.java:110) ~[teku-validator-coordinator-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.validator.coordinator.BlockFactory.createUnsignedBlock(BlockFactory.java:92) ~[teku-validator-coordinator-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createUnsignedBlock$3(ValidatorApiHandler.java:149) ~[teku-validator-coordinator-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createFromBlockAndState$4(ValidatorApiHandler.java:164) ~[teku-validator-coordinator-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.util.async.SafeFuture.lambda$thenApplyChecked$15(SafeFuture.java:275) ~[teku-util-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2306) ~[?:?]
        at tech.pegasys.teku.util.async.SafeFuture.thenCompose(SafeFuture.java:312) ~[teku-util-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.util.async.SafeFuture.thenApplyChecked(SafeFuture.java:272) ~[teku-util-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createFromBlockAndState(ValidatorApiHandler.java:159) ~[teku-validator-coordinator-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createUnsignedBlock(ValidatorApiHandler.java:146) ~[teku-validator-coordinator-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at tech.pegasys.teku.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:70) ~[teku-events-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:63) ~[teku-events-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:70) ~[teku-events-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111) [teku-events-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103) [teku-events-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
```

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
`BeaconState.eth1_deposit_index` is the number of of deposits included (so effectively a 1 based index) but our deposit index is 0 based.  So when there was a deposit tracked by `DepositProvider` and all deposits had been included in the chain, it incorrectly threw a `MissingDepositsException`.  If there were no known deposits, it would work correctly.

## Fixed Issue(s)
fixes #2047

### CODE REVIEW

File: validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/DepositProvider.java [hunk 1]
```diff
@@ -124,6 +121,18 @@ public void onMinGenesisTimeBlock(MinGenesisTimeBlockEvent event) {}
         Deposit.class);
   }
 
+  private void checkRequiredDepositsAvailable(
+      final UnsignedLong eth1DepositCount, final UnsignedLong fromDepositIndex) {
```
Comment (mbaxter) [inline validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/DepositProvider.java]:
```suggestion
      final UnsignedLong eth1DepositCount, final UnsignedLong eth1DepositIndex) {
```

**Review by mbaxter — APPROVED** [review]

**Comment by benjaminion** [comment]
Been running this all day and successfully proposed three blocks with no failures. This contrasts to two failures due to this issue yesterday without the patch. Small sample, but I'd say it looks good.
