### PR TITLE
Handle requests for a single block by slot or root not returning any result

### LINKED ISSUE #3027: Handle remote peers not having block requested by root
### Description
When a remote peer doesn't have the block requested by root, it should return no response chunks.  Teku however is expecting it to always return a single chunk.

We should fix this to return an empty `Optional` to indicate the peer does not have the block and cleanly handle that case, rather than throwing an exception.

Note the error is logged at DEBUG level so it's not noise in logs but is incorrect behaviour.

```
{"timestamp":"2020-10-20T04:58:49,911","level":"DEBUG","thread":"nioEventLoopGroup-3-3","class":"FetchBlockTask","message":"Failed to fetch block 0xcc92333e8ab9ca670c466394c5e54f7142235b654ca485461dc104d9672b7be4","throwable":" java.util.concurrent.CompletionException: java.lang.NullPointerException: No response received when single response expected\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)\n\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)\n\tat java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)\n\tat tech.pegasys.teku.networking.eth2.rpc.core.ResponseStreamImpl.completeSuccessfully(ResponseStreamImpl.java:75)\n\tat tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.lambda$completeRequest$0(Eth2OutgoingRequestHandler.java:196)\n\tat java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)\n\tat java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)\n\tat java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2172)\n\tat tech.pegasys.teku.infrastructure.async.SafeFuture.thenAccept(SafeFuture.java:390)\n\tat tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.completeRequest(Eth2OutgoingRequestHandler.java:193)\n\tat tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.readComplete(Eth2OutgoingRequestHandler.java:157)\n\tat tech.pegasys.teku.networking.p2p.libp2p.rpc.RpcHandler$Controller.onRemoteWriteClosed(RpcHandler.java:191)\n\tat tech.pegasys.teku.networking.p2p.libp2p.rpc.RpcHandler$Controller.userEventTriggered(RpcHandler.java:184)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1428)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)\n\tat io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:913)\n\tat io.libp2p.etc.util.netty.mux.MuxChannel.onRemoteDisconnected(MuxChannel.kt:58)\n\tat io.libp2p.etc.util.netty.mux.AbstractMuxHandler.onRemoteDisconnect(AbstractMuxHandler.kt:72)\n\tat io.libp2p.mux.MuxHandler.channelRead(MuxHandler.kt:37)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)\n\tat io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)\n\tat io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)\n\tat io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:832)\nCaused by: java.lang.NullPointerException: No response received when single response expected\n\tat com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897)\n\tat tech.pegasys.teku.networking.eth2.rpc.core.ResponseStreamImpl.lambda$expectSingleResponse$1(ResponseStreamImpl.java:42)\n\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)\n\t... 58 more\n"}
```

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
When the requested block is unknown the remote peer should return no results.  We were incorrectly requiring a block to be returned in the utility methods that request a single block by root or slot.

## Fixed Issue(s)
fixes #3027 

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

**Review by Nashatyrev — APPROVED** [review]
LGTM

File: networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/peers/PeerChainValidator.java [hunk 1]
```diff
@@ -183,8 +183,6 @@ private boolean isForkValid(final Eth2Peer peer, final PeerStatus status) {
       LOG.trace(
           "Request required checkpoint block from peer {}: {}", peer.getId(), checkpointToVerify);
       return peer.requestBlockByRoot(checkpointToVerify.getRoot())
-          // Map result to an optional block
-          .thenApply(Optional::of)
           .exceptionally(
               err -> {
                 if (Throwables.getRootCause(err) instanceof NullPointerException) {
```
Comment (mbaxter) [inline networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/peers/PeerChainValidator.java]: We can cut this `exceptionally` call now 🎉
