### PR TITLE
Log full block when block import fails with internal error

### LINKED ISSUE #6021: Log full block when block import files with internal error
### Description
When we fail to import a block because of an internal error, it doesn't trigger the invalid gossip logging so we currently don't get any record of the actual block content that was invalid.  We should always log the full block content (as hex encoded ssz) when block import fails with internal error so we can fully investigate.

This shouldn't depend on the setting to log invalid gossip being enabled and should only apply to internal errors, not blocks we reject for being invalid.

### PR DESCRIPTION
**Pull request by StefanBratanov**
## PR Description
Enhance error log when importing a block with hex encoded ssz of the block contents.

## Fixed Issue(s)
fixes #6021 

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/block/BlockImporter.java [hunk 1]
```diff
@@ -213,6 +217,10 @@ private String formatBlock(final SignedBeaconBlock block) {
     return LogFormatter.formatBlock(block.getSlot(), block.getRoot());
   }
 
+  private String getBlockContent(final SignedBeaconBlock block) {
+    return block.getMessage().sszSerialize().toHexString();
```
Comment (ajsutton) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/block/BlockImporter.java]: We should log the whole signed block so just:
```suggestion
    return block.sszSerialize().toHexString();
```

**Review by ajsutton — APPROVED** [review]
LGTM just with the tweak to include the signature wrapper as well.
