### PR TITLE
Fix incorrect genesis time issue

### LINKED ISSUE #2323: Incorrect time to genesis reported
### Description
Teku seems to get timezones confused when reporting the time until genesis.  When I run `run.sh` it prints:
```
10:36:36.835 INFO  - 10:00:06 until genesis time is reached                                                           │10:36:36.578 INFO  - 10:00:06 until genesis time is reached
```

I'm in UTC+1000 and genesis is actually in 6 seconds time.  It kicks off correctly, just the info message that's wrong.

### PR DESCRIPTION
**Pull request by cemozerr**
## PR Description
Fix incorrect genesis time issue

## Fixed Issue(s)

Fixes https://github.com/PegaSysEng/teku/issues/2323

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

**Review by mbaxter — APPROVED** [review]

File: services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/BeaconChainController.java [hunk 1]
```diff
@@ -524,7 +525,7 @@ public void onTick(Date date) {
     if (recentChainData.isPreGenesis()) {
       return;
     }
-    final UnsignedLong currentTime = UnsignedLong.valueOf(date.getTime() / 1000);
+    final UnsignedLong currentTime = UnsignedLong.valueOf(Instant.now().getEpochSecond());
```
Comment (ajsutton) [inline services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/BeaconChainController.java]: We shouldn't be using `Instant.now()` here - I think `date.getTime()` was right.

File: logging/src/main/java/tech/pegasys/teku/logging/StatusLogger.java [hunk 2]
```diff
@@ -105,9 +105,11 @@ public void generatingMockStartGenesis(final long genesisTime, final int size) {
...
 
   public void timeUntilGenesis(final long timeToGenesis) {
-    log.info(
-        "{} until genesis time is reached",
-        () -> DateFormatUtils.format(timeToGenesis * 1000, "hh:mm:ss"));
+    long hours = timeToGenesis / 3600;
+    long minutes = (timeToGenesis % 3600) / 60;
+    long seconds = timeToGenesis % 60;
+    String timeString = String.format("%02d:%02d:%02d", hours, minutes, seconds);
+    log.info("{} until genesis time is reached", timeString);
```
Comment (ajsutton) [inline logging/src/main/java/tech/pegasys/teku/logging/StatusLogger.java]: This doesn't feel like the right solution - I suspect we just needed to specify UTC as the timezone in the call to `DateFormatUtils`:
```suggestion
    log.info("{} until genesis time is reached", () -> DateFormatUtils.formatUTC(timeToGenesis * 1000, "hh:mm:ss");
```

File: services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/BeaconChainController.java [hunk 3]
```diff
@@ -506,7 +507,7 @@ private void setupInitialState() {
 
   private void onStoreInitialized() {
     UnsignedLong genesisTime = recentChainData.getGenesisTime();
-    UnsignedLong currentTime = UnsignedLong.valueOf(System.currentTimeMillis() / 1000);
+    UnsignedLong currentTime = UnsignedLong.valueOf(Instant.now().getEpochSecond());
```
Comment (ajsutton) [inline services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/BeaconChainController.java]: Would be nice to avoid using `Instant.now()` here and get the time via `TimeProvider` if possible but if it's not available I can live with it since it was already using `System.currentTimeMillis`.  No real reason I can see to change this though.

File: logging/src/main/java/tech/pegasys/teku/logging/StatusLogger.java (hunk 2 above)
Comment (ajsutton) [reply logging/src/main/java/tech/pegasys/teku/logging/StatusLogger.java]: Sorry I'm wrong about this.  The problem is we're trying to use a time formatter to format a duration.  We should be using `DurationFormatUtils` not `DateFormatUtils`.  Personally I quite like `formatWords` version:
```
        () -> DurationFormatUtils.formatDurationWords(timeToGenesis * 1000, true, true));
```

which gives:
`1157 days 12 hours 27 minutes 20 seconds until genesis time is reached`
or
`4 seconds until genesis time is reached`

File: services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/BeaconChainController.java (hunk 1 above)
Comment (ajsutton) [reply services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/BeaconChainController.java]: Both `Instant.now()` usages can actually be replaced with `timeProvider.getTimeInSeconds()` which avoids any need to convert millis to seconds and still uses our abstraction for time.

Comment (cemozerr) [reply services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/BeaconChainController.java]: Makes a lot of sense 👍

File: services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/BeaconChainController.java (hunk 3 above)
Comment (cemozerr) [reply services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/BeaconChainController.java]: Switching to timeProvider.

File: logging/src/main/java/tech/pegasys/teku/logging/StatusLogger.java (hunk 2 above)
Comment (cemozerr) [reply logging/src/main/java/tech/pegasys/teku/logging/StatusLogger.java]: Done.
