### PR TITLE
Avoid reprocessing the last stored deposit block on startup

### LINKED ISSUE #2243: Incorrect Genesis when calculated in "real time"
This was observed for Altona network genesis. When tracking the deposit contract "in real time" we got the following at the moment that `is_valid_genesis_state()` was first true (`GENESIS_DELAY - ETH1_FOLLOW_DISTANCE * SECONDS_PER_ETH1_BLOCK` seconds before `MIN_GENESIS_TIME`):

```
2020-06-27 16:46:14.274+00:00 | Eth1EventsChannel-2 | INFO  | teku-event-log | ^[[36mGenesis Event *** Initial state root: 0x692e5b2e01a21f46ca232cae86ae29c72e0e0ce18fc528d5de9f2f4b93e43f1f, Genesis block root: 0x980238061b46a5a79ba00f395daded137d529bae944d3ecaf43c0208fc4b9582^[[0m
```

This differed from Prysm.

Deleting the DB (yep, should have saved it, but I nuked it) and re-running Teku after this time obtained different genesis data, which matches Prysm's:

```
2020-06-27 17:43:26.069+00:00 | Eth1EventsChannel-2 | INFO  | teku-event-log | ^[[36mGenesis Event *** Initial state root: 0x939d98077986a9f6eccae33614e2da1008a2f300f1aac36bc65ef710550eec4a, Genesis block root: 0x9e2ffe8ab9316e03e45409eaaffab10cf02e1b60e609276113e07240d4a31b7a^[[0m
```

In both cases, the genesis time was correctly set to 1593433805, and 685 validators were registered.

```
$ ./build/install/teku/bin/teku --version
teku/v0.12.0-dev-50fa4ed6/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13
```

This may relate to a deposit ordering issue first discussed [on Discord](https://discord.com/channels/476244492043812875/619926417970429962/721131014314786827).

The definitive data from @protolambda:
```
state hash-tree-root: 939d98077986a9f6eccae33614e2da1008a2f300f1aac36bc65ef710550eec4a
genesis latest header root: eade62f0457b2fdf48e7d3fc4b60736688286be7c7a3ac4c9a16a5e0600bd9e4
genesis latest header root (with updated state root): 9e2ffe8ab9316e03e45409eaaffab10cf02e1b60e609276113e07240d4a31b7a
validator reg root: 1b244843b4aa8d14d59a3e397f0a02318eefa229ae68209de78418b2fc07f794
validator count: 685
eth1 data: Eth1Data(Container)
    deposit_root: Root = 0x14ad54cce180f0bc3c31a59c37c38125ab9120b1eae83946de906228a937f249
    deposit_count: uint64 = 1078
    block_hash: SpecialByteVectorView = 0x1b75ab3e138be05eb83d084ac54c4887e9ba6b83fa5c73d8b73a30ffdcd75faa
dep index: 1078
```

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
When Teku is restarted it replays deposits from it's local database and then resumes importing blocks from the ETH1 chain from there.  Previously it was incorrectly starting from the block the last stored deposit was from instead of the block after, resulting in the deposit being processed twice.

* Tidied up the block number processing so it's easier to understand and fix the off by one errors.  
* Added tests for `Eth1DepositManager`.
* Added a couple of debug utilities to be able to get finalised states in SSZ format.

## Fixed Issue(s)
fixes #2243 

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: storage/src/main/java/tech/pegasys/teku/storage/server/DepositStorage.java [hunk 1]
```diff
@@ -104,14 +98,14 @@ public void onMinGenesisTimeBlock(final MinGenesisTimeBlockEvent event) {
...
-    private UnsignedLong lastDeposit;
+    private BigInteger lastDeposit;
 
     public DepositSequencer(
         final Eth1EventsChannel eventChannel, final Optional<MinGenesisTimeBlockEvent> genesis) {
       this.eth1EventsChannel = eventChannel;
       this.genesis = genesis;
       this.isGenesisDone = false;
-      this.lastDeposit = UnsignedLong.ZERO;
+      this.lastDeposit = BigInteger.valueOf(-1);
```
Comment (rolfyone) [inline storage/src/main/java/tech/pegasys/teku/storage/server/DepositStorage.java]: nit: should use constant since its defined

**Review by rolfyone — APPROVED** [review]
LGTM, one minor nit.
