### PR TITLE
Calculate ETH1 deposit count and root based on event logs

### LINKED ISSUE #1813: Eth1RequestException: Eth1 call has failed:missing trie node
### Description
Trying to bootstrap a new testnet. Teku does not do anything. Maybe because it's prior to genesis time?

### Steps to Reproduce (Bug)
https://github.com/goerli/schlesi/tree/master/teku

* connect a teku node to a geth node
* teku eth1_follow_distance is 1024
* geth tries_in_memory value is 128

**Expected behavior:** [What you expect to happen]

It should launch the beacon node and validators.

**Actual behavior:** [What actually happens]

It doesn't do anything for more than 40 minutes:

```
~/.opt/PegaSysEng/teku master 15m 16s
❯ 
teku \
--config-file="/home/user/.opt/goerli/witti/teku/config.yaml" \
--network="/home/user/.opt/goerli/witti/teku/chain.yaml"


^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C

~/.opt/PegaSysEng/teku master 43m 55s
❯ 
teku \
--config-file="/home/user/.opt/goerli/witti/teku/config.yaml" \
--network="/home/user/.opt/goerli/witti/teku/chain.yaml"

```

**Frequency:** 1

### Versions (Add all that apply)
* Software version: `teku/v0.11.2-dev-982608ec/linux-x86_64/oracle_openjdk-java-11`
* Java version: `openjdk version "11.0.6" 2020-01-14`
* OS Name & Version: `NAME="Arch Linux"`
* Kernel Version: `Linux ceres 5.6.10-arch1-1 #1 SMP PREEMPT Sat, 02 May 2020 19:11:54 +0000 x86_64 GNU/Linux`

### LINKED ISSUE #1863: Better handle Eth1Node not having necessary cache capacity
https://github.com/PegaSysEng/artemis/compare/master...cemozerr:reportEth1NodeArchivalCacheStaleError?expand=1

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
Reworks how `Eth1Data` is collected so that there is no longer a dependency on having ETH1 world state available. All information is built up from the deposit event logs.

On both the PoWService and BeaconChainService sides, `Eth1Data` is now controlled by the deposit handling, rather than separate. This allows us to guarantee that all deposit data is processed before the `Eth1Data` for any empty blocks is filled in.

On the PoWService side:
 1. empty blocks are completely ignored until all deposits are processed up to the ETH1 follow distance from head.  This avoids querying old block data unnecessarily.
 2. Once follow distance has been reached, block data is fetched walking backwards from that latest block until a block is reached with a timestamp prior to the caching period. This handles filling the cache at initial startup
 3. As the chain moves forward, deposits are requested and processed for the unprocessed range, then any blocks without deposits in that range are requested.

On the BeaconChain side:
 * `DepositProvider` continues to receive and process all deposits. After all deposits in a block are processed it notifies `Eth1DataCache` of the block and the new `Eth1Data` associated with that block (generated from the deposit Merkle tree).
 * `DepositProvider` also passes block information for blocks without deposits to `Eth1DataCache`.  `Eth1DataCache` uses the same deposit root and count as the prior block from its cache for this blocks (as with no deposits in the block they must be unchanged).

## Fixed Issue(s)
fixes #1813 
fixes #1863

### CODE REVIEW

File: pow/src/main/java/tech/pegasys/teku/pow/Eth1BlockFetcher.java [hunk 1]
```diff
@@ -0,0 +1,153 @@
...
+              if (isAboveLowerBound(UnsignedLong.valueOf(block.getTimestamp()))) {
+                postBlock(block);
+              } else {
+                // Every block before the one we just fetched must be outside of the range
+                synchronized (Eth1BlockFetcher.this) {
+                  // All blocks at or before this number must be before the cache period
+                  blocksToRequest.headSet(blockNumberToRequest, true).clear();
+                }
+              }
+              requestNextBlockIfRequired();
```
Comment (cemozerr) [inline pow/src/main/java/tech/pegasys/teku/pow/Eth1BlockFetcher.java]: This line seems redundant. Every time `requestNextBlockIfRequired ` calls `requestBlock`, it sets `requestInProgress` to `true`. However, `requestNextBlockIfRequired` does not set `requestInProgress` to `false`. So `requestNextBlockIfRequired`returns early every time its called inside `requestBlock`.

File: pow/src/main/java/tech/pegasys/teku/pow/Eth1BlockFetcher.java [hunk 2]
```diff
@@ -0,0 +1,153 @@
...
+
+  private void postBlock(final Block block) {
+    eth1EventsChannel.onEth1Block(
+        Bytes32.fromHexString(block.getHash()), UnsignedLong.valueOf(block.getTimestamp()));
+  }
+
+  private void backfillEth1Blocks(final UnsignedLong nextBlockToRequest) {
+    // Walk backwards from blockNumber until we reach the start of the voting period
+    eth1Provider
+        .getGuaranteedEth1BlockFuture(nextBlockToRequest)
```
Comment (cemozerr) [inline pow/src/main/java/tech/pegasys/teku/pow/Eth1BlockFetcher.java:131]: Is there a reason why you used guaranteed requests here? Missing some blocks does seem better than potentially getting stuck retrying a block, similar to the case above.

File: validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/Eth1DataCache.java [hunk 3]
```diff
@@ -13,50 +13,48 @@
...
 
-  @Subscribe
-  public void onCacheEth1BlockEvent(CacheEth1BlockEvent cacheEth1BlockEvent) {
-    final UnsignedLong latestBlockTimestamp = cacheEth1BlockEvent.getBlockTimestamp();
-    eth1ChainCache.put(latestBlockTimestamp, createEth1Data(cacheEth1BlockEvent));
-    prune(latestBlockTimestamp);
+  public void onEth1Block(final Bytes32 blockHash, final UnsignedLong blockTimestamp) {
+    final Entry<UnsignedLong, Eth1Data> previousBlock = eth1ChainCache.floorEntry(blockTimestamp);
+    if (previousBlock == null) {
+      // This block is either before any deposits so will never be voted for
```
Comment (cemozerr) [inline validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/Eth1DataCache.java:50]: Adding a `LOG.debug` here might be useful, in case we're getting too many redundant blocks from `Eth1BlockFetcher`

**Review by cemozerr — APPROVED** [review]
LGTM.

**Comment by protolambda** [comment]
Fetching every single eth1 block is quite extreme, I wonder if that can be more optimal. In my python debug code, I backfill by querying for ranges of logs (block number ranges): https://github.com/protolambda/e2db/blob/065a194c4b12f4984175c034c572669581ff9b69/e2db/depwatch/monitor.py#L149

**Comment by ajsutton** [comment]
> Fetching every single eth1 block is quite extreme, I wonder if that can be more optimal.

We're not fetching every block - when first starting up, we use log queries to find the deposit events until we reach the head of the chain (less follow distance).  Once we're there, we kick off a process to walk backwards and backfill the empty blocks in the eth1 voting period (we could skip blocks we know have deposits here but currently don't for simplicity). We stop as soon as we reach a block with a timestamp prior to the voting period we'll need.

After that we're essentially tracking head so each new block that comes in we need to download, including any deposits in it as it's a valid candidate for an Eth1Data vote.

If we only considered blocks with deposit events in them then we would consider any vote for blocks without deposits as invalid because we wouldn't know the block hash.

File: pow/src/main/java/tech/pegasys/teku/pow/Eth1BlockFetcher.java (hunk 1 above)
Comment (ajsutton) [reply pow/src/main/java/tech/pegasys/teku/pow/Eth1BlockFetcher.java]: Yes it is, that logic got moved to the `.always` but I missed this call.

File: pow/src/main/java/tech/pegasys/teku/pow/Eth1BlockFetcher.java (hunk 2 above)
Comment (ajsutton) [reply pow/src/main/java/tech/pegasys/teku/pow/Eth1BlockFetcher.java:131]: I'm in two minds about it.  Ultimately I went with guaranteed here in backfill and not the normal case because if the node is down or overloaded briefly during backfill we'll potentially miss fairly large numbers of blocks and not backfill the cache properly.  If it's down briefly in the normal case, we likely only miss a couple of blocks (because normally we're querying one new block about every 15 seconds).

File: validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/Eth1DataCache.java (hunk 3 above)
Comment (ajsutton) [reply validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/Eth1DataCache.java:50]: Done.

File: pow/src/main/java/tech/pegasys/teku/pow/Eth1BlockFetcher.java (hunk 2 above)
Comment (cemozerr) [reply pow/src/main/java/tech/pegasys/teku/pow/Eth1BlockFetcher.java:131]: That makes sense to me.
