### PR TITLE
Don't mark peers as permanently unsuitable when they fail to respond to ping

### LINKED ISSUE #2200: Failed to recover after network outage
As far as I can tell, my netework was down for about 17 minutes overnight. Teku failed to recover from this - it only regained 3 peers and two hours later had none. It seemed to go off on its own fork: every slot in the 6 hours since is marked empty.

I've been using Infura for Eth1 data rather than a local Eth1 node. This may or may not be a factor.

Restarting (from the same database) swiftly brought Teku back onto the right fork and all is well again.

I have INFO level logs saved if they are of interest.

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
When the network connection is interrupted in a way that the local machine can't immediately detect (e.g. router suddenly powering off) all connected peers wind up being disconnected because they don't respond to pings.  Previously this caused them to be marked as permanently unsuitable and Teku would no longer initiate connections to them (incoming connections would still be accepted).

Now not responding to pings invokes a temporary penalty but after that Teku will again initiate connections to the peer.  On small networks this significantly improves the ability to recover after a network outage.

## Fixed Issue(s)
fixes #2200 

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

File: networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/peer/DisconnectReason.java [hunk 1]
```diff
@@ -23,6 +23,7 @@
   UNABLE_TO_VERIFY_NETWORK(GoodbyeMessage.REASON_UNABLE_TO_VERIFY_NETWORK, true),
   TOO_MANY_PEERS(GoodbyeMessage.REASON_TOO_MANY_PEERS, false),
   REMOTE_FAULT(GoodbyeMessage.REASON_FAULT_ERROR, false),
+  NO_PING_RESPONSES(GoodbyeMessage.REASON_FAULT_ERROR, false),
```
Comment (mbaxter) [inline networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/peer/DisconnectReason.java]: This is outside the scope of this PR - but seems like this eth2-specific logic (`GoodbyeMessage` / PING behavior) should be in the `eth2` package.

File: networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/connection/ReputationManager.java [hunk 2]
```diff
@@ -71,6 +75,9 @@ private Reputation getOrCreateReputation(final PeerAddress peerAddress) {
   }
 
   private static class Reputation {
+    private static final EnumSet<DisconnectReason> LOCAL_TEMPORARY_DISCONNECT_REASONS =
```
Comment (mbaxter) [inline networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/connection/ReputationManager.java:78]: Probably worth adding a test + some comments on the situation this fixes.

**Review by mbaxter — APPROVED** [review]
