### PR TITLE
Fix Altair finality

### LINKED ISSUE #3654: HF1 - update ref tests
https://github.com/ChainSafe/eth2.0-spec-tests/releases/tag/v1.0.0-hf1.0

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
The calculation of `TotalBalances` for Altair was slightly incorrect.  In Phase0 the validator must be a previous epoch source validator in order to be a previous epoch target validator, but that's not true in Altair.  If the `TIMELY_TARGET_FLAG_INDEX` is set, that validator's balance should count towards justification and finality.

Also introduced the `weighJustificationAndFinalization` method to better match the arrangement of code in the spec (but no change to the actual behaviour there).

## Fixed Issue(s)
fixes #3654 

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/common/statetransition/epoch/status/TotalBalances.java [hunk 1]
```diff
@@ -37,63 +35,64 @@ public TotalBalances(
...
-    this.previousEpochHeadAttesters = previousEpochHeadAttesters;
+    UInt64 effectiveBalanceIncrement = specConfig.getEffectiveBalanceIncrement();
+    this.currentEpochActiveValidators = currentEpochActiveValidators.max(effectiveBalanceIncrement);
+    this.previousEpochActiveValidators =
+        previousEpochActiveValidators.max(effectiveBalanceIncrement);
+    this.currentEpochSourceAttesters = currentEpochSourceAttesters.max(effectiveBalanceIncrement);
+    this.currentEpochTargetAttesters = currentEpochTargetAttesters.max(effectiveBalanceIncrement);
+    this.previousEpochSourceAttesters = previousEpochSourceAttesters.max(effectiveBalanceIncrement);
+    this.previousEpochTargetAttesters = previousEpochTargetAttesters.max(effectiveBalanceIncrement);
+    this.previousEpochHeadAttesters = previousEpochHeadAttesters.max(effectiveBalanceIncrement);
```
Comment (ajsutton) [inline ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/common/statetransition/epoch/status/TotalBalances.java:46]: Applied the max once in the constructor instead of on every get call.

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/altair/statetransition/epoch/ValidatorStatusFactoryAltair.java [hunk 2]
```diff
@@ -52,33 +53,86 @@ protected void processParticipation(
...
+            currentParticipationFlags, ParticipationFlags.TIMELY_SOURCE_FLAG_INDEX)) {
+          status.updateCurrentEpochSourceAttester(true);
+        }
+        if (miscHelpersAltair.hasFlag(
+            currentParticipationFlags, ParticipationFlags.TIMELY_TARGET_FLAG_INDEX)) {
+          status.updateCurrentEpochTargetAttester(true);
+        }
       }
     }
+  }
```
Comment (ajsutton) [inline ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/altair/statetransition/epoch/ValidatorStatusFactoryAltair.java]: Behaviour here didn't actually change but we now only iterate through the validator set once instead of twice. We can also skip accessing the participation flags entirely for any validators that weren't active in that epoch as they can't have attested (and matches the spec better which iterates through the active validators for the epoch).

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/altair/statetransition/epoch/ValidatorStatusFactoryAltair.java [hunk 3]
```diff
@@ -52,33 +53,86 @@ protected void processParticipation(
...
+    return new TotalBalances(
+        specConfig,
+        currentEpochActiveValidators,
+        previousEpochActiveValidators,
+        currentEpochSourceAttesters,
+        currentEpochTargetAttesters,
+        previousEpochSourceAttesters,
+        previousEpochTargetAttesters,
+        previousEpochHeadAttesters);
   }
```
Comment (ajsutton) [inline ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/altair/statetransition/epoch/ValidatorStatusFactoryAltair.java]: This is the key change - almost identical to the phase0 version but performs each check independently instead of nesting checks under the `isCurrentEpochSourceAttester` or `isPreviousSourceAttester` checks.

Comment (mbaxter) [reply ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/altair/statetransition/epoch/ValidatorStatusFactoryAltair.java]: I think we can just make this change in the abstract base class so that we don't have to duplicate the logic here.

**Review by mbaxter — APPROVED** [review]
Good find, nice clean-up - I'd look into whether we can avoid duplicating the total balance logic, but otherwise LGTM!

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/altair/statetransition/epoch/ValidatorStatusFactoryAltair.java (hunk 3 above)
Comment (ajsutton) [reply ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/altair/statetransition/epoch/ValidatorStatusFactoryAltair.java]: Yeah took me a bit of reasoning but we only set the correct head flag if the target was correct so can skip the nesting here for both versions.  Good spot.
