### PR TITLE
Validator id parameters should not be rejected for bytes48 not on g2 curve

### LINKED ISSUE #4787: Validator PubKey Validation Inconsistent With Other Clients
Teku's validation of validator pub keys in `/eth/v1/beacon/states/{state_id}/validators` is inconsistent with other clients.

If you make a call to the above endpoint with one or more invalid pub keys in the `id` parameter such as `0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001`, Teku responds with the following error:

```
{"status":400,"message":"Invalid public key: 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001"}
```

Other major clients ignore pub keys that don't match an existing validator regardless of whether the pub key is valid or not. The [Eth Beacon Node API](https://ethereum.github.io/beacon-APIs/#/Beacon/getStateValidators) specifies `If an index or public key does not match any known validator, no information will be returned but this will not cause an error.`. While it doesn't explicitly state that invalid pub keys should be ignored it can be interpreted that way and indeed other client implementation (perhaps unintentionally) took that interpretation.

Other clients tested: Nimbus, Prysm, Lighthouse.

### PR DESCRIPTION
**Pull request by rolfyone**
If a bytes48 key is provided that can't be validated on the curve, treat it as a missed key, not an invalid request. In a large list of bytes48 a single key will otherwise reject the entire request, where we could instead just process the rest of the request.

Internally we still need to map keys to the curve to be able to search for the key, so for any valid bytes48 we will still end up having to map to the curve to find the key.

0x hex with invalid length will still be rejected as a bad request.

fixes #4787

Signed-off-by: Paul Harris <paul.harris@consensys.net>

## Documentation

- [X] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java [hunk 1]
```diff
@@ -266,11 +257,13 @@ public boolean isFinalized(final UInt64 slot) {
...
 
     if (validatorParameter.toLowerCase().startsWith("0x")) {
+      final Bytes48 keyBytes = getBytes48FromParameter(validatorParameter);
       try {
-        BLSPubKey publicKey = BLSPubKey.fromHexString(validatorParameter);
-        return spec.getValidatorIndex(state, publicKey.asBLSPublicKey());
-      } catch (PublicKeyException ex) {
-        throw new BadRequestException(String.format("Invalid public key: %s", validatorParameter));
+        // validate key against g2 curve
+        return spec.getValidatorIndex(state, BLSPublicKey.fromBytesCompressedValidate(keyBytes));
```
Comment (ajsutton) [inline data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java]: I thought the aim was to *not* validate against the g2 curve?  I'd have just called `fromBytesCompressed` here (and then we shouldn't need the try/catch as we wouldn't be doing the G2 validation.

**Review by ajsutton — APPROVED** [review]
LGTM.
